import { QuizQuestion } from '@/types';

export const basicQuizzesData: Record<string, Omit<QuizQuestion, 'id' | 'quizId'>[]> = {
  // ==================== LEVEL 1: BASIC ====================
  // 1. CIA Triad & Fundamentals
  'lesson-b1-1': [
    {
      question: 'เสาหลักข้อใดใน CIA Triad ที่ทำหน้าที่รับรองว่าข้อมูลลับจะไม่ถูกเปิดเผยต่อผู้ที่ไม่ได้รับอนุญาต?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Confidentiality (การรักษาความลับ)' },
        { key: 'B', text: 'Integrity (ความถูกต้องสมบูรณ์)' },
        { key: 'C', text: 'Availability (ความพร้อมใช้งาน)' },
        { key: 'D', text: 'Non-repudiation (การห้ามปฏิเสธความรับผิดชอบ)' },
      ],
      correctAnswer: 'A',
      explanation: 'Confidentiality มุ่งเน้นการปกป้องข้อมูลสำคัญไม่ให้ถูกเปิดเผยหรือเข้าถึงโดยบุคคลที่ไม่มีสิทธิ์ ผ่านการเข้ารหัสและการกำหนดสิทธิ์',
      order: 1,
    },
    {
      question: 'มาตรการควบคุมความปลอดภัยข้อใดสนับสนุนเสาหลัก "Integrity (ความถูกต้องสมบูรณ์)" ได้ตรงจุดที่สุด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การทำ Cryptographic Hashing (เช่น SHA-256) และ Digital Signatures' },
        { key: 'B', text: 'การติดตั้งระบบสำรองไฟฉุกเฉิน (UPS)' },
        { key: 'C', text: 'การติดตั้ง Load Balancer เพื่อกระจายภาระงาน' },
        { key: 'D', text: 'การบังคับให้เชื่อมต่อผ่าน VPN เท่านั้น' },
      ],
      correctAnswer: 'A',
      explanation: 'Cryptographic Hashes และ Digital Signatures ช่วยตรวจสอบว่าข้อมูลไม่มีการถูกแก้ไข เปลี่ยนแปลง หรือดัดแปลงระหว่างทาง',
      order: 2,
    },
    {
      question: 'การโจมตีประเภท DDoS (Distributed Denial of Service) ส่งผลกระทบต่อเสาหลักใดใน CIA Triad โดยตรง?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Availability (ความพร้อมใช้งาน)' },
        { key: 'B', text: 'Confidentiality (การรักษาความลับ)' },
        { key: 'C', text: 'Integrity (ความถูกต้องสมบูรณ์)' },
        { key: 'D', text: 'Authentication (การยืนยันตัวตน)' },
      ],
      correctAnswer: 'A',
      explanation: 'DDoS มุ่งส่งทราฟฟิกมหาศาลเพื่อทำให้บริการหรือเซิร์ฟเวอร์ไม่สามารถให้บริการแก่ผู้ใช้งานทั่วไปได้ตามปกติ ซึ่งกระทบต่อ Availability โดยตรง',
      order: 3,
    },
    {
      question: 'ในทางความมั่นคงปลอดภัยสารสนเทศ "Asset (ทรัพย์สิน)" มีความหมายครอบคลุมสิ่งใดบ้าง?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ข้อมูล, ซอฟต์แวร์, โครงสร้างพื้นฐาน, บุคลากร หรืออุปกรณ์ใดๆ ที่มีคุณค่าต่อองค์กร' },
        { key: 'B', text: 'เฉพาะเครื่องเซิร์ฟเวอร์ที่ติดตั้งใน Data Center เท่านั้น' },
        { key: 'C', text: 'เฉพาะหน้าเว็บไซต์ที่เปิดให้คนภายนอกเข้าถึง' },
        { key: 'D', text: 'เฉพาะเงินสดและบัญชีธนาคารของบริษัท' },
      ],
      correctAnswer: 'A',
      explanation: 'Asset ครอบคลุมทั้งข้อมูลสำคัญ ฮาร์ดแวร์ ซอฟต์แวร์ โครงสร้างพื้นฐาน และบุคลากรที่มีคุณค่าต่อภารกิจขององค์กร',
      order: 4,
    },
    {
      question: 'ข้อใดอธิบายความแตกต่างระหว่าง "Threat (ภัยคุกคาม)" และ "Vulnerability (ช่องโหว่)" ได้ถูกต้องที่สุด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Threat คือตัวกระทำหรือเหตุการณ์ที่อาจสร้างความเสียหาย ส่วน Vulnerability คือจุดอ่อนหรือข้อบกพร่องของระบบ' },
        { key: 'B', text: 'Threat คือโปรแกรมป้องกันไวรัส ส่วน Vulnerability คือระบบปฏิบัติการ' },
        { key: 'C', text: 'ทั้งสองคำเป็นคำที่มีความหมายเหมือนกันทุกประการ' },
        { key: 'D', text: 'Vulnerability คือผู้ไม่ประสงค์ดี ส่วน Threat คือบั๊กในโค้ด' },
      ],
      correctAnswer: 'A',
      explanation: 'Threat คือตัวกระทำ/สถานการณ์ที่อาจสร้างอันตราย ส่วน Vulnerability คือจุดบกพร่องที่เปิดช่องให้ Threat นั้นสร้างความเสียหายได้',
      order: 5,
    },
    {
      question: 'หลักการ "Defense-in-Depth" (การป้องกันแบบเชิงลึกหลายชั้น) มีเป้าหมายสำคัญอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การวางมาตรการป้องกันความปลอดภัยซ้อนกันหลายระดับ เพื่อไม่ให้จุดบกพร่องจุดเดียวทำให้ระบบล่มทั้งระบบ' },
        { key: 'B', text: 'การใช้ Firewall ยี่ห้อที่ดีที่สุดเพียงตัวเดียวเพื่อประหยัดงบประมาณ' },
        { key: 'C', text: 'การปิดการเชื่อมต่ออินเทอร์เน็ตทั้งหมดอย่างถาวร' },
        { key: 'D', text: 'การเปลี่ยนรหัสผ่านทุกๆ 15 นาที' },
      ],
      correctAnswer: 'A',
      explanation: 'Defense-in-Depth คือการวางระบบความปลอดภัยหลายชั้น (Network, Host, App, Data) เพื่อให้ชั้นอื่นยังคงปกป้องระบบได้หากชั้นใดชั้นหนึ่งถูกเจาะ',
      order: 6,
    },
    {
      question: 'หลักการ Principle of Least Privilege (PoLP) กำหนดแนวทางปฏิบัติอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ให้สิทธิ์แก่ผู้ใช้และกระบวนการเฉพาะเท่าที่จำเป็นต่อการปฏิบัติหน้าที่ของตนเท่านั้น' },
        { key: 'B', text: 'มอบสิทธิ์ระดับ Administrator ให้กับพนักงานทุกคนเพื่อความสะดวกรวดเร็ว' },
        { key: 'C', text: 'ห้ามไม่ให้พนักงานเข้าถึงอินเทอร์เน็ตเลยเด็ดขาด' },
        { key: 'D', text: 'อนุญาตให้ทุกเซิร์ฟเวอร์ติดต่อกันได้โดยไม่ต้องยืนยันตัวตน' },
      ],
      correctAnswer: 'A',
      explanation: 'Least Privilege ช่วยลดความเสียหาย (Blast Radius) หากบัญชีหรือบริการนั้นถูกผู้ไม่ประสงค์ดีเข้าควบคุม',
      order: 7,
    },
    {
      question: 'แนวคิด "Non-Repudiation" (การไม่สามารถปฏิเสธความรับผิดชอบได้) มักอาศัยเทคโนโลยีใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Digital Signatures (ลายมือชื่อดิจิทัล) และ Audit Logs ที่ปลอดภัย' },
        { key: 'B', text: 'การบีบอัดไฟล์แบบ ZIP' },
        { key: 'C', text: 'การตั้งชื่อไฟล์ด้วยตัวพิมพ์ใหญ่ทั้งหมด' },
        { key: 'D', text: 'การใช้รหัสผ่านที่มีความยาว 4 หลัก' },
      ],
      correctAnswer: 'A',
      explanation: 'ลายมือชื่อดิจิทัลและบันทึกประวัติที่แก้ไขไม่ได้ช่วยพิสูจน์ว่าผู้ส่งเป็นผู้ทำธุรกรรมจริงและไม่สามารถปฏิเสธได้',
      order: 8,
    },
    {
      question: 'การยืนยันตัวตนแบบ Multi-Factor Authentication (MFA) ต้องประกอบด้วยปัจจัยต่างหมวดหมู่อย่างน้อยกี่ประเภท?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'อย่างน้อย 2 ปัจจัยจากหมวดหมู่ที่แตกต่างกัน (สิ่งที่รู้, สิ่งที่มี, สิ่งที่เป็น)' },
        { key: 'B', text: 'การใช้รหัสผ่าน 2 ตัวที่ตั้งไว้คนละแบบ' },
        { key: 'C', text: 'การพิมพ์รหัสผ่านเดิมซ้ำ 2 ครั้ง' },
        { key: 'D', text: 'การใช้อีเมล 2 บัญชีในการลงทะเบียน' },
      ],
      correctAnswer: 'A',
      explanation: 'MFA ต้องใช้ปัจจัยคนละหมวด เช่น Something you know (รหัสผ่าน) ร่วมกับ Something you have (OTP / Hardware Token) หรือ Something you are (ลายนิ้วมือ)',
      order: 9,
    },
    {
      question: 'แฮกเกอร์ประเภท "White Hat" (หมวกขาว) มีลักษณะการทำงานอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ผู้เชี่ยวชาญความปลอดภัยที่ได้รับอนุญาตถูกต้อง ทำหน้าที่ค้นหาและช่วยแก้ไขช่องโหว่เชิงจริยธรรม' },
        { key: 'B', text: 'ผู้ที่โจมตีระบบเพื่อเรียกค่าไถ่และนำเงินไปบริจาค' },
        { key: 'C', text: 'ผู้ที่โจมตีระบบโดยไม่มีการขออนุญาตเพื่อทดสอบฝีมือตนเอง' },
        { key: 'D', text: 'ผู้สร้างมัลแวร์เพื่อปล่อยลงในดาร์กเว็บ' },
      ],
      correctAnswer: 'A',
      explanation: 'White Hat หรือ Ethical Hacker ปฏิบัติตามกฎหมายและได้รับอนุญาตจากเจ้าของระบบเพื่อค้นหาช่องโหว่และช่วยเสริมความปลอดภัย',
      order: 10,
    },
    {
      question: 'สมการการคำนวณความเสี่ยง (Risk Calculation) พื้นฐานในทางความมั่นคงปลอดภัยคืออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Risk = Threat × Vulnerability × Impact (หรือ Likelihood × Impact)' },
        { key: 'B', text: 'Risk = จำนวนเครื่องเซิร์ฟเวอร์ ÷ ความเร็วอินเทอร์เน็ต' },
        { key: 'C', text: 'Risk = จำนวนผู้ใช้งาน × ขนาดของฐานข้อมูล' },
        { key: 'D', text: 'Risk = ราคาของ Firewall + ค่าไฟฟ้าของ Data Center' },
      ],
      correctAnswer: 'A',
      explanation: 'ความเสี่ยงเกิดจากการรวมกันของโอกาสที่จะเกิดเหตุการณ์ (Threat & Vulnerability) และระดับความเสียหายที่ส่งผลกระทบต่อองค์กร (Impact)',
      order: 11,
    },
    {
      question: 'แนวคิด "Security through Obscurity" (ความปลอดภัยด้วยการปิดบังซ่อนเร้น) ได้รับการยอมรับในมาตรฐานสากลหรือไม่ เพราะเหตุใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ไม่ได้รับการยอมรับ: การซ่อนข้อมูลเพียงอย่างเดียวไม่ถือเป็นความปลอดภัย หากผู้โจมตีล่วงรู้โครงสร้างก็จะเจาะได้ทันที' },
        { key: 'B', text: 'ได้รับการยอมรับสูงสุด: เพราะเป็นวิธีที่ประหยัดงบประมาณที่สุด' },
        { key: 'C', text: 'ได้รับการยอมรับ: หากเปลี่ยนพอร์ตเชื่อมต่อแล้วระบบจะไม่มีวันถูกเจาะ' },
        { key: 'D', text: 'ได้รับการยอมรับ: เฉพาะกับระบบที่เขียนด้วยภาษาซี' },
      ],
      correctAnswer: 'A',
      explanation: 'ตามหลักการ Kerckhoffs ระบบต้องมีความปลอดภัยในตัวเองแม้โครงสร้างทั้งหมดจะถูกเปิดเผยก็ตาม การซ่อนพอร์ตหรือซ่อนชื่อไม่ใช่มาตรการหลักที่เพียงพอ',
      order: 12,
    },
    {
      question: 'การจัดระดับชั้นความลับของข้อมูล (Data Classification) มีประโยชน์หลักอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ช่วยกำหนดมาตรการควบคุมความปลอดภัยและการเข้าถึงให้เหมาะสมกับระดับความสำคัญของข้อมูลแต่ละประเภท' },
        { key: 'B', text: 'ช่วยเพิ่มความเร็วในการดาวน์โหลดไฟล์ของผู้ใช้งาน' },
        { key: 'C', text: 'ทำให้ไม่ต้องทำระบบสำรองข้อมูลสำหรับข้อมูลสำคัญ' },
        { key: 'D', text: 'ทำให้สามารถเปิดเผยข้อมูลทุกอย่างสู่สาธารณะได้' },
      ],
      correctAnswer: 'A',
      explanation: 'Data Classification (เช่น Public, Internal, Confidential, Restricted) ช่วยให้องค์กรจัดสรรทรัพยากรและมาตรการป้องกันได้อย่างคุ้มค่าและรัดกุม',
      order: 13,
    },
    {
      question: 'ข้อใดคือตัวอย่างของ "Administrative / Organizational Control" (มาตรการควบคุมเชิงบริหารจัดการ)?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การกำหนดนโยบายความมั่นคงปลอดภัยสารสนเทศ (Security Policy) และการฝึกอบรมพนักงาน' },
        { key: 'B', text: 'การติดตั้ง Next-Generation Firewall บนเครือข่าย' },
        { key: 'C', text: 'การติดตั้งประตูล็อคสแกนลายนิ้วมือเข้าห้อง Server' },
        { key: 'D', text: 'การเขียนโค้ดเพื่อกรอง SQL Injection' },
      ],
      correctAnswer: 'A',
      explanation: 'Administrative Control ครอบคลุมนโยบาย ขั้นตอนปฏิบัติ การฝึกอบรมสร้างความตระหนักรู้ และข้อตกลงในการปฏิบัติงาน',
      order: 14,
    },
    {
      question: 'ข้อใดคือตัวอย่างของ "Physical Control" (มาตรการควบคุมทางกายภาพ)?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'กล้องวงจรปิด (CCTV), ประตูคีย์การ์ด, และเจ้าหน้าที่รักษาความปลอดภัยเฝ้าห้องเซิร์ฟเวอร์' },
        { key: 'B', text: 'การตั้งค่ารหัสผ่านที่มีความซับซ้อน' },
        { key: 'C', text: 'การติดตั้งโปรแกรมตรวจจับสแปมอีเมล' },
        { key: 'D', text: 'การอัปเดตระบบปฏิบัติการ Windows Update' },
      ],
      correctAnswer: 'A',
      explanation: 'Physical Control คือมาตรการที่จับต้องได้เพื่อป้องกันไม่ให้บุคคลที่ไม่ได้รับอนุญาตเข้าถึงพื้นที่หรืออุปกรณ์ฮาร์ดแวร์โดยตรง',
      order: 15,
    },
    {
      question: 'ข้อใดคือตัวอย่างของ "Technical / Logical Control" (มาตรการควบคุมทางเทคนิค)?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การเข้ารหัสข้อมูล (Encryption), การตั้งค่า Access Control Lists (ACLs), และระบบ Firewall' },
        { key: 'B', text: 'การทำสัญญาจ้างงานพนักงานใหม่' },
        { key: 'C', text: 'รั้วลวดหนามรอบอาคารสำนักงาน' },
        { key: 'D', text: 'การจัดสัมมนาประจำปี' },
      ],
      correctAnswer: 'A',
      explanation: 'Technical Controls ใช้ฮาร์ดแวร์ ซอฟต์แวร์ และอัลกอริทึมในการควบคุมการเข้าถึงและปกป้องระบบดิจิทัล',
      order: 16,
    },
    {
      question: 'กระบวนการ "Identification" และ "Authentication" มีความสัมพันธ์กันอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Identification คือการระบุตัวตน (เช่น ป้อน Username) ส่วน Authentication คือการพิสูจน์ว่าเป็นตัวจริง (เช่น ป้อน Password/OTP)' },
        { key: 'B', text: 'Identification คือการให้สิทธิ์เข้าถึง ส่วน Authentication คือการบันทึก Log' },
        { key: 'C', text: 'ทั้งสองคำหมายถึงการตั้งรหัสผ่านใหม่' },
        { key: 'D', text: 'Identification ใช้เฉพาะบนมือถือ ส่วน Authentication ใช้บนเซิร์ฟเวอร์' },
      ],
      correctAnswer: 'A',
      explanation: 'Identification คือการอ้างตัวตน (Who are you?) และ Authentication คือการตรวจสอบหลักฐานยืนยันตัวตน (Prove it!)',
      order: 17,
    },
    {
      question: 'หลังจากผ่านขั้นตอน Authentication แล้ว ขั้นตอนถัดไปคืออะไรเพื่อกำหนดว่าผู้ใช้ทำอะไรได้บ้าง?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Authorization (การอนุญาตและกำหนดสิทธิ์การเข้าถึง)' },
        { key: 'B', text: 'De-authentication (การตัดการเชื่อมต่อทันที)' },
        { key: 'C', text: 'Data Deletion (การลบข้อมูลทั้งหมด)' },
        { key: 'D', text: 'Re-registration (การลงทะเบียนใหม่)' },
      ],
      correctAnswer: 'A',
      explanation: 'Authorization เป็นขั้นตอนตรวจสอบสิทธิ์ของผู้ใช้ว่ามีอำนาจในการอ่าน เขียน หรือดำเนินการใดๆ บนทรัพยากรนั้นๆ หรือไม่',
      order: 18,
    },
    {
      question: 'เหตุการณ์ Ransomware ล็อคไฟล์ในองค์กรส่งผลกระทบต่อเสาหลักใดใน CIA Triad รุนแรงที่สุด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Availability (ความพร้อมใช้งานของข้อมูลถูกตัดขาด) และอาจรวมถึง Confidentiality หากมีการขู่ปล่อยข้อมูล' },
        { key: 'B', text: 'ไม่มีผลกระทบต่อเสาหลักใดเลย' },
        { key: 'C', text: 'กระทบเฉพาะความเร็วอินเทอร์เน็ตของเครื่องที่ติด' },
        { key: 'D', text: 'กระทบเฉพาะส่วนการพิมพ์เอกสารทางเครื่องพิมพ์' },
      ],
      correctAnswer: 'A',
      explanation: 'Ransomware เข้ารหัสไฟล์ทำให้เจ้าของไม่สามารถเข้าถึงข้อมูลได้ (เสีย Availability) และผู้โจมตียุคใหม่มักขโมยข้อมูลไปขู่ปล่อยด้วย (เสีย Confidentiality)',
      order: 19,
    },
    {
      question: 'ข้อใดคือแนวทางที่ถูกต้องตามกฎหมายและจริยธรรมในการศึกษาด้าน Cyber Security?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ทดสอบเครื่องมือและเทคนิคเฉพาะในระบบจำลอง (Sandbox) หรือระบบที่ได้รับอนุญาตเป็นลายลักษณ์อักษรเท่านั้น' },
        { key: 'B', text: 'ทดลองสแกนและเจาะระบบของโรงพยาบาลเพื่อหาช่องโหว่ช่วยสังคมโดยไม่ต้องบอกใคร' },
        { key: 'C', text: 'นำเครื่องมือทดสอบไปรันใส่เว็บไซต์ของมหาวิทยาลัยเพื่อทดสอบความแรง' },
        { key: 'D', text: 'แชร์ข้อมูลช่องโหว่ของผู้อื่นลงในโซเชียลมีเดียทันทีที่พบเพื่อสร้างชื่อเสียง' },
      ],
      correctAnswer: 'A',
      explanation: 'การทดสอบความปลอดภัยต้องได้รับความยินยอมเป็นลายลักษณ์อักษร (Authorized Scope) เสมอ การเจาะระบบผู้อื่นโดยไม่ได้รับอนุญาตผิดกฎหมายทั้งทางแพ่งและอาญา',
      order: 20,
    },
  ],

  // 2. Threats, Vulnerabilities & Attack Surface
  'lesson-b1-2': [
    {
      question: 'ข้อใดคือคำจำกัดความที่ถูกต้องของ "Attack Surface" (พื้นที่การโจมตี)?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ผลรวมของจุดเชื่อมต่อ, พอร์ต, บริการ, และโค้ดทั้งหมดที่บุคคลภายนอกสามารถส่งข้อมูลเข้าหรือดึงข้อมูลออกจากระบบได้' },
        { key: 'B', text: 'ขนาดหน้าจอของอุปกรณ์คอมพิวเตอร์ที่ใช้งาน' },
        { key: 'C', text: 'พื้นที่ของฮาร์ดดิสก์ที่ใช้ติดตั้งระบบปฏิบัติการ' },
        { key: 'D', text: 'จำนวนโต๊ะทำงานในแผนกไอที' },
      ],
      correctAnswer: 'A',
      explanation: 'Attack Surface คือจุดสัมผัสหรือช่องทางทั้งหมดที่เปิดโอกาสให้ผู้โจมตีสามารถใช้ประโยชน์หรือส่ง Payload เข้าสู่ระบบได้',
      order: 1,
    },
    {
      question: 'มาตรการใดต่อไปนี้ช่วยลด Attack Surface (Attack Surface Reduction - ASR) ได้อย่างมีประสิทธิภาพที่สุด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การปิดพอร์ตและบริการที่ไม่จำเป็น, ลบโปรแกรมที่ไม่ได้ใช้งานออกจากเครื่อง Production' },
        { key: 'B', text: 'การเพิ่มขนาดของแรม (RAM) ให้กับเครื่องเซิร์ฟเวอร์' },
        { key: 'C', text: 'การเปิด Debug Mode ในระบบจริงเพื่อให้ตรวจสอบข้อผิดพลาดได้ง่าย' },
        { key: 'D', text: 'การเปิดพอร์ตทั้งหมดไว้ล่วงหน้าเพื่อความสะดวกในการขยายระบบ' },
      ],
      correctAnswer: 'A',
      explanation: 'การปิดบริการ พอร์ต หรือโมดูลที่ไม่จำเป็น ช่วยกำจัดจุดที่ผู้โจมตีอาจนำมาใช้เป็นช่องทางเจาะระบบ',
      order: 2,
    },
    {
      question: 'คำว่า "CVE" (Common Vulnerabilities and Exposures) มีหน้าที่หลักคืออะไรในวงการไซเบอร์?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ระบบรหัสมาตรฐานสากลสำหรับระบุและอ้างอิงช่องโหว่ความปลอดภัยของซอฟต์แวร์ต่อสาธารณะ' },
        { key: 'B', text: 'โปรแกรม Antivirus ชนิดหนึ่งของรัฐบาลสหรัฐฯ' },
        { key: 'C', text: 'ชื่อของกลุ่มแฮกเกอร์สายมืด' },
        { key: 'D', text: 'ใบรับรองความเร็วของสัญญาณอินเทอร์เน็ต' },
      ],
      correctAnswer: 'A',
      explanation: 'CVE (เช่น CVE-2021-44228) เป็นรหัสสากลที่ใช้ระบุช่องโหว่แต่ละตัว เพื่อให้ผู้พัฒนาและผู้ดูแลระบบสื่อสารและติดตามการแพตช์ได้อย่างแม่นยำ',
      order: 3,
    },
    {
      question: 'ช่องโหว่ประเภท "Zero-Day Vulnerability" มีความหมายว่าอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ช่องโหว่ที่ผู้พัฒนาซอฟต์แวร์ยังไม่ทราบ หรือยังไม่มี Security Patch อย่างเป็นทางการปล่อยออกมาแก้ไข' },
        { key: 'B', text: 'ช่องโหว่ที่เกิดขึ้นในวันที่ 0 ของทุกเดือน' },
        { key: 'C', text: 'ช่องโหว่ที่มีความรุนแรงระดับ 0 ซึ่งไม่มีอันตรายใดๆ' },
        { key: 'D', text: 'ช่องโหว่ที่สามารถแก้ไขได้เสร็จสิ้นภายใน 0 วินาที' },
      ],
      correctAnswer: 'A',
      explanation: 'Zero-Day คือช่องโหว่ที่ยังไม่มีแพตช์จากผู้ผลิต ทำให้ระบบที่ได้รับผลกระทบมีความเสี่ยงสูงมากเนื่องจากยังไม่มีมาตรการอัปเดตอย่างเป็นทางการ',
      order: 4,
    },
    {
      question: 'การโจมตีแบบ "Phishing" จัดอยู่ในประเภทภัยคุกคามรูปแบบใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Social Engineering (วิศวกรรมทางสังคมที่หลอกลวงจิตวิทยาของมนุษย์)' },
        { key: 'B', text: 'Hardware Component Failure' },
        { key: 'C', text: 'Cryptographic Algorithm Cracking' },
        { key: 'D', text: 'Quantum Computing Attack' },
      ],
      correctAnswer: 'A',
      explanation: 'Phishing อาศัยการปลอมแปลงอีเมลหรือเว็บไซต์เพื่อหลอกล่อให้เหยื่อเปิดเผยข้อมูลส่วนบุคคลหรือรหัสผ่าน โดยใช้จุดอ่อนด้านจิตวิทยาของมนุษย์',
      order: 5,
    },
    {
      question: 'การส่งอีเมลปลอมที่เจาะจงเป้าหมายไปยังผู้บริหารระดับสูง (C-Level / Executives) เรียกว่าอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Whaling Attack' },
        { key: 'B', text: 'Port Scanning' },
        { key: 'C', text: 'SYN Flood' },
        { key: 'D', text: 'Buffer Overflow' },
      ],
      correctAnswer: 'A',
      explanation: 'Whaling เป็นรูปแบบเฉพาะของ Spear Phishing ที่มุ่งเป้าไปที่ "ปลาตัวใหญ่" เช่น CEO, CFO หรือผู้มีอำนาจตัดสินใจทางการเงินสูง',
      order: 6,
    },
    {
      question: 'มัลแวร์ประเภทใดที่สามารถ "แพร่กระจายตัวเองข้ามเครือข่าย" ได้โดยอัตโนมัติโดยไม่ต้องอาศัยการกระทำของผู้ใช้งาน?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Worm (หนอนคอมพิวเตอร์)' },
        { key: 'B', text: 'Trojan Horse (ม้าโทรจัน)' },
        { key: 'C', text: 'Adware' },
        { key: 'D', text: 'Macro Virus' },
      ],
      correctAnswer: 'A',
      explanation: 'Worm มีความสามารถในการสแกนหาเครื่องอื่นในเครือข่ายและแพร่กระจายตัวผ่านช่องโหว่ของโปรโตคอลได้เองโดยอัตโนมัติ ต่างจากไวรัสหรือโทรจันที่ต้องอาศัยผู้ใช้เปิดไฟล์',
      order: 7,
    },
    {
      question: 'มัลแวร์ประเภท "Trojan Horse" อาศัยเทคนิคใดในการเข้าสู่ระบบของเหยื่อ?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การปลอมตัวหรือแฝงมากับโปรแกรมที่ดูมีประโยชน์หรือน่าเชื่อถือ เพื่อหลอกให้เหยื่อติดตั้ง' },
        { key: 'B', text: 'การดักฟังสัญญาณวิทยุในอากาศ' },
        { key: 'C', text: 'การยิงเลเซอร์ไปยังฮาร์ดดิสก์' },
        { key: 'D', text: 'การทำให้สายไฟในเครื่องไหม้' },
      ],
      correctAnswer: 'A',
      explanation: 'Trojan หลอกล่อให้ผู้ใช้ดาวน์โหลดและติดตั้งโดยคิดว่าเป็นโปรแกรมดี (เช่น เกม หรือโปรแกรม Utility) แต่แฝงโค้ดอันตรายไว้เบื้องหลัง',
      order: 8,
    },
    {
      question: 'กลุ่มผู้คุกคามประเภท "APT" (Advanced Persistent Threat) มีลักษณะเด่นอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'กลุ่มผู้โจมตีระดับสูงที่มีเงินทุนและทรัพยากรหนุนหลัง มุ่งแฝงตัวในระบบเป้าหมายระยะยาวเพื่อจารกรรมข้อมูล' },
        { key: 'B', text: 'เด็กวัยรุ่นที่เพิ่งหัดเขียนโปรแกรมและชอบยิงเว็บเล่น' },
        { key: 'C', text: 'บอทสแปมอีเมลทั่วไปที่สุ่มส่งข้อความหาคน' },
        { key: 'D', text: 'โปรแกรม Antivirus ที่ทำงานช้าเกินไป' },
      ],
      correctAnswer: 'A',
      explanation: 'APT มักได้รับการสนับสนุนจากรัฐบาลหรือองค์กรขนาดใหญ่ มีเป้าหมายทางยุทธศาสตร์และแฝงตัวอยู่ในเครือข่ายเป้าหมายอย่างแนบเนียนเป็นเวลานาน',
      order: 9,
    },
    {
      question: 'มัลแวร์ประเภท "Rootkit" มีคุณสมบัติพิเศษด้านใดที่ทำให้ตรวจจับได้ยาก?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การฝังตัวในระดับ Kernel หรือระบบปฏิบัติการส่วนลึก และสามารถซ่อนไฟล์/โปรเซสของตนจากการตรวจสอบทั่วไปได้' },
        { key: 'B', text: 'การทำให้หน้าจอคอมพิวเตอร์เปลี่ยนเป็นสีแดงสด' },
        { key: 'C', text: 'การส่งเสียงเตือนดังออกมาจากลำโพงตลอดเวลา' },
        { key: 'D', text: 'การลบไฟล์ภาพพื้นหลังของ Desktop' },
      ],
      correctAnswer: 'A',
      explanation: 'Rootkit ดัดแปลงการทำงานของ Kernel ทำให้คำสั่งตรวจสอบระดับผู้ใช้ (เช่น ps, ls, Task Manager) มองไม่เห็นโปรเซสหรือไฟล์ของมัลแวร์',
      order: 10,
    },
    {
      question: 'การทำ "Vulnerability Assessment" (การประเมินช่องโหว่) แตกต่างจาก "Penetration Testing" (การทดสอบเจาะระบบ) อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Vulnerability Assessment เน้นการสแกนระบุรายการช่องโหว่ทั้งหมด ส่วน Penetration Testing เน้นการทดสอบเจาะจริงเพื่อพิสูจน์ผลกระทบ' },
        { key: 'B', text: 'Vulnerability Assessment ต้องใช้แฮกเกอร์หมวดดำเท่านั้น' },
        { key: 'C', text: 'Penetration Testing ทำเฉพาะกับอุปกรณ์มือถือเท่านั้น' },
        { key: 'D', text: 'ทั้งสองอย่างไม่มีความแตกต่างกันเลย' },
      ],
      correctAnswer: 'A',
      explanation: 'Vulnerability Assessment คือการสำรวจหาช่องโหว่ในวงกว้าง ส่วน Penetration Testing คือการจำลองการโจมตีจริงเพื่อดูว่าเจาะลึกเข้าไปได้แค่ไหนและสร้างความเสียหายได้เพียงใด',
      order: 11,
    },
    {
      question: 'ฐานข้อมูล "NVD" (National Vulnerability Database) จัดทำและดูแลโดยหน่วยงานใดของสหรัฐฯ?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'NIST (National Institute of Standards and Technology)' },
        { key: 'B', text: 'NASA' },
        { key: 'C', text: 'FBI' },
        { key: 'D', text: 'Federal Reserve' },
      ],
      correctAnswer: 'A',
      explanation: 'NVD ได้รับการดูแลโดยสถาบัน NIST เพื่อวิเคราะห์และกำหนดคะแนนความรุนแรง CVSS ให้กับช่องโหว่ CVE ต่างๆ ทั่วโลก',
      order: 12,
    },
    {
      question: 'การโจมตีแบบ "Supply Chain Attack" คืออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การโจมตีผ่านบุคคลที่สาม (Third-party vendor) หรือแทรกโค้ดอันตรายลงในไลบรารี/อัปเดตของซอฟต์แวร์ต้นทาง' },
        { key: 'B', text: 'การปล้นรถบรรทุกส่งสินค้าคอมพิวเตอร์' },
        { key: 'C', text: 'การตัดสายเคเบิลอินเทอร์เน็ตใต้ทะเล' },
        { key: 'D', text: 'การแย่งซื้อการ์ดจอในตลาด' },
      ],
      correctAnswer: 'A',
      explanation: 'Supply Chain Attack มุ่งโจมตีผู้ผลิตหรือผู้ให้บริการซอฟต์แวร์ต้นน้ำ เพื่อให้มัลแวร์แพร่กระจายไปยังลูกค้าทั้งหมดของบริษัทนั้นโดยอัตโนมัติ (เช่น กรณี SolarWinds)',
      order: 13,
    },
    {
      question: 'การแยกส่วนเครือข่าย (Network Segmentation) ช่วยลดผลกระทบของการบุกรุกได้อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ช่วยจำกัดขอบเขตการแพร่ระบาด (Lateral Movement) ไม่ให้ผู้โจมตีที่ยึดเครื่องหนึ่งสามารถเข้าถึงโซนข้อมูลสำคัญอื่นได้ง่าย' },
        { key: 'B', text: 'ช่วยเพิ่มความเร็วในการเชื่อมต่อ Wi-Fi' },
        { key: 'C', text: 'ทำให้ไม่ต้องตั้งรหัสผ่านสำหรับเครื่องในเครือข่าย' },
        { key: 'D', text: 'ทำให้ไม่จำเป็นต้องติดตั้ง Antivirus อีกต่อไป' },
      ],
      correctAnswer: 'A',
      explanation: 'Network Segmentation ใช้ Firewall หรือ VLANs กั้นระหว่างโซน ทำให้เมื่อเครื่องในโซนหนึ่งถูกยึด ผู้โจมตีจะไม่สามารถข้ามไปยังโซนอื่นที่มีความสำคัญสูงกว่าได้โดยตรง',
      order: 14,
    },
    {
      question: 'ข้อใดคือตัวอย่างของ "Patch Management" (การจัดการแพตช์ความปลอดภัย) ที่ดีในองค์กร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การทดสอบแพตช์ในระบบ Staging ก่อน แล้วจึงทยอยติดตั้งบนระบบ Production อย่างสม่ำเสมอตามวงรอบ' },
        { key: 'B', text: 'การปิดระบบอัปเดตทั้งหมดอย่างถาวรเพื่อป้องกันโปรแกรมรวน' },
        { key: 'C', text: 'การรอให้ระบบถูกแฮกก่อนแล้วจึงค่อยค้นหาแพตช์มาติดตั้ง' },
        { key: 'D', text: 'การติดตั้งแพตช์เฉพาะเมื่อเซิร์ฟเวอร์มีอายุการใช้งานครบ 10 ปี' },
      ],
      correctAnswer: 'A',
      explanation: 'การบริหารจัดการแพตช์ที่ดีต้องมีการทดสอบความเข้ากันได้ในระบบทดสอบก่อนนำขึ้นใช้งานจริง และต้องทำอย่างรวดเร็วสำหรับช่องโหว่ระดับวิกฤต',
      order: 15,
    },
    {
      question: 'โปรแกรมประเภท "Keylogger" มีพฤติกรรมการทำงานที่เป็นอันตรายอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'แอบบันทึกทุกปุ่มที่ผู้ใช้พิมพ์บนคีย์บอร์ด (เช่น รหัสผ่าน, หมายเลขบัตรเครดิต) แล้วส่งกลับไปยังผู้โจมตี' },
        { key: 'B', text: 'ทำให้ปุ่มคีย์บอร์ดกดไม่ติด' },
        { key: 'C', text: 'เปลี่ยนภาษาของคีย์บอร์ดเป็นภาษาต่างดาว' },
        { key: 'D', text: 'ทำลายแผงวงจรของคีย์บอร์ดให้เสียหายทางกายภาพ' },
      ],
      correctAnswer: 'A',
      explanation: 'Keylogger ดักจับการกดแป้นพิมพ์เพื่อขโมยข้อมูลสำคัญ เช่น ข้อมูลการเข้าสู่ระบบ ข้อความแชท หรือข้อมูลทางการเงิน',
      order: 16,
    },
    {
      question: 'ข้อใดคือสัญญาณเตือนที่ชัดเจนที่สุดของการถูกโจมตีแบบ "Ransomware"?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ไฟล์เอกสารและข้อมูลสำคัญถูกเปลี่ยนนามสกุล ไม่สามารถเปิดอ่านได้ และมีไฟล์ข้อความเรียกค่าไถ่ปรากฏขึ้น' },
        { key: 'B', text: 'เครื่องคอมพิวเตอร์ทำงานเร็วขึ้นผิดปกติ' },
        { key: 'C', text: 'มีเสียงเพลงบรรเลงเปิดขึ้นอัตโนมัติ' },
        { key: 'D', text: 'ขนาดหน้าต่างโปรแกรมเล็กลงครึ่งหนึ่ง' },
      ],
      correctAnswer: 'A',
      explanation: 'Ransomware จะทำการเข้ารหัสไฟล์ข้อมูลของเหยื่อ และทิ้งข้อความอธิบายวิธีการจ่ายค่าไถ่เพื่อแลกกับกุญแจถอดรหัส',
      order: 17,
    },
    {
      question: 'การใช้ "Default Credentials" (ชื่อผู้ใช้และรหัสผ่านเริ่มต้นจากโรงงาน เช่น admin/admin) มีความเสี่ยงอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ผู้โจมตีสามารถใช้สคริปต์สแกนและล็อกอินเข้าควบคุมอุปกรณ์ได้ทันทีโดยไม่ต้องใช้เครื่องมือเจาะระบบชั้นสูง' },
        { key: 'B', text: 'ทำให้อุปกรณ์กินกระแสไฟฟ้ามากขึ้น' },
        { key: 'C', text: 'ทำให้อุปกรณ์ไม่สามารถเชื่อมต่อสัญญาณ Wi-Fi ได้' },
        { key: 'D', text: 'ทำให้ปุ่ม Power ของอุปกรณ์ใช้งานไม่ได้' },
      ],
      correctAnswer: 'A',
      explanation: 'รหัสผ่านเริ่มต้นเป็นข้อมูลสาธารณะที่ถูกบันทึกอยู่ในคู่มือ บอทเน็ตและผู้ไม่ประสงค์ดีสามารถสแกนและเข้ายึดอุปกรณ์ได้ภายในไม่กี่วินาที',
      order: 18,
    },
    {
      question: 'กลยุทธ์ "Least Functionality" มีหลักการทำงานสอดคล้องกับข้อใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การกำหนดค่าระบบให้มีเฉพาะฟังก์ชันและโปรแกรมที่จำเป็นต่อภารกิจหลักเท่านั้น เพื่อลดโอกาสเกิดช่องโหว่' },
        { key: 'B', text: 'การลดความเร็วของ CPU ลงเพื่อประหยัดพลังงาน' },
        { key: 'C', text: 'การลดจำนวนพนักงานในบริษัทให้น้อยที่สุด' },
        { key: 'D', text: 'การเขียนโค้ดโดยไม่ใส่ Comment' },
      ],
      correctAnswer: 'A',
      explanation: 'Least Functionality คือการตัดฟังก์ชัน เครื่องมือ คอมไพเลอร์ หรือบริการที่ไม่จำเป็นออก เพื่อไม่ให้กลายเป็นเครื่องมือช่วยผู้โจมตี',
      order: 19,
    },
    {
      question: 'เหตุใดการติดตั้ง "Security Headers" บนเว็บเซิร์ฟเวอร์จึงช่วยลด Attack Surface ของเว็บแอปพลิเคชันได้?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เพราะเป็นการสั่งให้เบราว์เซอร์ของเหยื่อเปิดใช้กลไกป้องกันในตัว เช่น บล็อกการรันสคริปต์แปลกปลอม หรือป้องกันการฝัง iframe' },
        { key: 'B', text: 'เพราะทำให้หน้าเว็บโหลดเร็วขึ้น 10 เท่า' },
        { key: 'C', text: 'เพราะสามารถแทนที่ระบบฐานข้อมูลได้ทั้งหมด' },
        { key: 'D', text: 'เพราะทำให้ไม่ต้องเขียนโค้ดยืนยันตัวตน' },
      ],
      correctAnswer: 'A',
      explanation: 'Security Headers (เช่น CSP, HSTS, X-Frame-Options) สั่งการให้ Web Browser บังคับใช้นโยบายความปลอดภัยเพื่อสกัดกั้นการโจมตีหลายรูปแบบ',
      order: 20,
    },
  ],

  // 3. TCP/IP & OSI
  'lesson-b2-1': [
    {
      question: 'โมเดล OSI Model ประกอบไปด้วยกี่ชั้น (Layers) และชั้นล่างสุด (Layer 1) คือชั้นใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '7 ชั้น โดยมี Physical Layer เป็น Layer 1' },
        { key: 'B', text: '4 ชั้น โดยมี Network Layer เป็น Layer 1' },
        { key: 'C', text: '5 ชั้น โดยมี Transport Layer เป็น Layer 1' },
        { key: 'D', text: '7 ชั้น โดยมี Application Layer เป็น Layer 1' },
      ],
      correctAnswer: 'A',
      explanation: 'OSI Model มี 7 ชั้น เรียงจากล่างขึ้นบน: 1. Physical, 2. Data Link, 3. Network, 4. Transport, 5. Session, 6. Presentation, 7. Application',
      order: 1,
    },
    {
      question: 'โปรโตคอล IP (Internet Protocol) ทำงานอยู่ในชั้น (Layer) ใดของ OSI Model?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Network Layer (Layer 3)' },
        { key: 'B', text: 'Transport Layer (Layer 4)' },
        { key: 'C', text: 'Data Link Layer (Layer 2)' },
        { key: 'D', text: 'Application Layer (Layer 7)' },
      ],
      correctAnswer: 'A',
      explanation: 'IP และ ICMP ทำงานอยู่ที่ Network Layer (Layer 3) ทำหน้าที่กำหนดที่อยู่ Logical Address และหาเส้นทางส่งข้อมูล (Routing)',
      order: 2,
    },
    {
      question: 'กระบวนการเชื่อมต่อแบบ TCP 3-Way Handshake มีลำดับขั้นตอนการส่ง Flag อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'SYN -> SYN-ACK -> ACK' },
        { key: 'B', text: 'ACK -> SYN -> FIN' },
        { key: 'C', text: 'SYN -> ACK -> RST' },
        { key: 'D', text: 'HELO -> PING -> PONG' },
      ],
      correctAnswer: 'A',
      explanation: 'Client ส่ง SYN -> Server ตอบ SYN-ACK -> Client ยืนยันด้วย ACK จึงถือว่าการเชื่อมต่อ TCP สมบูรณ์พร้อมส่งข้อมูล',
      order: 3,
    },
    {
      question: 'ข้อใดคือข้อแตกต่างสำคัญระหว่าง TCP และ UDP?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'TCP เป็น Connection-oriented มีการยืนยันส่งข้อมูลครบถ้วน ส่วน UDP เป็น Connectionless รวดเร็วแต่ไม่การันตีการส่งถึง' },
        { key: 'B', text: 'TCP ใช้ได้เฉพาะสายเคเบิล ส่วน UDP ใช้ได้เฉพาะ Wi-Fi' },
        { key: 'C', text: 'UDP มีการเข้ารหัสในตัว ส่วน TCP ไม่มี' },
        { key: 'D', text: 'TCP ทำงานเฉพาะบนมือถือ ส่วน UDP ทำงานบน PC' },
      ],
      correctAnswer: 'A',
      explanation: 'TCP เน้นความถูกต้องสมบูรณ์ (Reliability & Ordering) ส่วน UDP เน้นความเร็วและ Latency ต่ำ (เช่น Video Streaming, DNS, Gaming)',
      order: 4,
    },
    {
      question: 'การโจมตีแบบ "SYN Flood Attack" อาศัยช่องว่างของกระบวนการใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ส่งแพ็กเกจ TCP SYN จำนวนมากโดยไม่ส่ง ACK สุดท้ายกลับไป เพื่อทำให้ Backlog Queue ของเซิร์ฟเวอร์เต็ม' },
        { key: 'B', text: 'การปลอมแปลงชื่อโดเมน DNS' },
        { key: 'C', text: 'การส่งรูปภาพขนาดใหญ่ทางอีเมล' },
        { key: 'D', text: 'การตัดไฟที่ตัวเร้าเตอร์' },
      ],
      correctAnswer: 'A',
      explanation: 'SYN Flood ทำให้เซิร์ฟเวอร์ต้องรอ Connection State แบบ Half-Open จนทรัพยากรหน่วยความจำของเซิร์ฟเวอร์เต็มและไม่สามารถรับผู้ใช้ใหม่ได้',
      order: 5,
    },
    {
      question: 'Flag "RST" (Reset) ใน TCP Packet มีหน้าที่อะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'แจ้งยกเลิกและตัดการเชื่อมต่อทันทีเมื่อเกิดข้อผิดพลาดหรือเมื่อพอร์ตเป้าหมายปิดอยู่' },
        { key: 'B', text: 'แจ้งขอเริ่มการเชื่อมต่อใหม่ตั้งแต่แรก' },
        { key: 'C', text: 'แจ้งยืนยันว่าได้รับข้อมูลครบถ้วน' },
        { key: 'D', text: 'แจ้งให้เซิร์ฟเวอร์รีบูตเครื่อง' },
      ],
      correctAnswer: 'A',
      explanation: 'RST ใช้เพื่อปฏิเสธการเชื่อมต่อหรือตัดการเชื่อมต่อทันทีโดยไม่ต้องผ่านกระบวนการ 4-way FIN teardown',
      order: 6,
    },
    {
      question: 'อุปกรณ์ "Switch" ทั่วไปทำงานอยู่ที่ชั้น (Layer) ใดของ OSI Model และใช้ที่อยู่ชนิดใดในการส่งต่อข้อมูล?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Data Link Layer (Layer 2) โดยใช้ MAC Address' },
        { key: 'B', text: 'Network Layer (Layer 3) โดยใช้ IP Address' },
        { key: 'C', text: 'Transport Layer (Layer 4) โดยใช้ Port Number' },
        { key: 'D', text: 'Physical Layer (Layer 1) โดยใช้แรงดันไฟฟ้า' },
      ],
      correctAnswer: 'A',
      explanation: 'Layer 2 Switch สวิตช์เฟรมข้อมูลภายใน LAN เดียวกันโดยอิงตามตาราง MAC Address Table (CAM Table)',
      order: 7,
    },
    {
      question: 'การแปลงข้อมูลจากชั้นบนลงสู่ชั้นล่างโดยการเพิ่ม Header ในแต่ละ Layer เรียกว่ากระบวนการอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Encapsulation' },
        { key: 'B', text: 'Decapsulation' },
        { key: 'C', text: 'De-serialization' },
        { key: 'D', text: 'Compilation' },
      ],
      correctAnswer: 'A',
      explanation: 'Encapsulation คือการห่อหุ้มข้อมูลโดยเพิ่ม Header เฉพาะของแต่ละชั้น (Data -> Segment -> Packet -> Frame -> Bits)',
      order: 8,
    },
    {
      question: 'โปรโตคอล ICMP (Internet Control Message Protocol) ถูกนำมาใช้งานในเครื่องมือใดบ่อยที่สุด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ping และ traceroute' },
        { key: 'B', text: 'SSH และ Telnet' },
        { key: 'C', text: 'FTP และ SFTP' },
        { key: 'D', text: 'MySQL และ PostgreSQL' },
      ],
      correctAnswer: 'A',
      explanation: 'ping ใช้ ICMP Echo Request/Reply เพื่อทดสอบความพร้อมในการติดต่อ และ traceroute ใช้ ICMP Time Exceeded เพื่อหาเส้นทาง Hop',
      order: 9,
    },
    {
      question: 'การโจมตี "ARP Spoofing / Poisoning" อาศัยช่องโหว่ที่เกิดขึ้นใน Layer ใดของ OSI Model?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Data Link Layer (Layer 2)' },
        { key: 'B', text: 'Application Layer (Layer 7)' },
        { key: 'C', text: 'Presentation Layer (Layer 6)' },
        { key: 'D', text: 'Session Layer (Layer 5)' },
      ],
      correctAnswer: 'A',
      explanation: 'ARP Spoofing เกิดจากการส่งแพ็กเกจ ARP Reply ปลอมในเครือข่ายท้องถิ่น (L2) เพื่อผูก IP ของ Gateway เข้ากับ MAC Address ของผู้โจมตี (ทำ Man-in-the-Middle)',
      order: 10,
    },
    {
      question: 'ขนาด MTU (Maximum Transmission Unit) มาตรฐานสำหรับ Ethernet มีขนาดกี่ไบต์?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '1500 ไบต์' },
        { key: 'B', text: '64 ไบต์' },
        { key: 'C', text: '9000 ไบต์' },
        { key: 'D', text: '65535 ไบต์' },
      ],
      correctAnswer: 'A',
      explanation: 'Standard Ethernet MTU คือ 1,500 Bytes หากแพ็กเกจมีขนาดใหญ่กว่านี้และไม่ตั้ง Flag Don\'t Fragment (DF) จะเกิดการ Fragment',
      order: 11,
    },
    {
      question: 'เมื่อผู้ใช้งานพิมพ์ข้อความผ่านโปรแกรมเว็บเบราว์เซอร์ การเข้ารหัส TLS ทำงานอยู่ที่ชั้นใดในเชิงแนวคิด OSI Model?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Presentation Layer (Layer 6) / Transport Layer (Layer 4)' },
        { key: 'B', text: 'Physical Layer (Layer 1)' },
        { key: 'C', text: 'Data Link Layer (Layer 2)' },
        { key: 'D', text: 'Network Layer (Layer 3)' },
      ],
      correctAnswer: 'A',
      explanation: 'TLS ทำหน้าที่เข้ารหัสและแปลงฟอร์แมตข้อมูล ซึ่งตรงกับ Presentation Layer (Layer 6) บน OSI Model ก่อนจะส่งต่อให้ TCP (Layer 4)',
      order: 12,
    },
    {
      question: 'โปรโตคอลใดทำงานบน UDP และมักถูกนำมาใช้ทำการโจมตีแบบ Amplification Attack ได้เนื่องจากไม่มีการตรวจสอบ Handshake?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'DNS, NTP, และ SNMP' },
        { key: 'B', text: 'SSH และ HTTPS' },
        { key: 'C', text: 'BGP และ OSPF' },
        { key: 'D', text: 'FTP และ Telnet' },
      ],
      correctAnswer: 'A',
      explanation: 'UDP โปรโตคอลเช่น DNS/NTP สามารถส่งคำขอสั้นๆ ด้วย IP ปลอมของเหยื่อ แล้วทำให้เซิร์ฟเวอร์ส่งคำตอบขนาดใหญ่กลับไปยังเหยื่อ (Amplification)',
      order: 13,
    },
    {
      question: 'หมายเลข IP Address `127.0.0.1` และ `::1` ถูกกำหนดให้ทำหน้าที่อะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Loopback Address (ชี้กลับมาที่ตัวเครื่องตัวเอง)' },
        { key: 'B', text: 'Default Gateway ประจำเราเตอร์' },
        { key: 'C', text: 'Public IP ของ Google DNS' },
        { key: 'D', text: 'Broadcast IP ของทุกเครือข่าย' },
      ],
      correctAnswer: 'A',
      explanation: '127.0.0.1 (IPv4) และ ::1 (IPv6) คือ Loopback Adapter เพื่อทดสอบและเชื่อมต่อบริการภายในเครื่องตัวเองโดยไม่ต้องส่งข้อมูลออกสายแลน',
      order: 14,
    },
    {
      question: 'ช่วง IP ใดต่อไปนี้ถูกสงวนไว้เป็น Private IP Address ตามมาตรฐาน RFC 1918?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '10.0.0.0/8, 172.16.0.0/12, และ 192.168.0.0/16' },
        { key: 'B', text: '8.8.8.0/24 และ 1.1.1.0/24' },
        { key: 'C', text: '200.0.0.0/8 และ 150.0.0.0/8' },
        { key: 'D', text: '100.64.0.0/10 เท่านั้น' },
      ],
      correctAnswer: 'A',
      explanation: 'RFC 1918 กำหนดช่วง Private IP สำหรับใช้ภายในองค์กร ไม่สามารถ Route บนอินเทอร์เน็ตสาธารณะได้โดยตรง',
      order: 15,
    },
    {
      question: 'กลไก NAT (Network Address Translation) มีบทบาทหลักอย่างไรในการเชื่อมต่ออินเทอร์เน็ต?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'แปลง Private IP หลายเครื่องในวง LAN ให้แชร์ใช้งาน Public IP ร่วมกันในการออกสู่อินเทอร์เน็ต' },
        { key: 'B', text: 'เพิ่มความเร็วสัญญาณไฟเบอร์ออปติก' },
        { key: 'C', text: 'ทำการสำรองข้อมูลอัตโนมัติ' },
        { key: 'D', text: 'ลบมัลแวร์ในฮาร์ดดิสก์' },
      ],
      correctAnswer: 'A',
      explanation: 'NAT ช่วยประหยัด IPv4 Public Address โดยให้เครื่องนับร้อยในวงแลนออกเน็ตผ่าน Public IP เดียวกันโดยใช้ Port Mapping (PAT)',
      order: 16,
    },
    {
      question: 'พอร์ต 0 ถึง 1023 ในระบบเครือข่ายถูกจัดอยู่ในกลุ่มใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Well-Known Ports (พอร์ตมาตรฐานสำหรับบริการระบบ)' },
        { key: 'B', text: 'Registered Ports' },
        { key: 'C', text: 'Dynamic / Ephemeral Ports' },
        { key: 'D', text: 'Blocked Ports' },
      ],
      correctAnswer: 'A',
      explanation: '0-1023 คือ Well-Known Ports สงวนไว้สำหรับบริการสำคัญ (เช่น 80 HTTP, 443 HTTPS, 22 SSH) และบนระบบ Unix ต้องใช้สิทธิ์ root ในการ bind',
      order: 17,
    },
    {
      question: 'TCP Window Size ใน Header มีบทบาทสำคัญในการทำหน้าที่อะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Flow Control (ควบคุมปริมาณข้อมูลที่ส่งเพื่อไม่ให้ฝั่งรับประมวลผลไม่ทัน)' },
        { key: 'B', text: 'กำหนดความกว้างหน้าจอของเบราว์เซอร์' },
        { key: 'C', text: 'ตั้งเวลาเปิดปิดหน้าต่างโปรแกรม' },
        { key: 'D', text: 'กำหนดสีของสายแลน' },
      ],
      correctAnswer: 'A',
      explanation: 'Flow Control ใช้ Window Size เพื่อบอกฝั่งส่งว่าฝั่งรับยังมี Buffer ว่างรับข้อมูลได้อีกกี่ไบต์ ป้องกันไม่ให้เกิด Buffer Overflow ขาเข้า',
      order: 18,
    },
    {
      question: 'การตรวจจับแพ็กเกจด้วย Wireshark / tcpdump เป็นการวิเคราะห์ข้อมูลในระดับใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Packet Inspection (ตรวจสอบเนื้อหา Header และ Payload ของแพ็กเกจแบบไบต์ต่อไบต์)' },
        { key: 'B', text: 'การตรวจสอบทางกายภาพของสายไฟ' },
        { key: 'C', text: 'การจำลองแบบ 3D Animation' },
        { key: 'D', text: 'การวัดอุณหภูมิห้องเซิร์ฟเวอร์' },
      ],
      correctAnswer: 'A',
      explanation: 'Packet Analyzer ดักจับและแกะโครงสร้าง Header ของโปรโตคอลทุกระดับตั้งแต่ L2 ถึง L7 เพื่อการวิเคราะห์ความปลอดภัยและการแก้ปัญหา',
      order: 19,
    },
    {
      question: 'โปรโตคอลใดใช้กระบวนการ 4-Way Handshake ในการจบการเชื่อมต่ออย่างสง่างาม?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'TCP (FIN -> ACK -> FIN -> ACK)' },
        { key: 'B', text: 'UDP' },
        { key: 'C', text: 'ICMP' },
        { key: 'D', text: 'ARP' },
      ],
      correctAnswer: 'A',
      explanation: 'TCP สิ้นสุดการเชื่อมต่อด้วยการส่ง FIN และ ACK ตอบกลับทั้งสองทิศทาง (4 ขั้นตอน) เพื่อให้ทั้งสองฝ่ายมั่นใจว่าข้อมูลถูกส่งหมดแล้ว',
      order: 20,
    },
  ],

  // 4. DNS, DHCP, Ports & HTTPS
  'lesson-b2-2': [
    {
      question: 'พอร์ตมาตรฐานสำหรับการเชื่อมต่อ Secure Shell (SSH) และ HTTPS คือหมายเลขใดตามลำดับ?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'พอร์ต 22 สำหรับ SSH และพอร์ต 443 สำหรับ HTTPS' },
        { key: 'B', text: 'พอร์ต 80 สำหรับ SSH และพอร์ต 21 สำหรับ HTTPS' },
        { key: 'C', text: 'พอร์ต 25 สำหรับ SSH และพอร์ต 53 สำหรับ HTTPS' },
        { key: 'D', text: 'พอร์ต 3306 สำหรับ SSH และพอร์ต 5432 สำหรับ HTTPS' },
      ],
      correctAnswer: 'A',
      explanation: 'SSH ใช้พอร์ต 22 (TCP) ในการจัดการเซิร์ฟเวอร์แบบเข้ารหัส และ HTTPS ใช้พอร์ต 443 (TCP) สำหรับเว็บความปลอดภัยสูง',
      order: 1,
    },
    {
      question: 'DNS Record ประเภทใดที่ใช้จับคู่ชื่อโดเมนเข้ากับหมายเลข IPv4 Address?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'A Record' },
        { key: 'B', text: 'AAAA Record' },
        { key: 'C', text: 'MX Record' },
        { key: 'D', text: 'CNAME Record' },
      ],
      correctAnswer: 'A',
      explanation: 'A Record (Address Record) ใช้แปลงชื่อโฮสต์เป็น IPv4 (ส่วน AAAA Record ใช้สำหรับ IPv6)',
      order: 2,
    },
    {
      question: 'DNS Record ชนิดใดใช้สำหรับระบุ Mail Server ที่ทำหน้าที่รับอีเมลของโดเมน?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'MX Record (Mail Exchange)' },
        { key: 'B', text: 'TXT Record' },
        { key: 'C', text: 'PTR Record' },
        { key: 'D', text: 'NS Record' },
      ],
      correctAnswer: 'A',
      explanation: 'MX Record กำหนดรายชื่อเมลเซิร์ฟเวอร์และลำดับความสำคัญ (Priority) ในการรับส่งอีเมลของโดเมนนั้น',
      order: 3,
    },
    {
      question: 'การโจมตีแบบ "DNS Cache Poisoning / Spoofing" มีผลลัพธ์ที่เป็นอันตรายอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'หลอกให้ DNS Resolver จดจำ IP ปลอม ทำให้ผู้ใช้งานถูกส่งต่อไปยังเว็บไซต์ฟิชชิ่งของผู้โจมตี' },
        { key: 'B', text: 'ทำให้เครื่องดับทันที' },
        { key: 'C', text: 'ลบไฟล์ทั้งหมดในเครื่องผู้ใช้' },
        { key: 'D', text: 'เปลี่ยนสีหน้าจอเบราว์เซอร์' },
      ],
      correctAnswer: 'A',
      explanation: 'DNS Poisoning แทรกล่อคำตอบ DNS ปลอมเข้าสู่แคช ทำให้เมื่อผู้ใช้พิมพ์ชื่อเว็บธนาคาร จะถูกส่งไปยังเซิร์ฟเวอร์ปลอมของผู้โจมตี',
      order: 4,
    },
    {
      question: 'เทคโนโลยีใดที่ช่วยเพิ่มลายเซ็นดิจิทัลให้กับระเบียน DNS เพื่อป้องกันการปลอมแปลงคำตอบ?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'DNSSEC (Domain Name System Security Extensions)' },
        { key: 'B', text: 'DHCP Snooping' },
        { key: 'C', text: 'NAT overload' },
        { key: 'D', text: 'VLAN Tagging' },
      ],
      correctAnswer: 'A',
      explanation: 'DNSSEC ใช้ Public Key Cryptography ลงลายเซ็นกำกับ DNS Records เพื่อให้ Resolver ตรวจสอบความถูกต้องและแหล่งที่มาได้',
      order: 5,
    },
    {
      question: 'กระบวนการรับแจก IP Address ผ่าน DHCP มี 4 ขั้นตอน (DORA Process) เรียงตามลำดับอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Discover -> Offer -> Request -> Acknowledge' },
        { key: 'B', text: 'Download -> Open -> Read -> Accept' },
        { key: 'C', text: 'Detect -> Order -> Receive -> Authenticate' },
        { key: 'D', text: 'Disconnect -> Offline -> Reboot -> Apply' },
      ],
      correctAnswer: 'A',
      explanation: 'DORA: Client ส่ง Discover (หาเซิร์ฟเวอร์) -> Server เสนอ Offer -> Client ขอ Request -> Server ยืนยันสิทธิ์ Acknowledge',
      order: 6,
    },
    {
      question: 'การโจมตี "Rogue DHCP Server" สามารถสร้างความเสียหายต่อเครือข่ายได้อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'แจก Gateway และ DNS ปลอมให้แก่เครื่องลูกข่าย เพื่อดักฟังหรือดัดแปลงทราฟฟิกทั้งหมดในวงแลน' },
        { key: 'B', text: 'ทำให้อุปกรณ์ฮาร์ดดิสก์เกิดความร้อนสูง' },
        { key: 'C', text: 'ลบรหัสผ่าน BIOS ของคอมพิวเตอร์' },
        { key: 'D', text: 'ทำให้ความละเอียดหน้าจอลดลง' },
      ],
      correctAnswer: 'A',
      explanation: 'Rogue DHCP แจกค่า Default Gateway ปลอมชี้มาที่เครื่องผู้โจมตี ทำให้ทราฟฟิกทั้งหมดของเหยื่อวิ่งผ่านเครื่องผู้โจมตี (MITM)',
      order: 7,
    },
    {
      question: 'ฟีเจอร์ใดบน Managed Switch ที่ช่วยป้องกันการปล่อย DHCP ปลอมในเครือข่าย?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'DHCP Snooping (กำหนด Trusted Port เฉพาะพอร์ตที่ต่อกับ DHCP Server จริง)' },
        { key: 'B', text: 'Spanning Tree Protocol' },
        { key: 'C', text: 'Link Aggregation' },
        { key: 'D', text: 'Jumbo Frames' },
      ],
      correctAnswer: 'A',
      explanation: 'DHCP Snooping จะบล็อกแพ็กเกจ DHCP Offer จาก Untrusted Ports ทั้งหมด ป้องกัน Rogue DHCP ได้อย่างเด็ดขาด',
      order: 8,
    },
    {
      question: 'ในการเชื่อมต่อ HTTPS ใบรับรองความปลอดภัยดิจิทัล (SSL/TLS Certificate) ต้องได้รับการลงนามจากหน่วยงานใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Certificate Authority (CA ที่ได้รับความไว้วางใจ)' },
        { key: 'B', text: 'ผู้ให้บริการอินเทอร์เน็ตท้องถิ่น' },
        { key: 'C', text: 'ร้านค้าขายคอมพิวเตอร์' },
        { key: 'D', text: 'ผู้ผลิตการ์ดจอ' },
      ],
      correctAnswer: 'A',
      explanation: 'CA ที่น่าเชื่อถือ (เช่น DigiCert, Let\'s Encrypt) ทำหน้าที่เป็นคนกลางตรวจสอบและออกใบรับรองยืนยันความเป็นเจ้าของโดเมน',
      order: 9,
    },
    {
      question: 'ในกระบวนการ TLS 1.3 Handshake ข้อใดคือการปรับปรุงสำคัญเมื่อเทียบกับ TLS 1.2?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ลดเวลา Handshake เหลือเพียง 1-RTT (หรือ 0-RTT ในการเชื่อมต่อซ้ำ) และยกเลิก Cipher Suites ที่ล้าสมัย' },
        { key: 'B', text: 'ยกเลิกการใช้การเข้ารหัสทั้งหมดเพื่อความเร็ว' },
        { key: 'C', text: 'เปลี่ยนไปใช้สายเชื่อมต่อเฉพาะแบบขนาน' },
        { key: 'D', text: 'บังคับให้พิมพ์รหัสผ่านใหม่ทุกครั้งที่เปิดเว็บ' },
      ],
      correctAnswer: 'A',
      explanation: 'TLS 1.3 ตัดอัลกอริทึมเก่าที่มีช่องโหว่ทิ้งไป (เช่น RSA key exchange, RC4) และเร่งความเร็วการเริ่มเซสชันให้เหลือเพียง 1 Round Trip',
      order: 10,
    },
    {
      question: 'Header ข้อใดที่สั่งให้เบราว์เซอร์บังคับใช้ HTTPS เสมอและป้องกันการถูก Downgrade เป็น HTTP?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Strict-Transport-Security (HSTS)' },
        { key: 'B', text: 'X-Forwarded-For' },
        { key: 'C', text: 'User-Agent' },
        { key: 'D', text: 'Accept-Encoding' },
      ],
      correctAnswer: 'A',
      explanation: 'HSTS สั่งให้เบราว์เซอร์เปลี่ยนคำขอจาก http:// เป็น https:// อัตโนมัติ ป้องกันการโจมตีแบบ SSL Stripping',
      order: 11,
    },
    {
      question: 'พอร์ต 53 ถูกใช้โดยโปรโตคอลใด และมักใช้โหมดการส่งข้อมูลแบบใดเป็นหลัก?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'DNS โดยใช้ UDP สำหรับ Standard Queries และ TCP สำหรับ Zone Transfer หรือคำตอบขนาดใหญ่' },
        { key: 'B', text: 'HTTP โดยใช้เฉพาะ TCP' },
        { key: 'C', text: 'SMTP โดยใช้เฉพาะ UDP' },
        { key: 'D', text: 'RDP โดยใช้เฉพาะ ICMP' },
      ],
      correctAnswer: 'A',
      explanation: 'DNS Query ทั่วไปใช้ UDP พอร์ต 53 เพื่อความรวดเร็ว แต่หากขนาดข้อมูลเกิน 512 ไบต์ (หรือ EDNS0) หรือทำ Zone Transfer จะใช้ TCP 53',
      order: 12,
    },
    {
      question: 'พอร์ตหมายเลข 25, 110, และ 143 สัมพันธ์กับบริการด้านใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ระบบรับส่งอีเมล (SMTP, POP3, IMAP)' },
        { key: 'B', text: 'ระบบแชร์ไฟล์และปริ้นเตอร์' },
        { key: 'C', text: 'ระบบฐานข้อมูล SQL' },
        { key: 'D', text: 'ระบบกระจายสัญญาณเสียง' },
      ],
      correctAnswer: 'A',
      explanation: '25 = SMTP (ส่งเมล), 110 = POP3 (ดึงเมลแบบไม่ซิงค์), 143 = IMAP (ดึงเมลแบบซิงค์กล่องข้อความ)',
      order: 13,
    },
    {
      question: 'พอร์ตหมายเลข 3306 และ 5432 เป็นพอร์ตเริ่มต้นของระบบฐานข้อมูลใดตามลำดับ?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'MySQL/MariaDB (3306) และ PostgreSQL (5432)' },
        { key: 'B', text: 'Oracle (3306) และ MongoDB (5432)' },
        { key: 'C', text: 'Redis (3306) และ SQLite (5432)' },
        { key: 'D', text: 'Cassandra (3306) และ Neo4j (5432)' },
      ],
      correctAnswer: 'A',
      explanation: '3306 คือพอร์ต Default ของ MySQL ส่วน 5432 คือพอร์ต Default ของ PostgreSQL',
      order: 14,
    },
    {
      question: 'เหตุใดจึงไม่ควรเปิดพอร์ตฐานข้อมูล (3306, 5432) สู่สาธารณะ (0.0.0.0)?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เพื่อป้องกันการถูกบอทสแกนและพยายาม Brute-force รหัสผ่านฐานข้อมูล หรือเจาะผ่านช่องโหว่ของ Database Engine' },
        { key: 'B', text: 'เพราะทำให้ตารางในฐานข้อมูลหายไปเอง' },
        { key: 'C', text: 'เพราะฐานข้อมูลจะรันช้าลง 90%' },
        { key: 'D', text: 'เพราะทำให้คอมพิวเตอร์กินไฟเพิ่มขึ้น' },
      ],
      correctAnswer: 'A',
      explanation: 'ฐานข้อมูลควร Bind อยู่ที่ localhost หรือเชื่อมต่อผ่าน Private Network / VPN เท่านั้น เพื่อลดความเสี่ยงจากการถูกโจมตีทางตรง',
      order: 15,
    },
    {
      question: 'การใช้บริการ Let\'s Encrypt มีจุดเด่นสำคัญอย่างไรในวงการความมั่นคงปลอดภัย?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ให้บริการออกใบรับรอง SSL/TLS ฟรีและสามารถต่ออายุอัตโนมัติผ่าน ACME Protocol' },
        { key: 'B', text: 'เป็นระบบตรวจจับมัลแวร์ในสมาร์ทโฟน' },
        { key: 'C', text: 'เป็นโปรแกรมทำเหมืองเหรียญคริปโต' },
        { key: 'D', text: 'เป็นระบบฮาร์ดแวร์ไฟร์วอลล์' },
      ],
      correctAnswer: 'A',
      explanation: 'Let\'s Encrypt ช่วยผลักดันให้อินเทอร์เน็ตทั่วโลกเปลี่ยนมาใช้ HTTPS โดยการแจกใบรับรองฟรีพร้อมระบบจัดการอัตโนมัติผ่าน Certbot/ACME',
      order: 16,
    },
    {
      question: 'คุณสมบัติ "Forward Secrecy" (PFS) ในโปรโตคอล TLS มีประโยชน์อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'แม้ Private Key หลักของเซิร์ฟเวอร์จะรั่วไหลในอนาคต ผู้โจมตีก็ยังไม่สามารถถอดรหัสเซสชันที่เคยดักฟังบันทึกไว้ในอดีตได้' },
        { key: 'B', text: 'ช่วยส่งข้อความไปหาผู้รับในอนาคตได้' },
        { key: 'C', text: 'ทำให้ไม่ต้องใช้รหัสผ่านในการเข้าใช้งาน' },
        { key: 'D', text: 'ทำให้เซิร์ฟเวอร์ไม่ต้องการการสำรองข้อมูล' },
      ],
      correctAnswer: 'A',
      explanation: 'PFS (ใช้ Ephemeral Diffie-Hellman: ECDHE) สร้าง Session Key ชั่วคราวเฉพาะแต่ละเซสชัน ทำให้การรั่วไหลของ Master Key ย้อนหลังไม่กระทบอดีต',
      order: 17,
    },
    {
      question: 'Certificate Transparency (CT) Logs มีบทบาทอย่างไรในการรักษาความปลอดภัยของระบบเว็บ?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เป็นสมุดบัญชีสาธารณะที่บันทึกการออกใบรับรอง SSL/TLS ทุกใบ ช่วยให้เจ้าของโดเมนตรวจพบหากมีใครแอบออกใบรับรองปลอมในชื่อโดเมนของตน' },
        { key: 'B', text: 'เป็นฐานข้อมูลรหัสผ่านที่หลุดสู่สาธารณะ' },
        { key: 'C', text: 'เป็นไฟล์บันทึกรายชื่อผู้เข้าชมเว็บ' },
        { key: 'D', text: 'เป็นเครื่องมือบีบอัดไฟล์ PDF' },
      ],
      correctAnswer: 'A',
      explanation: 'CT Logs บังคับให้ CA ต้องส่งบันทึกการออกใบรับรองเข้าระบบ Audit สาธารณะ ทำให้ตรวจจับ Rogue CA หรือการปลอมแปลงใบรับรองได้อย่างรวดเร็ว',
      order: 18,
    },
    {
      question: 'คำสั่ง `dig +short example.com A` หรือ `nslookup example.com` มีหน้าที่อะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ส่งคำขอสอบถาม DNS ไปยัง Resolver เพื่อขอข้อมูลหมายเลข IP Address ของโดเมนเป้าหมาย' },
        { key: 'B', text: 'ดาวน์โหลดหน้าเว็บเพจทั้งหมดลงเครื่อง' },
        { key: 'C', text: 'ลบชื่อโดเมนออกจากอินเทอร์เน็ต' },
        { key: 'D', text: 'รีสตาร์ทเซิร์ฟเวอร์ปลายทาง' },
      ],
      correctAnswer: 'A',
      explanation: 'dig และ nslookup เป็นเครื่องมือมาตรฐานบน Terminal สำหรับ Query ข้อมูล DNS Records จากเซิร์ฟเวอร์',
      order: 19,
    },
    {
      question: 'ข้อใดคือพอร์ตมาตรฐานของบริการ Remote Desktop Protocol (RDP) บนระบบ Windows?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'พอร์ต 3389' },
        { key: 'B', text: 'พอร์ต 22' },
        { key: 'C', text: 'พอร์ต 80' },
        { key: 'D', text: 'พอร์ต 445' },
      ],
      correctAnswer: 'A',
      explanation: 'RDP บน Windows ใช้พอร์ต 3389 (TCP/UDP) สำหรับการรีโมทควบคุมหน้าจอเดสก์ท็อป',
      order: 20,
    },
  ],

  // 5. Linux Security & Permissions
  'lesson-b3-1': [
    {
      question: 'คำสั่ง `chmod 750 secure_script.sh` กำหนดสิทธิ์ให้กับ User, Group, และ Others อย่างไรตามลำดับ?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'User: rwx (7), Group: r-x (5), Others: --- (0 ไม่มีสิทธิ์ใดๆ)' },
        { key: 'B', text: 'User: r-x (5), Group: rwx (7), Others: r-- (4)' },
        { key: 'C', text: 'User: r--, Group: -w-, Others: --x' },
        { key: 'D', text: 'ให้สิทธิ์ทุกคนทำได้ทุกอย่างเท่ากัน' },
      ],
      correctAnswer: 'A',
      explanation: '7 = 4(r)+2(w)+1(x), 5 = 4(r)+0+1(x), 0 = ไม่มีสิทธิ์ ทำให้เจ้าของอ่านเขียนรันได้ กลุ่มอ่านรันได้ และคนอื่นเข้าไม่ถึงเลย',
      order: 1,
    },
    {
      question: 'ไฟล์ SSH Private Key (`id_rsa`) ควรกำหนดสิทธิ์การเข้าถึงแบบ Octal เป็นค่าใดเพื่อความปลอดภัยสูงสุด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'chmod 600 id_rsa (เฉพาะเจ้าของอ่านและเขียนได้เท่านั้น)' },
        { key: 'B', text: 'chmod 777 id_rsa (ให้ทุกคนเข้าถึงได้)' },
        { key: 'C', text: 'chmod 666 id_rsa (ให้อ่านเขียนได้ทุกคน)' },
        { key: 'D', text: 'chmod 000 id_rsa (ห้ามทุกคนอ่าน)' },
      ],
      correctAnswer: 'A',
      explanation: 'SSH Client จะปฏิเสธการใช้งานทันทีหาก Private Key มีสิทธิ์ที่หลวมเกินไป (ต้องเป็น 600 หรือ 400 เพื่อป้องกันผู้ใช้อื่นในเครื่องแอบอ่าน)',
      order: 2,
    },
    {
      question: 'บนระบบปฏิบัติการ Linux ไฟล์ใดเก็บรหัสผ่านที่ผ่านการแฮช (Password Hashes) ของผู้ใช้ไว้?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '/etc/shadow' },
        { key: 'B', text: '/etc/passwd' },
        { key: 'C', text: '/etc/hosts' },
        { key: 'D', text: '/var/log/syslog' },
      ],
      correctAnswer: 'A',
      explanation: '/etc/passwd เก็บข้อมูลบัญชีทั่วไปที่ทุกคนอ่านได้ ส่วน /etc/shadow เก็บ Password Hash ที่เฉพาะสิทธิ์ root เท่านั้นที่อ่านได้',
      order: 3,
    },
    {
      question: 'สิทธิ์พิเศษ "SUID" (Set User ID) ที่ตั้งไว้บนไฟล์ Binary มีพฤติกรรมอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เมื่อผู้ใช้ทั่วไปรันโปรแกรมนี้ โปรแกรมจะทำงานด้วยสิทธิ์ของเจ้าของไฟล์ (เช่น root) ชั่วคราว' },
        { key: 'B', text: 'ทำให้ไฟล์นั้นไม่สามารถลบได้ตลอดไป' },
        { key: 'C', text: 'เปลี่ยนชื่อไฟล์เป็นตัวพิมพ์เล็ก' },
        { key: 'D', text: 'ส่งอีเมลแจ้งเตือนทุกครั้งที่มีคนเปิดไฟล์' },
      ],
      correctAnswer: 'A',
      explanation: 'SUID (เช่น บนคำสั่ง passwd) ช่วยให้โปรแกรมรันด้วยสิทธิ์เจ้าของไฟล์ หากเขียนไม่รัดกุมอาจถูกใช้ทำ Privilege Escalation ได้',
      order: 4,
    },
    {
      question: 'ไฟล์ Log ใดบน Ubuntu/Debian ที่บันทึกประวัติการ Login, ความพยายามเข้าสู่ระบบ และการใช้คำสั่ง sudo?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '/var/log/auth.log' },
        { key: 'B', text: '/var/log/nginx/access.log' },
        { key: 'C', text: '/var/log/dpkg.log' },
        { key: 'D', text: '/var/log/bootstrap.log' },
      ],
      correctAnswer: 'A',
      explanation: '/var/log/auth.log (บน RHEL/CentOS คือ /var/log/secure) เป็นจุดตรวจสอบหลักสำหรับการวิเคราะห์การเข้าสู่ระบบและ Brute-force attacks',
      order: 5,
    },
    {
      question: 'คำสั่งใดใช้ตรวจสอบสถานะการทำงานและบันทึกเหตุการณ์ของ Service ผ่าน systemd บน Linux?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'systemctl status <service> และ journalctl -u <service>' },
        { key: 'B', text: 'ping -c 4 localhost' },
        { key: 'C', text: 'ls -la /home' },
        { key: 'D', text: 'chmod +x /bin/bash' },
      ],
      correctAnswer: 'A',
      explanation: 'systemctl ใช้ควบคุมสถานะ Service และ journalctl ใช้ดูบันทึก Log ของระบบและ Service อย่างละเอียด',
      order: 6,
    },
    {
      question: 'การตั้งค่าในไฟล์ `/etc/ssh/sshd_config` ข้อใดช่วยยกระดับความปลอดภัยให้กับ SSH Server ได้ดีที่สุด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'PermitRootLogin no และ PasswordAuthentication no (บังคับใช้ SSH Key เท่านั้น)' },
        { key: 'B', text: 'PermitEmptyPasswords yes' },
        { key: 'C', text: 'PermitRootLogin yes' },
        { key: 'D', text: 'MaxAuthTries 1000' },
      ],
      correctAnswer: 'A',
      explanation: 'การปิด Root Login ตรงๆ และปิด Password Authentication โดยบังคับใช้ Key-based Auth ช่วยตัดโอกาสการถูก Brute-force รหัสผ่านได้เกือบ 100%',
      order: 7,
    },
    {
      question: 'คำสั่ง `chown www-data:www-data /var/www/html` ทำหน้าที่อะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เปลี่ยนผู้ครอบครอง (Owner) และกลุ่ม (Group) ของโฟลเดอร์ให้เป็นของ www-data' },
        { key: 'B', text: 'ลบไฟล์ทั้งหมดในโฟลเดอร์ทิ้ง' },
        { key: 'C', text: 'บีบอัดโฟลเดอร์เป็น zip' },
        { key: 'D', text: 'ส่งไฟล์ไปที่เว็บเซิร์ฟเวอร์ภายนอก' },
      ],
      correctAnswer: 'A',
      explanation: 'chown ย่อมาจาก Change Owner ใช้เปลี่ยนผู้ใช้และกลุ่มที่เป็นเจ้าของไฟล์หรือไดเรกทอรี',
      order: 8,
    },
    {
      question: 'Sticky Bit (เช่น `chmod 1777 /tmp`) มีคุณสมบัติพิเศษอย่างไรกับไดเรกทอรีแชร์?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'อนุญาตให้ทุกคนสร้างไฟล์ได้ แต่ผู้ที่จะลบหรือเปลี่ยนชื่อไฟล์ได้ต้องเป็นเจ้าของไฟล์นั้นๆ หรือ root เท่านั้น' },
        { key: 'B', text: 'ทำให้ไฟล์ในโฟลเดอร์ติดไวรัสทันที' },
        { key: 'C', text: 'ป้องกันไม่ให้ใครสร้างไฟล์ใหม่ในโฟลเดอร์ได้' },
        { key: 'D', text: 'ทำให้ไฟล์มีขนาดเล็กลงครึ่งหนึ่ง' },
      ],
      correctAnswer: 'A',
      explanation: 'Sticky Bit ป้องกันไม่ให้ผู้ใช้คนอื่นมาลบหรือแก้ไขไฟล์ของคนอื่นในไดเรกทอรีสาธารณะอย่าง /tmp',
      order: 9,
    },
    {
      question: 'ไฟล์คอนฟิกูเรชัน `/etc/sudoers` ควรได้รับการแก้ไขผ่านคำสั่งใดเสมอเพื่อป้องกันข้อผิดพลาดทางไวยากรณ์?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'visudo' },
        { key: 'B', text: 'cat' },
        { key: 'C', text: 'echo' },
        { key: 'D', text: 'rm' },
      ],
      correctAnswer: 'A',
      explanation: 'visudo จะทำการตรวจสอบไวยากรณ์ก่อนบันทึกไฟล์ ป้องกันข้อผิดพลาดที่อาจทำให้ระบบล็อคคำสั่ง sudo จนไม่มีใครใช้งานสิทธิ์ root ได้',
      order: 10,
    },
    {
      question: 'คำสั่งใดใช้แสดงรายการโปรเซสที่กำลังทำงานอยู่ทั้งหมดบนระบบพร้อมรายละเอียดผู้ใช้งาน?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ps aux หรือ top / htop' },
        { key: 'B', text: 'ifconfig' },
        { key: 'C', text: 'uname -a' },
        { key: 'D', text: 'df -h' },
      ],
      correctAnswer: 'A',
      explanation: 'ps aux แสดง Snapshot ของ Process ทั้งหมด ส่วน top/htop แสดง Process แบบ Real-time',
      order: 11,
    },
    {
      question: 'กลไก SELinux (Security-Enhanced Linux) หรือ AppArmor มีหน้าที่สำคัญอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Mandatory Access Control (MAC) บังคับใช้นโยบายควบคุมสิทธิ์ของ Process ไม่ให้เข้าถึงทรัพยากรนอกเหนือจากที่กำหนดแม้โปรเซสจะเป็น root' },
        { key: 'B', text: 'เป็นโปรแกรมเล่นไฟล์เพลง' },
        { key: 'C', text: 'เพิ่มความสว่างหน้าจอ' },
        { key: 'D', text: 'ลบไฟล์แคชในเครื่อง' },
      ],
      correctAnswer: 'A',
      explanation: 'MAC (SELinux/AppArmor) จำกัดขอบเขตของ Service แม้แฮกเกอร์จะเจาะเว็บเซิร์ฟเวอร์จนได้สิทธิ์ www-data/root ก็ไม่สามารถอ่านไฟล์ลับนอกนโยบายได้',
      order: 12,
    },
    {
      question: 'คำสั่ง `ss -tulpn` หรือ `netstat -tulpn` มีประโยชน์อย่างไรต่อนักวิเคราะห์ความปลอดภัย?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ตรวจสอบพอร์ต TCP/UDP ที่เปิดดักฟัง (Listening) อยู่ในเครื่อง พร้อมแสดงหมายเลข PID และชื่อโปรแกรมที่เปิด' },
        { key: 'B', text: 'วัดความเร็วการเขียนข้อมูลลง Hard Disk' },
        { key: 'C', text: 'สแกนหาไฟล์เอกสาร Word' },
        { key: 'D', text: 'แสดงประวัติการเปิดดู YouTube' },
      ],
      correctAnswer: 'A',
      explanation: 'ss -tulpn ช่วยให้ผู้ดูแลระบบตรวจหา Backdoor หรือ Unauthorized Services ที่แอบเปิดพอร์ตเชื่อมต่อออกไปภายนอก',
      order: 13,
    },
    {
      question: 'คำสั่ง `ufw enable` และ `ufw allow 22/tcp` บน Ubuntu มีหน้าที่อะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เปิดใช้งานไฟร์วอลล์ (Uncomplicated Firewall) และอนุญาตให้เชื่อมต่อพอร์ต 22 (SSH) ผ่านเข้ามาได้' },
        { key: 'B', text: 'ลบระบบ SSH ทิ้ง' },
        { key: 'C', text: 'รีบูตระบบเข้าสู่ Safe Mode' },
        { key: 'D', text: 'ดาวน์โหลดระบบปฏิบัติการใหม่' },
      ],
      correctAnswer: 'A',
      explanation: 'UFW เป็นอินเทอร์เฟซควบคุม iptables บน Ubuntu ช่วยให้เปิดปิดพอร์ตไฟร์วอลล์ได้อย่างสะดวกและปลอดภัย',
      order: 14,
    },
    {
      question: 'โฟลเดอร์ `/proc` บน Linux มีลักษณะพิเศษอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เป็น Virtual Filesystem ในหน่วยความจำที่แสดงข้อมูลสถานะของ Kernel และ Processes ที่กำลังทำงานอยู่' },
        { key: 'B', text: 'เป็นโฟลเดอร์สำหรับเก็บไฟล์ภาพยนตร์' },
        { key: 'C', text: 'เป็นที่เก็บไฟล์ Backup ของฐานข้อมูล' },
        { key: 'D', text: 'เป็นโฟลเดอร์ที่ถูกเข้ารหัสด้วย BitLocker' },
      ],
      correctAnswer: 'A',
      explanation: '/proc สร้างขึ้นบน RAM โดย Kernel เช่น /proc/[PID]/cmdline เก็บคำสั่งที่ใช้รัน Process นั้นๆ มีประโยชน์มากต่อการทำ Forensic',
      order: 15,
    },
    {
      question: 'เครื่องมือ `fail2ban` ทำงานอย่างไรในการป้องกันเซิร์ฟเวอร์ Linux จากการถูก Brute-force?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'คอยอ่านไฟล์ Log (เช่น auth.log) และสั่งบล็อก IP ใน Firewall โดยอัตโนมัติเมื่อพบการ Login ล้มเหลวติดต่อกันเกินกำหนด' },
        { key: 'B', text: 'ลบบัญชีผู้ใช้ที่ล็อกอินผิดทิ้งทันที' },
        { key: 'C', text: 'ปิดเครื่องเซิร์ฟเวอร์ทันที' },
        { key: 'D', text: 'เปลี่ยนรหัสผ่าน root เป็นค่าสุ่มใหม่' },
      ],
      correctAnswer: 'A',
      explanation: 'fail2ban ตรวจจับพฤติกรรม Brute-force จาก Log แล้วเขียนกฎ iptables เพื่อแบนไอพีนั้นชั่วคราวหรือถาวร',
      order: 16,
    },
    {
      question: 'การรัน Container (เช่น Docker) ด้วย Flag `--privileged` หรือสิทธิ์ `root` มีความเสี่ยงอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'หากคอนเทนเนอร์ถูกเจาะ ผู้โจมตีอาจสามารถ Escape ออกมาควบคุมระบบปฏิบัติการหลักของโฮสต์ (Host OS) ได้' },
        { key: 'B', text: 'ทำให้ Docker ดาวน์โหลดอิมเมจช้าลง' },
        { key: 'C', text: 'ทำให้สีของ Terminal เปลี่ยนไป' },
        { key: 'D', text: 'ไม่มีความเสี่ยงใดๆ เพราะ Docker ปลอดภัยสมบูรณ์เสมอ' },
      ],
      correctAnswer: 'A',
      explanation: 'Privileged Container ปิดฟีเจอร์ Isolation ของ Linux Namespaces/Capabilities ทำให้เปิดช่อง Container Breakout เข้าสู่ Host',
      order: 17,
    },
    {
      question: 'คำสั่ง `grep "Failed password" /var/log/auth.log` มีประโยชน์สำหรับกิจกรรมใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ค้นหารายการความพยายามล็อกอินที่ใส่รหัสผ่านผิด เพื่อตรวจสอบการโจมตีแบบ Brute-force หรือ Password Spraying' },
        { key: 'B', text: 'กู้คืนรหัสผ่านที่ลืม' },
        { key: 'C', text: 'เปลี่ยนรหัสผ่านของผู้ใช้' },
        { key: 'D', text: 'ลบประวัติการพิมพ์คำสั่ง' },
      ],
      correctAnswer: 'A',
      explanation: 'คำสั่งนี้ช่วยคัดกรอง Log รายการ Failed Password ทำให้เห็น IP ต้นทางที่พยายามสุ่มรหัสผ่านเข้ามา',
      order: 18,
    },
    {
      question: 'การตั้งค่า `umask 027` บน Linux มีผลต่อการสร้างไฟล์ใหม่ของผู้ใช้อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ไฟล์ที่สร้างใหม่จะมีสิทธิ์เริ่มต้นเป็น 640 (เจ้าของอ่านเขียนได้ กลุ่มอ่านได้ คนอื่นห้ามเข้าถึง)' },
        { key: 'B', text: 'ไฟล์ที่สร้างใหม่จะเปิดให้ทุกคนอ่านเขียนได้' },
        { key: 'C', text: 'ไฟล์จะถูกลบอัตโนมัติภายใน 27 นาที' },
        { key: 'D', text: 'ป้องกันไม่ให้ผู้ใช้สร้างไฟล์ใหม่' },
      ],
      correctAnswer: 'A',
      explanation: 'umask ตัดสิทธิ์เริ่มต้นออก (666 - 027 = 640 สำหรับไฟล์, 777 - 027 = 750 สำหรับโฟลเดอร์) ช่วยเพิ่มความปลอดภัย',
      order: 19,
    },
    {
      question: 'คำสั่ง `crontab -l` และการตรวจสอบไดเรกทอรี `/etc/cron.*` มีความสำคัญในการตรวจสอบความปลอดภัยอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ตรวจสอบงานที่ตั้งเวลาทำงานอัตโนมัติ (Scheduled Tasks) เพื่อค้นหา Persistence Backdoors ที่ผู้โจมตีอาจฝังไว้' },
        { key: 'B', text: 'ตั้งเวลานาฬิกาปลุกของเซิร์ฟเวอร์' },
        { key: 'C', text: 'ตรวจสอบประวัติการซื้อของออนไลน์' },
        { key: 'D', text: 'วัดความเร็วของพัดลมระบายความร้อน' },
      ],
      correctAnswer: 'A',
      explanation: 'ผู้โจมตีมักฝัง Backdoor script ไว้ใน Cron เพื่อให้รันเชื่อมต่อกลับ (Reverse Shell) อัตโนมัติทุกๆ ชั่วโมงหรือเมื่อเครื่องรีบูต',
      order: 20,
    },
  ],

  // 6. Windows Security & Event Viewer
  'lesson-b3-2': [
    {
      question: 'ใน Windows Event Viewer หมายเลข Event ID ใดบ่งชี้ว่ามีการ "เข้าสู่ระบบสำเร็จ (Successful Logon)"?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Event ID 4624' },
        { key: 'B', text: 'Event ID 4625' },
        { key: 'C', text: 'Event ID 4688' },
        { key: 'D', text: 'Event ID 1102' },
      ],
      correctAnswer: 'A',
      explanation: 'Event ID 4624 คือ Successful Logon บน Windows Security Log ระบุชื่อผู้ใช้และประเภทการล็อกอิน (เช่น Interactive, Network, RDP)',
      order: 1,
    },
    {
      question: 'หมายเลข Event ID 4625 บน Windows มีความหมายถึงเหตุการณ์ใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การเข้าสู่ระบบล้มเหลว (Failed Logon - ตัวบ่งชี้การถูก Brute-force หรือ Password Spraying)' },
        { key: 'B', text: 'การปิดเครื่องคอมพิวเตอร์' },
        { key: 'C', text: 'การติดตั้งไดรเวอร์เครื่องพิมพ์' },
        { key: 'D', text: 'การเปิดดูไฟล์เอกสารสำเร็จ' },
      ],
      correctAnswer: 'A',
      explanation: 'Event ID 4625 ถูกสร้างขึ้นเมื่อมีการใส่ชื่อผู้ใช้หรือรหัสผ่านผิด หากเกิดขึ้นจำนวนมากในเวลาสั้นๆ บ่งชี้การโจมตีทางรหัสผ่าน',
      order: 2,
    },
    {
      question: 'Event ID 4688 มีบทบาทสำคัญอย่างยิ่งต่อนักสืบสวนภัยคุกคามทางไซเบอร์ (Threat Hunter) เนื่องจากบันทึกอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การสร้าง Process ใหม่ขึ้นในระบบ (Process Creation พร้อม Parent Process และ Command Line)' },
        { key: 'B', text: 'การเปลี่ยนสีหน้าจอพื้นหลัง' },
        { key: 'C', text: 'การเชื่อมต่อหูฟังบลูทูธ' },
        { key: 'D', text: 'การตั้งค่าระดับเสียงลำโพง' },
      ],
      correctAnswer: 'A',
      explanation: 'Event ID 4688 ช่วยตรวจสอบ Process Tree เช่น เมื่อ Microsoft Word (WINWORD.EXE) ไปเรียกสั่งรัน powershell.exe ซึ่งเป็นพฤติกรรมมัลแวร์ชัดเจน',
      order: 3,
    },
    {
      question: 'Event ID 1102 บน Windows Security Log มีความสำคัญระดับวิกฤตอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Security Audit Log ถูกลบหรือล้างข้อมูลทิ้ง (The audit log was cleared) บ่งชี้ว่าผู้โจมตีกำลังพยายามทำลายหลักฐาน' },
        { key: 'B', text: 'เครื่องเซิร์ฟเวอร์อัปเดต Windows สำเร็จ' },
        { key: 'C', text: 'การเชื่อมต่อ Wi-Fi หลุด' },
        { key: 'D', text: 'มีการเสียบสายชาร์จไฟ' },
      ],
      correctAnswer: 'A',
      explanation: 'เมื่อผู้โจมตียึดเครื่องได้มักสั่ง `wevtutil cl Security` เพื่อลบ Log แต่ระบบจะบันทึก Event 1102 เสมอเพื่อเป็นหลักฐานว่า Log ถูกลบ',
      order: 4,
    },
    {
      question: 'กลไก User Account Control (UAC) บน Windows มีหน้าที่หลักเพื่ออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ป้องกันไม่ให้โปรแกรมทำงานด้วยสิทธิ์ระดับ Administrator โดยไม่ได้รับการยืนยันจากผู้ใช้ก่อน' },
        { key: 'B', text: 'ช่วยจำกัดปริมาณการดาวน์โหลดอินเทอร์เน็ต' },
        { key: 'C', text: 'ลบไฟล์แคชของเบราว์เซอร์อัตโนมัติ' },
        { key: 'D', text: 'ปิดหน้าต่างที่ไม่ได้ใช้งาน' },
      ],
      correctAnswer: 'A',
      explanation: 'UAC ทำให้แอปพลิเคชันทำงานในสภาพแวดล้อมสิทธิ์มาตรฐาน และจะแสดงหน้าต่างแจ้งเตือนขอความยินยอม (Prompt) เมื่อต้องแก้ไขระบบสำคัญ',
      order: 5,
    },
    {
      question: 'ฐานข้อมูล SAM (Security Account Manager) บนเครื่อง Standalone Windows ทำหน้าที่อะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เก็บข้อมูลบัญชีผู้ใช้และ Password Hashes (NTLM Hash) ของเครื่อง Local' },
        { key: 'B', text: 'เก็บไฟล์ภาพถ่ายของผู้ใช้' },
        { key: 'C', text: 'เก็บประวัติการท่องเว็บ' },
        { key: 'D', text: 'เก็บไดรเวอร์การ์ดจอ' },
      ],
      correctAnswer: 'A',
      explanation: 'SAM เก็บ Local Password Hashes ซึ่งถูกล็อคโดยระบบ ผู้โจมตีที่ได้สิทธิ์ SYSTEM อาจพยายาม Dump SAM ด้วยเครื่องมือเช่น Mimikatz',
      order: 6,
    },
    {
      question: 'ในสภาพแวดล้อม Active Directory โดเมนคอนโทรลเลอร์ใช้โปรโตคอลใดในการยืนยันตัวตน (Authentication) เป็นค่าเริ่มต้น?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Kerberos (ใช้ Ticket-Granting Ticket / TGT)' },
        { key: 'B', text: 'Telnet' },
        { key: 'C', text: 'FTP' },
        { key: 'D', text: 'POP3' },
      ],
      correctAnswer: 'A',
      explanation: 'Kerberos เป็นโปรโตคอลยืนยันตัวตนหลักบน Active Directory ที่มีความปลอดภัยสูงกว่า NTLM โดยใช้ตั๋ว Ticket และการเข้ารหัสสมมาตร',
      order: 7,
    },
    {
      question: 'PowerShell Execution Policy ชนิดใดที่เป็นค่าเริ่มต้นบนเครื่อง Windows Client ทั่วไปเพื่อป้องกันการรันสคริปต์สุ่มสี่สุ่มห้า?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Restricted (ไม่อนุญาตให้รันไฟล์ .ps1)' },
        { key: 'B', text: 'Unrestricted' },
        { key: 'C', text: 'Bypass' },
        { key: 'D', text: 'AllSigned' },
      ],
      correctAnswer: 'A',
      explanation: 'Restricted ป้องกันไม่ให้รันสคริปต์ .ps1 โดยไม่ตั้งใจ (อย่างไรก็ตาม Execution Policy ถูกออกแบบมาเพื่อป้องกันความผิดพลาด ไม่ใช่ Security Boundary ที่กันแฮกเกอร์)',
      order: 8,
    },
    {
      question: 'เทคโนโลยี BitLocker บนระบบปฏิบัติการ Windows มีหน้าที่ทำอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Full Volume Encryption (เข้ารหัสข้อมูลทั้งไดรฟ์เพื่อป้องกันการขโมยข้อมูลเมื่อฮาร์ดดิสก์ถูกถอดไปอ่านที่เครื่องอื่น)' },
        { key: 'B', text: 'เพิ่มความจุของฮาร์ดดิสก์เป็น 2 เท่า' },
        { key: 'C', text: 'บล็อกการเข้าถึงเว็บไซต์พนัน' },
        { key: 'D', text: 'กำจัดฝุ่นละอองภายในเคสคอมพิวเตอร์' },
      ],
      correctAnswer: 'A',
      explanation: 'BitLocker ทำงานร่วมกับชิป TPM (Trusted Platform Module) เพื่อเข้ารหัส Volume ป้องกันการขโมยข้อมูลทางกายภาพ',
      order: 9,
    },
    {
      question: 'เครื่องมือ Sysinternals ใดที่นิยมใช้ตรวจสอบ Process ที่กำลังทำงานอย่างละเอียด พร้อมตรวจสอบ Digital Signature และ Network Activity?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Process Explorer (procexp)' },
        { key: 'B', text: 'Notepad' },
        { key: 'C', text: 'Paint' },
        { key: 'D', text: 'Calculator' },
      ],
      correctAnswer: 'A',
      explanation: 'Process Explorer จาก Microsoft Sysinternals เป็นเครื่องมือที่ทรงพลังสำหรับการตรวจสอบ Process Tree, DLLs, Handles และตรวจเช็ค VirusTotal แบบ Real-time',
      order: 10,
    },
    {
      question: 'บริการ Windows Defender Exploit Guard (ASR Rules) ช่วยป้องกันพฤติกรรมใดของโปรแกรม Office?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'บล็อกไม่ให้แอปพลิเคชัน Office สร้าง Child Process (เช่น ไม่ให้ Word ไปเรียกรัน PowerShell หรือ CMD)' },
        { key: 'B', text: 'บล็อกไม่ให้ผู้ใช้พิมพ์ข้อความยาวเกินไป' },
        { key: 'C', text: 'บล็อกการบันทึกไฟล์เป็น PDF' },
        { key: 'D', text: 'บล็อกการเปลี่ยนฟอนต์เป็น Angsana New' },
      ],
      correctAnswer: 'A',
      explanation: 'ASR Rules (Attack Surface Reduction) ช่วยสกัดกั้นเทคนิคยอดนิยมของมัลแวร์ เช่น มาโครใน Excel/Word ที่พยายามสปอว์น CMD หรือ PowerShell',
      order: 11,
    },
    {
      question: 'Event ID 4720 บน Windows Security Log หมายถึงอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'A user account was created (มีการสร้างบัญชีผู้ใช้ใหม่ในระบบ)' },
        { key: 'B', text: 'มีการเปลี่ยนรหัสผ่าน' },
        { key: 'C', text: 'มีการลบบัญชีผู้ใช้' },
        { key: 'D', text: 'มีการล็อคหน้าจอ' },
      ],
      correctAnswer: 'A',
      explanation: 'Event ID 4720 ต้องได้รับการเฝ้าระวังอย่างใกล้ชิด เพราะผู้โจมตีที่ยึดระบบได้มักสร้าง Local Admin ใหม่เพื่อเป็นทางเข้าถาวร (Persistence)',
      order: 12,
    },
    {
      question: 'เครื่องมือ "Sysmon" (System Monitor) จาก Microsoft มีจุดเด่นเหนือกว่า Standard Windows Logging อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'บันทึกเหตุการณ์เชิงลึก เช่น Process Creation พร้อม File Hash, Network Connections, Process Injection และ Registry Changes' },
        { key: 'B', text: 'เป็นโปรแกรมแชทภายในออฟฟิศ' },
        { key: 'C', text: 'ช่วยดาวน์โหลดไดรเวอร์เสียง' },
        { key: 'D', text: 'ช่วยทำความสะอาดหน้าจอ' },
      ],
      correctAnswer: 'A',
      explanation: 'Sysmon เป็น Driver และ Service ที่บันทึก Security Telemetry ละเอียดสูง ส่งต่อไปยัง SIEM เพื่อตรวจจับการโจมตีขั้นสูงได้อย่างมีประสิทธิภาพ',
      order: 13,
    },
    {
      question: 'เทคนิค "Pass-the-Hash" (PtH) บนระบบ Windows อาศัยช่องโหว่ของอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การนำค่า NTLM Hash ที่ขโมยมาจากหน่วยความจำไปใช้ยืนยันตัวตนข้ามเครื่องได้โดยตรงโดยไม่ต้องแคร็กรหัสผ่านกลับเป็นตัวอักษร' },
        { key: 'B', text: 'การเดารหัสผ่านโดยใช้ดิกชันนารี' },
        { key: 'C', text: 'การตัดสัญญาณสาย LAN' },
        { key: 'D', text: 'การส่งสแปมอีเมล' },
      ],
      correctAnswer: 'A',
      explanation: 'โปรโตคอล NTLM ยอมรับ Hash ในการคำนวณ Challenge-Response ทำให้ผู้โจมตีที่มี Hash สามารถ Authenticate ไปยังเครื่องอื่นในโดเมนได้ทันที',
      order: 14,
    },
    {
      question: 'เทคโนโลยี "Credential Guard" บน Windows 10/11 และ Windows Server ช่วยป้องกันการโจมตีแบบ Mimikatz ได้อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ใช้ Virtualization-based Security (VBS) เพื่อแยกหน่วยความจำของ LSA (LSASS) ออกไปทำงานใน Isolated VM ที่แม้แต่ Admin ก็เข้าถึงไม่ได้' },
        { key: 'B', text: 'ลบรหัสผ่านออกจากระบบทั้งหมด' },
        { key: 'C', text: 'เปลี่ยนรหัสผ่านทุกๆ 1 วินาที' },
        { key: 'D', text: 'ปิดการทำงานของคีย์บอร์ด' },
      ],
      correctAnswer: 'A',
      explanation: 'Credential Guard แยก Secrets ของ NTLM/Kerberos ไปไว้ใน Isolated User Mode (LSAIso) ทำให้มัลแวร์หรือ Mimikatz ไม่สามารถอ่าน RAM ของ LSASS ได้',
      order: 15,
    },
    {
      question: 'ฟีเจอร์ "AppLocker" หรือ "Windows Defender Application Control (WDAC)" มีหน้าที่อะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'กำหนด Whitelist ควบคุมว่าอนุญาตให้ไฟล์ Executable, Script หรือ DLL ใดรันบนระบบได้บ้างตาม Path, Hash หรือ Certificate' },
        { key: 'B', text: 'ล็อคแอปพลิเคชันให้แสดงผลเต็มหน้าจอ' },
        { key: 'C', text: 'ควบคุมเวลาเปิดปิดแอปเพื่อประหยัดแบตเตอรี่' },
        { key: 'D', text: 'ดาวน์โหลดแอปใหม่จาก Windows Store' },
      ],
      correctAnswer: 'A',
      explanation: 'Application Whitelisting เป็นมาตรการป้องกันมัลแวร์ที่มีประสิทธิภาพสูงมาก โดยไม่อนุญาตให้โค้ดที่ไม่ได้รับอนุญาตทำงานบนเครื่อง',
      order: 16,
    },
    {
      question: 'เมื่อพบเหตุการณ์ Event ID 4738 บน Domain Controller เหตุการณ์นี้หมายถึงอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'A user account was modified (มีการแก้ไขเปลี่ยนแปลงข้อมูลหรือสิทธิ์ของบัญชีผู้ใช้)' },
        { key: 'B', text: 'มีการเข้าสู่ระบบสำเร็จ' },
        { key: 'C', text: 'มีการพิมพ์งานออกทางเครื่องพิมพ์' },
        { key: 'D', text: 'มีการเปลี่ยนวันที่ของระบบ' },
      ],
      correctAnswer: 'A',
      explanation: 'Event ID 4738 แสดงรายละเอียดเมื่อมีการแก้ไข User เช่น การเปลี่ยน Password, การเปิดใช้งาน Account ที่เคยถูกปิด หรือการแก้สิทธิ์',
      order: 17,
    },
    {
      question: 'คำสั่ง `Get-WinEvent -FilterHashtable @{LogName=\'Security\'; Id=4625}` ใน PowerShell ทำหน้าที่อะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ดึงข้อมูลรายการเข้าสู่ระบบล้มเหลว (Event 4625) ทั้งหมดจาก Security Log มาแสดงผล' },
        { key: 'B', text: 'ลบ Event Log ทั้งหมดทิ้ง' },
        { key: 'C', text: 'ปิดการทำงานของไฟร์วอลล์' },
        { key: 'D', text: 'รีสตาร์ทเครื่องคอมพิวเตอร์' },
      ],
      correctAnswer: 'A',
      explanation: 'Get-WinEvent เป็นคำสั่ง PowerShell ประสิทธิภาพสูงสำหรับดึงและวิเคราะห์ Event Logs ตามเงื่อนไขที่กำหนด',
      order: 18,
    },
    {
      question: 'เหตุใดการปิดโปรโตคอลเก่าอย่าง SMBv1 (Server Message Block v1) จึงเป็นข้อบังคับด้านความปลอดภัย?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'SMBv1 มีช่องโหว่ร้ายแรงระดับ Remote Code Execution เช่น EternalBlue (ที่ถูกใช้แพร่ระบาด WannaCry Ransomware)' },
        { key: 'B', text: 'เพราะทำให้ไฟล์ภาพเปิดไม่ติด' },
        { key: 'C', text: 'เพราะทำให้เสียงลำโพงเบาลง' },
        { key: 'D', text: 'เพราะ SMBv1 กินพื้นที่ฮาร์ดดิสก์ 1 Terabyte' },
      ],
      correctAnswer: 'A',
      explanation: 'SMBv1 เป็นโปรโตคอลล้าสมัยที่ไม่มีความปลอดภัยและมีช่องโหว่ EternalBlue (CVE-2017-0144) องค์กรต้องปิดการใช้งานอย่างเด็ดขาด',
      order: 19,
    },
    {
      question: 'ฟังก์ชัน "Controlled Folder Access" ใน Windows Defender มีประโยชน์อย่างไรในการต้านทาน Ransomware?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'บล็อกไม่ให้โปรแกรมที่ไม่ได้รับอนุญาต (Untrusted Apps) เข้าไปแก้ไขหรือเข้ารหัสไฟล์ในโฟลเดอร์สำคัญ (เช่น Documents, Pictures)' },
        { key: 'B', text: 'ซ่อนโฟลเดอร์ไม่ให้ผู้ใช้มองเห็น' },
        { key: 'C', text: 'จำกัดขนาดโฟลเดอร์ไม่ให้เกิน 10MB' },
        { key: 'D', text: 'บีบอัดโฟลเดอร์ให้เป็นไฟล์ RAR' },
      ],
      correctAnswer: 'A',
      explanation: 'Controlled Folder Access จะแจ้งเตือนและบล็อกทันทีหากมีแอปแปลกปลอมพยายามเขียนหรือเข้ารหัสไฟล์ในโฟลเดอร์เอกสารสำคัญ',
      order: 20,
    },
  ],

  // 7. HTTP Request Lifecycle, Cookies, Sessions & Headers
  'lesson-b3-3': [
    {
      question: 'Flag "HttpOnly" บนคุกกี้ (Set-Cookie: session=xyz; HttpOnly) มีหน้าที่ปกป้องระบบอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ป้องกันไม่ให้ JavaScript ฝั่งไคลเอนต์ (เช่น document.cookie) เข้าถึงคุกกี้ได้ ช่วยตัดวงจรการขโมย Session จาก XSS' },
        { key: 'B', text: 'บังคับให้ส่งคุกกี้ผ่าน HTTPS เท่านั้น' },
        { key: 'C', text: 'ทำให้คุกกี้หมดอายุทันทีที่ปิดแท็บ' },
        { key: 'D', text: 'เพิ่มความเร็วในการส่งคำขอ HTTP' },
      ],
      correctAnswer: 'A',
      explanation: 'HttpOnly ทำให้ Browser ไม่อนุญาตให้สคริปต์ JavaScript ในหน้าเว็บอ่านค่าคุกกี้นี้ ป้องกันผู้โจมตีที่ฝัง XSS ไม่ให้ขโมย Session Token ไปได้',
      order: 1,
    },
    {
      question: 'Flag "Secure" บนคุกกี้มีผลลัพธ์ในการทำงานอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'บังคับให้เบราว์เซอร์ส่งคุกกี้นี้แนบไปกับคำขอเฉพาะที่มีการเข้ารหัส HTTPS เท่านั้น ไม่ส่งผ่าน HTTP ธรรมดา' },
        { key: 'B', text: 'ทำให้คุกกี้ไม่สามารถถูกลบได้' },
        { key: 'C', text: 'ซ่อนคุกกี้ไม่ให้เซิร์ฟเวอร์อ่านได้' },
        { key: 'D', text: 'บีบอัดขนาดของคุกกี้' },
      ],
      correctAnswer: 'A',
      explanation: 'Secure Flag ป้องกันการดักฟังคุกกี้ผ่านเครือข่ายที่ไม่ปลอดภัย (Unencrypted HTTP)',
      order: 2,
    },
    {
      question: 'แอตทริบิวต์ `SameSite=Strict` บนคุกกี้ช่วยป้องกันการโจมตีประเภทใดได้ดีที่สุด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Cross-Site Request Forgery (CSRF)' },
        { key: 'B', text: 'SQL Injection' },
        { key: 'C', text: 'Buffer Overflow' },
        { key: 'D', text: 'SYN Flood' },
      ],
      correctAnswer: 'A',
      explanation: 'SameSite=Strict กำหนดให้เบราว์เซอร์ไม่ส่งคุกกี้ไปกับ Cross-Site Requests เลย ทำให้คำขอข้ามเว็บไซต์ของผู้โจมตีไม่มี Session แนบไปด้วย',
      order: 3,
    },
    {
      question: 'HTTP Status Code `401 Unauthorized` และ `403 Forbidden` มีความแตกต่างกันอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '401 หมายถึงยังไม่ได้ยืนยันตัวตน (Unauthenticated) ส่วน 403 หมายถึงยืนยันตัวตนแล้วแต่ไม่มีสิทธิ์เข้าถึงทรัพยากรนั้น (Unauthorized/Forbidden)' },
        { key: 'B', text: '401 คือหน้าเว็บไม่พบ ส่วน 403 คือเซิร์ฟเวอร์ล่ม' },
        { key: 'C', text: '401 ใช้กับมือถือ ส่วน 403 ใช้กับคอมพิวเตอร์' },
        { key: 'D', text: 'ทั้งสองรหัสมีความหมายเหมือนกันทุกประการ' },
      ],
      correctAnswer: 'A',
      explanation: '401 = ผู้ใช้ต้อง Login ก่อน, 403 = เซิร์ฟเวอร์รู้ว่าคุณคือใคร แต่สิทธิ์ของคุณไม่เพียงพอในการเข้าถึงหน้านี้',
      order: 4,
    },
    {
      question: 'Security Header `X-Frame-Options: DENY` (หรือ CSP `frame-ancestors \'none\'`) มีหน้าที่ป้องกันการโจมตีรูปแบบใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Clickjacking (การนำหน้าเว็บไปฝังใน iframe โปร่งใสซ้อนทับเพื่อหลอกให้เหยื่อคลิก)' },
        { key: 'B', text: 'SQL Injection' },
        { key: 'C', text: 'DNS Spoofing' },
        { key: 'D', text: 'DDoS Attack' },
      ],
      correctAnswer: 'A',
      explanation: 'X-Frame-Options: DENY ห้ามไม่ให้เบราว์เซอร์แสดงผลหน้าเว็บนี้ภายในแท็ก <frame>, <iframe> หรือ <object> ใดๆ ป้องกัน Clickjacking',
      order: 5,
    },
    {
      question: 'Header `Content-Security-Policy (CSP)` มีบทบาทสำคัญที่สุดในการป้องกันช่องโหว่ใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Cross-Site Scripting (XSS) และ Data Injection Attacks' },
        { key: 'B', text: 'Port Scanning' },
        { key: 'C', text: 'ARP Spoofing' },
        { key: 'D', text: 'Password Brute-forcing' },
      ],
      correctAnswer: 'A',
      explanation: 'CSP กำหนดรายชื่อโดเมนและเงื่อนไขที่เบราว์เซอร์ได้รับอนุญาตให้ดาวน์โหลดและรัน Script, Image, Style ทำให้ XSS ไม่สามารถโหลด Payload ภายนอกมารันได้',
      order: 6,
    },
    {
      question: 'Header `X-Content-Type-Options: nosniff` ช่วยป้องกันความเสี่ยงด้านใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ป้องกันเบราว์เซอร์จากการทำ MIME-sniffing (เดาประเภทไฟล์เอง) ซึ่งอาจทำให้ไฟล์ข้อความหรือรูปภาพที่มีโค้ดแฝงถูกรันเป็น JavaScript' },
        { key: 'B', text: 'ป้องกันไม่ให้ผู้ใช้ดาวน์โหลดรูปภาพ' },
        { key: 'C', text: 'บีบอัดไฟล์ภาพให้เล็กลง' },
        { key: 'D', text: 'เร่งความเร็วในการโหลด CSS' },
      ],
      correctAnswer: 'A',
      explanation: 'nosniff บังคับให้เบราว์เซอร์เชื่อค่า Content-Type ที่เซิร์ฟเวอร์ส่งมาอย่างเคร่งครัด ป้องกันการหลอกรันสคริปต์ผ่านไฟล์แนบ',
      order: 7,
    },
    {
      question: 'กลไก CORS (Cross-Origin Resource Sharing) เป็นมาตรการความปลอดภัยที่ถูกบังคับใช้โดยใคร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เว็บเบราว์เซอร์ (Web Browser) ของผู้ใช้งาน เพื่อควบคุมการเข้าถึงทรัพยากรข้ามโดเมน' },
        { key: 'B', text: 'เราเตอร์ Wi-Fi' },
        { key: 'C', text: 'ผู้ให้บริการอินเทอร์เน็ต (ISP)' },
        { key: 'D', text: 'สายเคเบิลใต้น้ำ' },
      ],
      correctAnswer: 'A',
      explanation: 'CORS เป็นกลไกความปลอดภัยฝั่ง Browser ที่ทำงานร่วมกับ Same-Origin Policy (SOP) เพื่อป้องกันสคริปต์ของเว็บหนึ่งแอบอ่านข้อมูลจากอีกเว็บหนึ่ง',
      order: 8,
    },
    {
      question: 'เมื่อเบราว์เซอร์จะส่งคำขอข้าม Origin ที่ซับซ้อน (เช่น มี Custom Header หรือใช้ Method PUT/DELETE) เบราว์เซอร์จะส่งคำขอใดไปล่วงหน้าก่อน?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'CORS Preflight Request ด้วย HTTP Method OPTIONS' },
        { key: 'B', text: 'HTTP Method GET' },
        { key: 'C', text: 'ICMP Echo Request' },
        { key: 'D', text: 'DNS Query' },
      ],
      correctAnswer: 'A',
      explanation: 'Preflight Request (OPTIONS) ทำหน้าที่ถามเซิร์ฟเวอร์ปลายทางล่วงหน้าว่าอนุญาตให้ส่ง Method และ Header นี้มาจาก Origin นี้หรือไม่',
      order: 9,
    },
    {
      question: 'HTTP Method ใดต่อไปนี้ตามมาตรฐาน RFC ถูกกำหนดให้เป็น "Safe & Idempotent" (ไม่มีผลข้างเคียงในการเปลี่ยนแปลงสถานะข้อมูลบนเซิร์ฟเวอร์)?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'GET และ HEAD' },
        { key: 'B', text: 'POST' },
        { key: 'C', text: 'PATCH' },
        { key: 'D', text: 'DELETE' },
      ],
      correctAnswer: 'A',
      explanation: 'GET และ HEAD เป็น Safe Method ใช้สำหรับอ่านข้อมูลเท่านั้น ไม่ควรนำไปใช้ในการทำธุรกรรมเปลี่ยนสถานะข้อมูล (เช่น ห้ามใช้ /delete_user?id=5 บน GET)',
      order: 10,
    },
    {
      question: 'เหตุใดการเก็บ Sensitive Data (เช่น รหัสผ่าน, API Keys, หรือบัตรเครดิต) ใน URL Query Parameter (GET Request) จึงเป็นข้อผิดพลาดร้ายแรง?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เพราะ URL จะถูกบันทึกอยู่ใน Browser History, Web Server Access Logs, Proxy Logs และ Header Referer ส่งผลให้ข้อมูลรั่วไหลได้ง่าย' },
        { key: 'B', text: 'เพราะทำให้ URL ยาวเกิน 10 ตัวอักษรไม่ได้' },
        { key: 'C', text: 'เพราะเบราว์เซอร์จะลบ URL ทิ้งทันที' },
        { key: 'D', text: 'เพราะทำให้เว็บเพจโหลดช้าลง 50%' },
      ],
      correctAnswer: 'A',
      explanation: 'ข้อมูลใน URL ไม่ได้รับการปกป้องเหมือน Request Body โดยจะปรากฏใน Log ของทุกจุดที่ผ่าน จึงห้ามส่งข้อมูลสำคัญผ่าน Query Strings เด็ดขาด',
      order: 11,
    },
    {
      question: 'Header `Referrer-Policy: strict-origin-when-cross-origin` มีประโยชน์อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ส่ง Full URL เฉพาะคำขอภายในเว็บเดิม แต่จะส่งเฉพาะ Origin (เช่น https://example.com) เมื่อข้ามไปยังเว็บอื่น และไม่ส่งเลยหาก Downgrade เป็น HTTP' },
        { key: 'B', text: 'ป้องกันไม่ให้เว็บลิงก์ไปหาเว็บอื่น' },
        { key: 'C', text: 'ลบประวัติการกดปุ่ม Back' },
        { key: 'D', text: 'เพิ่มคะแนน SEO ของเว็บไซต์' },
      ],
      correctAnswer: 'A',
      explanation: 'Referrer-Policy ควบคุมปริมาณข้อมูล URL อ้างอิงที่ส่งไปกับ Request ข้ามเว็บ ช่วยป้องกัน Path หรือ Query Parameter รั่วไหลสู่ Third-party',
      order: 12,
    },
    {
      question: 'Session Hijacking (การขโมยเซสชัน) สามารถเกิดขึ้นได้จากวิธีใดต่อไปนี้?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การดักฟังคุกกี้บนเครือข่าย Wi-Fi ที่ไม่มี HTTPS (Packet Sniffing) หรือการขโมยผ่านช่องโหว่ XSS' },
        { key: 'B', text: 'การปิดหน้าจอคอมพิวเตอร์' },
        { key: 'C', text: 'การกดปุ่ม F5 รีเฟรชหน้าเว็บ' },
        { key: 'D', text: 'การตั้งรหัสผ่านยาวกว่า 16 ตัวอักษร' },
      ],
      correctAnswer: 'A',
      explanation: 'หากไม่มีการเข้ารหัส HTTPS หรือไม่มีการตั้งค่า HttpOnly คุกกี้ Session ID อาจถูกดักฟังหรือถูกสคริปต์ XSS ขโมยไปสวมรอยเข้าใช้งาน',
      order: 13,
    },
    {
      question: 'แนวทาง "Session Regeneration" (สร้าง Session ID ใหม่ทันทีเมื่อผู้ใช้ล็อกอินสำเร็จ) มีเป้าหมายเพื่อป้องกันการโจมตีใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Session Fixation (การที่ผู้โจมตีกำหนด Session ID หลอกไว้ล่วงหน้าให้เหยื่อใช้ล็อกอิน)' },
        { key: 'B', text: 'SQL Injection' },
        { key: 'C', text: 'DDoS Attack' },
        { key: 'D', text: 'Buffer Overflow' },
      ],
      correctAnswer: 'A',
      explanation: 'การสร้าง Session ID ใหม่หลัง Login ทำลาย Session ID เก่าที่อาจถูกผู้ไม่หวังดีป้อนไว้ล่วงหน้า (Session Fixation)',
      order: 14,
    },
    {
      question: 'การกำหนด `Cache-Control: no-store, max-age=0` มีความสำคัญอย่างไรในหน้าเว็บที่มีข้อมูลส่วนบุคคลหรือข้อมูลการเงิน?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'สั่งไม่ให้เบราว์เซอร์หรือ Proxy แคชข้อมูลหน้านั้นไว้ ป้องกันไม่ให้บุคคลอื่นที่มาใช้คอมพิวเตอร์เครื่องเดียวกันกดปุ่ม Back แล้วเห็นข้อมูลลับ' },
        { key: 'B', text: 'ทำให้หน้าเว็บเปิดไม่ได้หากไม่มีเน็ต' },
        { key: 'C', text: 'ลบคุกกี้ทั้งหมดในเครื่อง' },
        { key: 'D', text: 'บังคับให้ดาวน์โหลดฟอนต์ใหม่ทุกครั้ง' },
      ],
      correctAnswer: 'A',
      explanation: 'no-store ป้องกันไม่ให้ข้อมูลความลับถูกบันทึกลงดิสก์ของเครื่องสาธารณะหรือแคชเซิร์ฟเวอร์',
      order: 15,
    },
    {
      question: 'ความแตกต่างระหว่าง `SameSite=Lax` และ `SameSite=Strict` คืออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Lax ยอมให้ส่งคุกกี้เมื่อผู้ใช้คลิกลิงก์ข้ามเว็บแบบ Top-level Navigation (GET) ได้ แต่ Strict จะไม่ส่งคุกกี้ในคำขอข้ามเว็บทุกกรณี' },
        { key: 'B', text: 'Lax ปลอดภัยกว่า Strict 10 เท่า' },
        { key: 'C', text: 'Strict ใช้ได้เฉพาะบนโทรศัพท์มือถือ' },
        { key: 'D', text: 'Lax ไม่มีการตรวจสอบความปลอดภัยใดๆ' },
      ],
      correctAnswer: 'A',
      explanation: 'Lax เป็นค่า Default ของเบราว์เซอร์ยุคใหม่ ให้ความสมดุลระหว่างความสะดวก (คลิกลิงก์จากเมลแล้วยังล็อกอินอยู่) กับการป้องกัน CSRF บน POST requests',
      order: 16,
    },
    {
      question: 'การใช้ `localStorage` ในเบราว์เซอร์เพื่อเก็บ Access Token (JWT) มีข้อเสียด้านความปลอดภัยเมื่อเทียบกับ `HttpOnly Cookie` อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'localStorage สามารถถูกอ่านได้โดย JavaScript ทุกตัวในหน้านั้น ทำให้หากเกิดช่องโหว่ XSS เพียงจุดเดียว Token จะถูกขโมยได้ทันที' },
        { key: 'B', text: 'localStorage หมดอายุเองทุก 5 นาที' },
        { key: 'C', text: 'localStorage ไม่สามารถเก็บข้อมูลสตริงได้' },
        { key: 'D', text: 'localStorage ส่งข้อมูลไปหา Google ทุกครั้ง' },
      ],
      correctAnswer: 'A',
      explanation: 'สคริปต์อันตรายจาก XSS สามารถสั่ง localStorage.getItem(\'token\') แล้วยิงออกไปหาเซิร์ฟเวอร์แฮกเกอร์ได้ง่าย ต่างจาก HttpOnly Cookie ที่ JS อ่านไม่ได้',
      order: 17,
    },
    {
      question: 'HTTP Status Code `502 Bad Gateway` และ `504 Gateway Timeout` มีความหมายอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '502 คือ Proxy/Reverse Proxy ได้รับคำตอบที่ผิดพลาดจากเซิร์ฟเวอร์หลังบ้าน ส่วน 504 คือรอคำตอบจากหลังบ้านนานจนหมดเวลา' },
        { key: 'B', text: '502 คือรหัสผ่านผิด ส่วน 504 คือบัญชีถูกแบน' },
        { key: 'C', text: '502 คือหน้าเว็บถูกลบ ส่วน 504 คือรูปภาพเสีย' },
        { key: 'D', text: 'เป็นโค้ดที่เกิดเฉพาะบนเครือข่าย 5G' },
      ],
      correctAnswer: 'A',
      explanation: '502/504 เป็น Server-side error มักเกิดขึ้นเมื่อ Nginx/Load Balancer ไม่สามารถติดต่อกับ Backend Service (Node.js/Python) ได้',
      order: 18,
    },
    {
      question: 'Header `Permissions-Policy` (เดิมคือ Feature-Policy) ใช้สำหรับควบคุมอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ควบคุมการเปิด/ปิดสิทธิ์การเข้าถึงฮาร์ดแวร์และฟีเจอร์ของเบราว์เซอร์ เช่น กล้อง (camera), ไมโครโฟน (microphone), พิกัด (geolocation)' },
        { key: 'B', text: 'กำหนดสิทธิ์ของระบบฐานข้อมูล' },
        { key: 'C', text: 'ตั้งค่าความเร็วของพัดลมซีพียู' },
        { key: 'D', text: 'จำกัดจำนวนการพิมพ์ข้อความ' },
      ],
      correctAnswer: 'A',
      explanation: 'Permissions-Policy ช่วยจำกัดไม่ให้สคริปต์บุคคลที่สามหรือ iframe แอบเปิดกล้อง ดักฟังไมค์ หรือขอพิกัด GPS ของผู้ใช้',
      order: 19,
    },
    {
      question: 'Header `Access-Control-Allow-Origin: *` มีความเสี่ยงอย่างไรหากใช้กับ API ที่ส่งข้อมูลส่วนตัวของผู้ใช้งาน?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เปิดโอกาสให้เว็บไซต์แปลกปลอมใดๆ ก็ตามสามารถเขียน JavaScript ส่งคำขอมาดึงข้อมูลตอบกลับจาก API นี้ได้' },
        { key: 'B', text: 'ทำให้ฐานข้อมูลลบตารางทิ้ง' },
        { key: 'C', text: 'ทำให้เบราว์เซอร์แสดงผลเป็นภาษาอื่น' },
        { key: 'D', text: 'ทำให้ขนาดไฟล์ดาวน์โหลดใหญ่ขึ้น' },
      ],
      correctAnswer: 'A',
      explanation: 'การใช้ Wildcard (*) บน Access-Control-Allow-Origin ควรใช้เฉพาะกับ Public API เท่านั้น หากเป็นข้อมูลส่วนบุคคลต้องระบุ Trusted Origin อย่างเจาะจง',
      order: 20,
    },
  ],
};
