import { QuizQuestion } from '@/types';

export const advancedQuizzesData: Record<string, Omit<QuizQuestion, 'id' | 'quizId'>[]> = {
  // ==================== LEVEL 3: ADVANCED ====================
  // 1. Buffer Overflows, Memory Layout & Shellcoding
  'lesson-a1-1': [
    {
      question: 'ในโครงสร้างหน่วยความจำของโปรเซส x86/x64 "Stack" และ "Heap" มีทิศทางการเจริญเติบโต (Growth Direction) อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Stack เติบโตจากแอดเดรสสูงลงสู่แอดเดรสต่ำ (High to Low Memory) ส่วน Heap เติบโตจากแอดเดรสต่ำขึ้นสู่แอดเดรสสูง (Low to High Memory)' },
        { key: 'B', text: 'Stack และ Heap เติบโตไปในทิศทางเดียวกันเสมอ' },
        { key: 'C', text: 'Stack เติบโตจากซ้ายไปขวา ส่วน Heap เติบโตเป็นวงกลม' },
        { key: 'D', text: 'Stack ไม่มีการขยายขนาด' },
      ],
      correctAnswer: 'A',
      explanation: 'Stack ขยายตัวลงล่าง (Decrementing SP) เพื่อเก็บ Local Variables และ Function Frames ขณะที่ Heap ขยายตัวขึ้นบน (Incrementing brk/mmap) สำหรับ Dynamic Allocation',
      order: 1,
    },
    {
      question: 'รีจิสเตอร์ใดในสถาปัตยกรรม x86 (32-bit) ที่ทำหน้าที่ชี้ไปยังคำสั่งถัดไปที่จะถูกประมวลผล (Instruction Pointer)?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'EIP (Extended Instruction Pointer) หรือ RIP ในสถาปัตยกรรม 64-bit' },
        { key: 'B', text: 'ESP (Stack Pointer)' },
        { key: 'C', text: 'EBP (Base Pointer)' },
        { key: 'D', text: 'EAX (Accumulator Register)' },
      ],
      correctAnswer: 'A',
      explanation: 'EIP/RIP ชี้ไปยังตำแหน่งคำสั่งถัดไปในโค้ด หากผู้โจมตีสามารถเขียนทับค่า Return Address บน Stack ให้ชี้ไปที่ EIP ที่ต้องการได้ ก็จะควบคุมทิศทางการทำงานของโปรแกรมได้',
      order: 2,
    },
    {
      question: 'ช่องโหว่ประเภท "Stack-based Buffer Overflow" มักเกิดจากการใช้ฟังก์ชันภาษา C/C++ ใดที่ไม่มีการตรวจสอบขอบเขตความยาวของบัฟเฟอร์ (Unbounded Copy)?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '`strcpy()`, `strcat()`, `gets()`, และ `sprintf()`' },
        { key: 'B', text: '`strncpy()`, `strncat()`, และ `snprintf()`' },
        { key: 'C', text: '`sizeof()`' },
        { key: 'D', text: '`strlen()`' },
      ],
      correctAnswer: 'A',
      explanation: 'ฟังก์ชันกลุ่มดั้งเดิมเช่น `strcpy(dest, src)` จะคัดลอกข้อมูลไปเรื่อยๆ จนกว่าจะเจอ Null Byte โดยไม่สนขนาดของ dest ทำให้เขียนล้นบัฟเฟอร์เข้าสู่ Saved Frame Pointer และ Return Address',
      order: 3,
    },
    {
      question: 'กลไกป้องกันหน่วยความจำแบบ "ASLR" (Address Space Layout Randomization) ทำงานอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'สุ่มตำแหน่ง Memory Addresses ของ Stack, Heap, และ Shared Libraries ทุกครั้งที่โปรแกรมเริ่มทำงาน ทำให้คาดเดาแอดเดรสของโค้ดได้ยาก' },
        { key: 'B', text: 'ลบหน่วยความจำที่ไม่ใช้งานทิ้ง' },
        { key: 'C', text: 'เพิ่มความเร็วในการคำนวณของซีพียู' },
        { key: 'D', text: 'เปลี่ยนรหัสผ่านผู้ใช้ทุก 1 นาที' },
      ],
      correctAnswer: 'A',
      explanation: 'ASLR สุ่ม Base Address ของโครงสร้างหน่วยความจำ ทำให้ผู้โจมตีไม่สามารถ Hardcode Memory Address ลงใน Payload ได้โดยตรง',
      order: 4,
    },
    {
      question: 'กลไกป้องกันแบบ "DEP / NX" (Data Execution Prevention / No-Execute) มีหน้าที่หลักเพื่ออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'กำหนดให้พื้นที่หน่วยความจำที่เขียนได้ (Writable) เช่น Stack และ Heap ไม่สามารถรันโค้ดคำสั่ง (Executable) ได้' },
        { key: 'B', text: 'ป้องกันไม่ให้โปรแกรมเปิดอ่านไฟล์' },
        { key: 'C', text: 'ลดความร้อนของชิปประมวลผล' },
        { key: 'D', text: 'บังคับให้ต่อสายดิน' },
      ],
      correctAnswer: 'A',
      explanation: 'W^X (Write XOR Execute) ป้องกันไม่ให้แฮกเกอร์วาง Shellcode บน Stack แล้วกระโดดไปสั่งรันได้โดยตรง หากพยายามรันจะเกิด Segmentation Fault ทันที',
      order: 5,
    },
    {
      question: 'กลไก "Stack Canary" (Stack Cookie) ทำงานอย่างไรในการป้องกัน Buffer Overflow?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'วางค่าสุ่มลับไว้หน้า Return Address บน Stack และตรวจสอบว่าค่ายังคงเดิมก่อนที่ฟังก์ชันจะ Return หรือไม่ หากเปลี่ยนไปโปรแกรมจะ Terminate ทันที' },
        { key: 'B', text: 'ส่งสัญญาณเสียงเตือนเมื่อพิมพ์เร็วเกินไป' },
        { key: 'C', text: 'บันทึกประวัติการใช้แป้นพิมพ์' },
        { key: 'D', text: 'เพิ่มขนาดของบัฟเฟอร์อัตโนมัติ' },
      ],
      correctAnswer: 'A',
      explanation: 'Stack Canary ถูกสร้างขึ้นสุ่มก่อน Return Address เมื่อเกิด Buffer Overflow ค่า Canary จะถูกเขียนทับก่อน คอมไพเลอร์จึงตรวจจับได้และหยุดการทำงานก่อนที่ EIP จะถูกควบคุม',
      order: 6,
    },
    {
      question: 'เมื่อเปิดใช้ DEP/NX ทำให้ไม่สามารถรัน Shellcode บน Stack ได้ ผู้โจมตีจึงนิยมใช้เทคนิคใดในการบายพาสกลไกนี้?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ROP (Return-Oriented Programming) โดยการร้อยเรียงคำสั่งย่อย (Gadgets) ที่มีอยู่เดิมใน Executable Code เพื่อสร้าง Logic ใหม่' },
        { key: 'B', text: 'การรีสตาร์ทเครื่องคอมพิวเตอร์' },
        { key: 'C', text: 'การเพิ่มขนาดไฟล์ Payload' },
        { key: 'D', text: 'การส่งคำขอผ่าน Wi-Fi' },
      ],
      correctAnswer: 'A',
      explanation: 'ROP ใช้ประโยชน์จากชุดคำสั่งสั้นๆ ที่ลงท้ายด้วยคำสั่ง `ret` ภายใน Binary หรือ libc เดิม (เรียกว่า Gadgets) มาร้อยเรียงกันเพื่อเรียกฟังก์ชันเช่น `system(\'/bin/sh\')`',
      order: 7,
    },
    {
      question: 'ในบริบทของ Shellcode ค่า "Bad Characters" (เช่น `\\x00`, `\\x0a`, `\\x0d`) ส่งผลกระทบอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ทำให้ฟังก์ชันจัดการสตริง (เช่น strcpy) ตีความว่าเป็นตัวจบสตริงหรือบรรทัดใหม่ ส่งผลให้ Shellcode ถูกตัดทอนและทำงานไม่สมบูรณ์' },
        { key: 'B', text: 'ทำให้หน้าจอแสดงผลเป็นภาษาอื่น' },
        { key: 'C', text: 'ทำให้พัดลมระบายความร้อนหมุนช้าลง' },
        { key: 'D', text: 'ไม่มีผลกระทบใดๆ' },
      ],
      correctAnswer: 'A',
      explanation: 'Null Byte (0x00) สิ้นสุดสตริงในภาษาซี ดังนั้น Shellcode จะต้องเขียนแบบเลี่ยง Null Byte (เช่น ใช้ `xor eax, eax` แทน `mov eax, 0`) เพื่อไม่ให้โดนตัด',
      order: 8,
    },
    {
      question: 'คำสั่ง NOP Sled (No-Operation Sled เช่น `\\x90` หลายๆ ตัวหน้า Shellcode) มีประโยชน์อย่างไรใน Classic Buffer Overflow?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'สร้างพื้นที่ลงจอด (Landing Pad) เพื่อให้ EIP สามารถกระโดดลงตรงตำแหน่งใดก็ได้ในแถบ NOP แล้วซีพียูจะเลื่อนไถลไปยัง Shellcode โดยอัตโนมัติ' },
        { key: 'B', text: 'ทำให้ขนาดไฟล์เล็กลง' },
        { key: 'C', text: 'เพิ่มความเร็วของ Shellcode' },
        { key: 'D', text: 'ลบมัลแวร์ในเครื่อง' },
      ],
      correctAnswer: 'A',
      explanation: 'NOP Sled ช่วยเพิ่มโอกาสสำเร็จเมื่อไม่ทราบตำแหน่งเริ่มต้นที่แน่นอนของ Shellcode ใน Stack โดยกระโดดไปลงตรงไหนของ NOP Sled ก็จะไหลไปรันโค้ดจริง',
      order: 9,
    },
    {
      question: 'ช่องโหว่ "Format String Vulnerability" เกิดจากการเขียนโค้ดลักษณะใดในภาษา C?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '`printf(user_input);` แทนที่จะเป็น `printf("%s", user_input);`' },
        { key: 'B', text: '`scanf("%d", &num);`' },
        { key: 'C', text: '`malloc(sizeof(int));`' },
        { key: 'D', text: '`free(ptr);`' },
      ],
      correctAnswer: 'A',
      explanation: 'หากส่ง Input เข้า printf ตรงๆ ผู้ใช้สามารถป้อน Format Specifiers เช่น `%x`, `%s` เพื่ออ่านข้อมูลบน Stack หรือ `%n` เพื่อเขียนค่าลงใน Memory Addresses ได้',
      order: 10,
    },
    {
      question: 'Format Specifier ใดในช่องโหว่ Format String ที่อนุญาตให้ผู้โจมตี "เขียนค่า (Write)" ลงในหน่วยความจำได้?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '`%n` (เขียนจำนวนตัวอักษรที่พิมพ์ออกมาแล้วลงในที่อยู่พอยน์เตอร์)' },
        { key: 'B', text: '`%x`' },
        { key: 'C', text: '`%p`' },
        { key: 'D', text: '`%s`' },
      ],
      correctAnswer: 'A',
      explanation: '`%n` เป็น Format Specifier ตัวเดียวที่ทำหน้าที่เขียนข้อมูล (Write) ไม่ใช่อ่าน ทำให้ผู้โจมตีสามารถเขียนทับ GOT Table หรือ Return Address ได้',
      order: 11,
    },
    {
      question: 'ช่องโหว่ "Use-After-Free" (UAF) บน Heap Memory เกิดขึ้นเมื่อใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'โปรแกรมยังคงพยายามเข้าถึงหรือเรียกใช้พอยน์เตอร์หน่วยความจำที่ถูกสั่ง `free()` คืนระบบไปแล้ว' },
        { key: 'B', text: 'การใช้โปรแกรมฟรีโดยไม่จ่ายเงิน' },
        { key: 'C', text: 'การลืมเปิดไฟร์วอลล์' },
        { key: 'D', text: 'การใช้ฮาร์ดดิสก์เก่า' },
      ],
      correctAnswer: 'A',
      explanation: 'เมื่อหน่วยความจำถูก free ไปแล้วแต่ยังมี Dangling Pointer อยู่ ผู้โจมตีสามารถ Allocate อ็อบเจกต์ใหม่เข้าไปทับตำแหน่งเดิมเพื่อควบคุม Function Pointer (vtable)',
      order: 12,
    },
    {
      question: 'เทคนิค "ret2libc" (Return-to-libc) มีแนวทางปฏิบัติอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เขียนทับ Return Address ให้ชี้ไปยังฟังก์ชัน `system()` ใน Standard C Library (libc) พร้อมส่งพารามิเตอร์ `/bin/sh` เพื่อเปิดเชลล์' },
        { key: 'B', text: 'การดาวน์โหลดไลบรารีใหม่จากอินเทอร์เน็ต' },
        { key: 'C', text: 'การลบไฟล์ libc.so ทิ้ง' },
        { key: 'D', text: 'การรีสตาร์ทเครื่องเซิร์ฟเวอร์' },
      ],
      correctAnswer: 'A',
      explanation: 'ret2libc ไม่จำเป็นต้องรันโค้ดบน Stack จึงบายพาส DEP/NX ได้ โดยอาศัยฟังก์ชันมาตรฐานที่มีอยู่แล้วใน libc',
      order: 13,
    },
    {
      question: 'กลไก "PIE" (Position Independent Executable) เมื่อใช้งานร่วมกับ ASLR จะมีผลอย่างไรต่อ Binary?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'โค้ดส่วนของโปรแกรมหลัก (.text segment) จะถูกโหลดในตำแหน่งแอดเดรสที่สุ่มใหม่ทุกครั้งเช่นเดียวกับ Libraries' },
        { key: 'B', text: 'ทำให้โปรแกรมกลายเป็นไฟล์รูปภาพ' },
        { key: 'C', text: 'ทำให้ไฟล์ Binary ทำงานได้เฉพาะบน ARM' },
        { key: 'D', text: 'ปิดการทำงานของ Stack' },
      ],
      correctAnswer: 'A',
      explanation: 'หากไม่มี PIE ส่วนโค้ดหลัก (.text) จะโหลดที่ Fixed Address (เช่น 0x08048000 หรือ 0x400000) ทำให้หา ROP Gadgets ได้ง่าย แต่ถ้าเปิด PIE แอดเดรสทั้งหมดจะถูกสุ่ม',
      order: 14,
    },
    {
      question: 'เครื่องมือ Debugger ใดที่นิยมใช้งานมากที่สุดสำหรับการวิเคราะห์ Binary Exploitation และ Reverse Engineering บน Linux?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'GDB (GNU Debugger) ร่วมกับปลั๊กอิน pwndbg หรือ GEF' },
        { key: 'B', text: 'MS Paint' },
        { key: 'C', text: 'Notepad++' },
        { key: 'D', text: 'Calculator' },
      ],
      correctAnswer: 'A',
      explanation: 'GDB พร้อม GEF/pwndbg มีฟังก์ชันแสดง Stack Context, Register States, ROP Gadget Search, และ Heap Chunks Inspection อย่างครบครัน',
      order: 15,
    },
    {
      question: 'ในสถาปัตยกรรม x86-64 (Linux System V AMD64 ABI) พารามิเตอร์ 3 ตัวแรกของฟังก์ชันจะถูกส่งผ่านทางรีจิสเตอร์ใดตามลำดับ?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'RDI, RSI, RDX' },
        { key: 'B', text: 'RAX, RBX, RCX' },
        { key: 'C', text: 'RSP, RBP, RIP' },
        { key: 'D', text: 'R8, R9, R10' },
      ],
      correctAnswer: 'A',
      explanation: '64-bit ABI ส่งพารามิเตอร์ผ่านรีจิสเตอร์: 1st=RDI, 2nd=RSI, 3rd=RDX, 4th=RCX, 5th=R8, 6th=R9 ต่างจาก 32-bit ที่ Push ลง Stack ทั้งหมด',
      order: 16,
    },
    {
      question: 'ช่องโหว่ "Double Free" บน Heap Memory นำไปสู่อันตรายด้านใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ทำให้โครงสร้างหน่วยความจำของ Heap Allocator (เช่น Fastbin/Tcache) เสียหาย เปิดช่องให้ Allocate ซ้ำในที่อยู่เดิม (Arbitrary Write)' },
        { key: 'B', text: 'ทำให้คอมพิวเตอร์ประหยัดแรมขึ้น 2 เท่า' },
        { key: 'C', text: 'ทำให้โปรแกรมแปลงร่างเป็นเว็บเซิร์ฟเวอร์' },
        { key: 'D', text: 'ไม่มีอันตรายใดๆ' },
      ],
      correctAnswer: 'A',
      explanation: 'การ free พอยน์เตอร์เดิม 2 ครั้งทำให้เกิด Loop ใน Free List ของ Heap ซึ่งสามารถนำไปสู่การควบคุม Memory Allocator เพื่อเขียนทับพอยน์เตอร์สำคัญ',
      order: 17,
    },
    {
      question: 'เทคนิค "GOT Overwrite" (Global Offset Table Overwrite) มีขั้นตอนการโจมตีอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เขียนทับแอดเดรสของฟังก์ชันไลบรารีในตาราง GOT (เช่น puts หรือ printf) ให้ชี้ไปยัง system() เพื่อให้เมื่อโปรแกรมเรียกใช้ฟังก์ชันเดิมจะกลายเป็นการเปิดเชลล์' },
        { key: 'B', text: 'การลบตารางฐานข้อมูล' },
        { key: 'C', text: 'การเปลี่ยนสีหน้าจอ' },
        { key: 'D', text: 'การแก้ไขไฟล์ .bashrc' },
      ],
      correctAnswer: 'A',
      explanation: 'GOT เป็นตาราง Resolve Dynamic Function แอดเดรส หากโปรแกรมไม่มีการเปิด Full RELRO ผู้โจมตีสามารถเขียนทับ Pointer ใน GOT เพื่อ Redirect Execution Flow ได้',
      order: 18,
    },
    {
      question: 'กลไกความปลอดภัยแบบ "Full RELRO" (Read-Only Relocations) ช่วยป้องกันการโจมตีแบบใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'บังคับให้ Resolve Dynamic Symbols ทั้งหมดตั้งแต่เริ่มโปรแกรม แล้วกำหนดให้ตาราง GOT กลายเป็น Read-Only เพื่อป้องกันการเขียนทับ GOT Overwrite' },
        { key: 'B', text: 'ป้องกันการพิมพ์ข้อความผิด' },
        { key: 'C', text: 'ป้องกันสายเคเบิลขาด' },
        { key: 'D', text: 'ปิดการทำงานของคีย์บอร์ด' },
      ],
      correctAnswer: 'A',
      explanation: 'Full RELRO ทำให้ตาราง GOT กลายเป็น Read-Only หลัง Binding เสร็จสิ้น สกัดกั้นเทคนิค GOT Overwrite ได้อย่างสมบูรณ์',
      order: 19,
    },
    {
      question: 'ไลบรารี Python ยอดนิยมที่ใช้สำหรับพัฒนา Exploit Scripts และสร้าง Payload สำหรับงาน Binary Exploitation (CTF/Pwn) คืออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Pwntools (`import pwn`)' },
        { key: 'B', text: 'Pandas' },
        { key: 'C', text: 'Matplotlib' },
        { key: 'D', text: 'Django' },
      ],
      correctAnswer: 'A',
      explanation: 'Pwntools เป็น Framework พัฒนา Exploit ชั้นนำ มีฟังก์ชันจัดการกระบวนการเชื่อมต่อ (remote/process), จัดการไบต์ (p32/p64), และสร้าง ROP Chain อัตโนมัติ',
      order: 20,
    },
  ],

  // 2. Active Directory Attacks, Kerberos & BloodHound
  'lesson-a1-2': [
    {
      question: 'ในโปรโตคอล Kerberos ชิ้นส่วนใดทำหน้าที่เป็น Authentication Center ในการออกตั๋ว TGT (Ticket Granting Ticket)?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'KDC (Key Distribution Center) ซึ่งรันอยู่บน Domain Controller' },
        { key: 'B', text: 'เครื่องพิมพ์เครือข่าย' },
        { key: 'C', text: 'เว็บเบราว์เซอร์ของลูกข่าย' },
        { key: 'D', text: 'เราเตอร์ Wi-Fi' },
      ],
      correctAnswer: 'A',
      explanation: 'KDC ประกอบด้วย Authentication Service (AS) ที่ออกตั๋ว TGT และ Ticket Granting Service (TGS) ที่ออกตั๋วบริการ (Service Tickets)',
      order: 1,
    },
    {
      question: 'การโจมตีแบบ "Pass-the-Hash" (PtH) บน Active Directory ทำงานได้เพราะคุณสมบัติใดของ NTLM?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'โปรโตคอล NTLM ใช้ Password Hash ในการสร้าง Challenge-Response โดยตรง จึงสามารถใช้ Hash แทนรหัสผ่านตัวจริงได้ทันที' },
        { key: 'B', text: 'NTLM มีการสุ่มรหัสผ่านใหม่ทุก 5 วินาที' },
        { key: 'C', text: 'NTLM บังคับให้ใช้ภาษาไทยเท่านั้น' },
        { key: 'D', text: 'NTLM ไม่มีการเข้ารหัสข้อมูล' },
      ],
      correctAnswer: 'A',
      explanation: 'NTLM Authentication ยอมรับ NTLM Hash ในการคำนวณการยืนยันตัวตน ผู้โจมตีจึงไม่จำเป็นต้องเสียเวลาแคร็ก Hash กลับมาเป็นรหัสผ่าน',
      order: 2,
    },
    {
      question: 'การโจมตีแบบ "Silver Ticket Attack" แตกต่างจาก "Golden Ticket Attack" อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Silver Ticket ปลอมแปลง Service Ticket (TGS) เฉพาะบริการนั้นๆ โดยใช้ Hash ของ Service Account โดยไม่ต้องติดต่อ KDC ส่วน Golden Ticket ปลอมแปลง TGT ด้วย krbtgt hash' },
        { key: 'B', text: 'Silver Ticket มีความร้ายแรงสูงกว่า Golden Ticket 10 เท่า' },
        { key: 'C', text: 'Silver Ticket ใช้ได้เฉพาะบนเครื่อง Linux' },
        { key: 'D', text: 'ไม่มีความแตกต่างกัน' },
      ],
      correctAnswer: 'A',
      explanation: 'Silver Ticket ปลอม TGS สำหรับบริการเฉพาะ (เช่น CIFS, MSSQL, HTTP) มีข้อดีคือเงียบและไม่ผ่าน DC แต่ Golden Ticket มีอำนาจครอบคลุมทั้งโดเมน',
      order: 3,
    },
    {
      question: 'เทคนิค "DCSync Attack" อาศัยสิทธิ์ใดใน Active Directory ในการจำลองตนเองเป็น Domain Controller เพื่อขอขโมย Password Hashes ทั้งหมด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'สิทธิ์ Directory Replication (เช่น `DS-Replication-Get-Changes` และ `DS-Replication-Get-Changes-All`)' },
        { key: 'B', text: 'สิทธิ์ Print Operators' },
        { key: 'C', text: 'สิทธิ์ Remote Desktop Users' },
        { key: 'D', text: 'สิทธิ์ Backup Operators' },
      ],
      correctAnswer: 'A',
      explanation: 'DCSync ใช้ Directory Replication Service (DRS) Remote Protocol เพื่อสั่งจำลองข้อมูลและดึง NTLM Hash ของบัญชีทั้งหมด (รวม krbtgt) ออกมาโดยไม่ต้องรันโค้ดบน DC ตรงๆ',
      order: 4,
    },
    {
      question: 'เครื่องมือ "Sharphound" มีหน้าที่อะไรในกระบวนการทำงานร่วมกับ BloodHound?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เป็นตัวเก็บรวบรวมข้อมูล (Data Ingestor/Collector) สแกนสอบถามข้อมูล AD (Users, Groups, Sessions, ACLs, Trusts) แล้วส่งออกเป็น JSON' },
        { key: 'B', text: 'เป็นเครื่องมือลบไวรัส' },
        { key: 'C', text: 'เป็นโปรแกรมพิมพ์งาน' },
        { key: 'D', text: 'เป็นตัวกระจายสัญญาณอินเทอร์เน็ต' },
      ],
      correctAnswer: 'A',
      explanation: 'SharpHound รันบนเครื่องในโดเมนเพื่อดึงข้อมูลสิทธิ์และ Active Sessions ส่งต่อให้ BloodHound นำไปพล็อตแผนภูมิกราฟ (Neo4j)',
      order: 5,
    },
    {
      question: 'การโจมตี "NTLM Relay Attack" สามารถถูกป้องกันได้อย่างมีประสิทธิภาพสูงสุดด้วยมาตรการใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เปิดใช้งาน SMB Signing (บังคับเซ็นชื่อแพ็กเกจ SMB) และ LDAP Signing / Channel Binding' },
        { key: 'B', text: 'การเพิ่มความเร็วอินเทอร์เน็ต' },
        { key: 'C', text: 'การปิดหน้าจอคอมพิวเตอร์เมื่อไม่ได้ใช้งาน' },
        { key: 'D', text: 'การใช้รหัสผ่านที่มีความยาว 8 หลัก' },
      ],
      correctAnswer: 'A',
      explanation: 'SMB Signing ป้องกันไม่ให้ผู้โจมตีตรงกลาง (Man-in-the-Middle) นำ NTLM Authentication Handshake ของเหยื่อไปส่งต่อ (Relay) ให้กับเซิร์ฟเวอร์ปลายทางอื่น',
      order: 6,
    },
    {
      question: 'เทคนิค "Kerberos Unconstrained Delegation" มีความเสี่ยงระดับสูงอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เซิร์ฟเวอร์ที่เปิด Unconstrained Delegation จะเก็บตั๋ว TGT ของผู้ใช้ทุกคนที่เข้ามาเชื่อมต่อไว้ในหน่วยความจำ หากเซิร์ฟเวอร์นี้ถูกเจาะ แฮกเกอร์จะขโมย TGT ของ Domain Admin ได้ทันที' },
        { key: 'B', text: 'ทำให้ความเร็วของโดเมนลดลง 50%' },
        { key: 'C', text: 'ทำให้บัญชีผู้ใช้ถูกลบอัตโนมัติ' },
        { key: 'D', text: 'ไม่มีความเสี่ยงใดๆ' },
      ],
      correctAnswer: 'A',
      explanation: 'Unconstrained Delegation ส่งตั๋ว TGT ไปเก็บใน LSASS ของเซิร์ฟเวอร์เป้าหมาย ทำให้แฮกเกอร์ที่ยึดเครื่องนั้นได้สามารถดึงตั๋ว TGT ของเหยื่อไปสวมรอยต่อได้ทันที',
      order: 7,
    },
    {
      question: 'ช่องโหว่ "AD CS (Active Directory Certificate Services) ESC1" เกิดจากสาเหตุใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Certificate Template อนุญาตให้ผู้ใช้ทั่วไปขอใบรับรองสำหรับ Client Authentication และเปิด Flag `ENROLLEE_SUPPLIES_SUBJECT` (อนุญาตให้ผู้ขอระบุชื่อ SAN เป็น Domain Admin ได้)' },
        { key: 'B', text: 'การลืมใส่รหัสผ่านในใบรับรอง' },
        { key: 'C', text: 'การใช้ใบรับรองที่มีอายุเกิน 100 ปี' },
        { key: 'D', text: 'การติดตั้ง Certificate บนเครื่อง Linux' },
      ],
      correctAnswer: 'A',
      explanation: 'ESC1 อนุญาตให้ User ปกติขอใบรับรองโดยปลอม Subject Alternative Name (SAN) เป็น Administrator แล้วนำใบรับรองนั้นไปยืนยันตัวตน (PKINIT) เพื่อยึดทั้งโดเมน',
      order: 8,
    },
    {
      question: 'เครื่องมือ "Certipy" หรือ "Certify" นิยมถูกนำมาใช้ในกิจกรรมใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ตรวจสอบ ค้นหา และหาผลประโยชน์จากช่องโหว่การตั้งค่าผิดพลาดใน Active Directory Certificate Services (AD CS Abuse / Misconfigurations)' },
        { key: 'B', text: 'ออกแบบและพิมพ์ใบประกาศนียบัตร' },
        { key: 'C', text: 'สแกนไวรัสในสมาร์ทโฟน' },
        { key: 'D', text: 'ตัดต่อเสียงเพลง' },
      ],
      correctAnswer: 'A',
      explanation: 'Certipy เป็นเครื่องมือยอดนิยมสำหรับตรวจสอบและ Exploit ช่องโหว่ AD CS (ESC1-ESC13) เพื่อยกระดับสิทธิ์เป็น Domain Admin',
      order: 9,
    },
    {
      question: 'การโจมตีแบบ "LLMNR / NBT-NS Poisoning" (เช่น ใช้เครื่องมือ Responder) มักถูกนำมาใช้ทำอะไรในเครือข่ายภายใน?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ดักจับคำขอค้นหาชื่อเครื่องที่พิมพ์ผิดในวงแลน แล้วตอบกลับด้วย IP ตนเองเพื่อล่อให้เหยื่อส่ง NetNTLMv2 Hash มายืนยันตัวตน' },
        { key: 'B', text: 'ตัดสายสัญญาณอินเทอร์เน็ต' },
        { key: 'C', text: 'ลบไฟล์ภาพในเครื่องเหยื่อ' },
        { key: 'D', text: 'ปิดการทำงานของเราเตอร์' },
      ],
      correctAnswer: 'A',
      explanation: 'Responder ดักฟัง Broadcast ของ LLMNR/NBT-NS และหลอกว่าเป็นโฮสต์นั้น ทำให้เหยื่อส่ง NTLM Hash มาให้เพื่อทำการแคร็กหรือ Relay',
      order: 10,
    },
    {
      question: 'แนวทาง "Protected Users Group" บน Active Directory ช่วยเสริมความปลอดภัยอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ปิดการใช้ NTLM Authentication, ปิดการแคชรหัสผ่านในหน่วยความจำ (WDigest/CredSSP), และจำกัดอายุของตั๋ว Kerberos' },
        { key: 'B', text: 'ห้ามไม่ให้ผู้ใช้เปิดดูเว็บไซต์' },
        { key: 'C', text: 'ทำให้ผู้ใช้ทุกคนเป็น Administrator' },
        { key: 'D', text: 'ลบชื่อบัญชีออกจากระบบ' },
      ],
      correctAnswer: 'A',
      explanation: 'Protected Users Security Group บังคับใช้กลไกความปลอดภัยขั้นสูงสุดเพื่อป้องกันการขโมย Credential ผ่าน Mimikatz และ NTLM attacks',
      order: 11,
    },
    {
      question: 'คำว่า "GPO Abuse" (Group Policy Object Abuse) หมายถึงเทคนิคใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การที่ผู้โจมตีมีสิทธิ์เขียน (Write/Edit) บน GPO แล้วแอบแก้ไขนโยบายเพื่อสั่งรันสคริปต์อันตราย หรือเพิ่มสิทธิ์ Local Admin ให้ตนเองบนทุกเครื่องในโดเมน' },
        { key: 'B', text: 'การลบรูปภาพบนเดสก์ท็อป' },
        { key: 'C', text: 'การเปลี่ยนเวลาของนาฬิกา' },
        { key: 'D', text: 'การเปิดเพลงผ่านเครือข่าย' },
      ],
      correctAnswer: 'A',
      explanation: 'GPO ถูกนำไปใช้งานกับเครื่องลูกข่ายทั้งหมดในโดเมน การมีสิทธิ์แก้ไข GPO ช่วยให้แฮกเกอร์แพร่กระจายมัลแวร์ไปทั่วองค์กรได้ในครั้งเดียว',
      order: 12,
    },
    {
      question: 'เมื่อผู้โจมตีได้สิทธิ์ "GenericAll" หรือ "WriteDacl" บน Object ใน Active Directory (พบผ่าน BloodHound) มีความหมายว่าอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ผู้โจมตีมีสิทธิ์ควบคุม Object นั้นอย่างสมบูรณ์ เช่น สามารถสั่ง Reset Password ของ User นั้น หรือเพิ่มตนเองเข้า Group นั้นได้ทันที' },
        { key: 'B', text: 'ผู้โจมตีอ่านไฟล์ได้เฉพาะข้อความธรรมดา' },
        { key: 'C', text: 'ผู้โจมตีไม่มีสิทธิ์ใดๆ เลย' },
        { key: 'D', text: 'ระบบกำลังปิดปรับปรุง' },
      ],
      correctAnswer: 'A',
      explanation: 'GenericAll คือ Full Control เหนือ Object นั้น ทำให้สามารถแก้ไข DACL, ปลดล็อค, หรือรีเซ็ตรหัสผ่านของเป้าหมายได้ตามต้องการ',
      order: 13,
    },
    {
      question: 'การรีเซ็ตรหัสผ่านบัญชี `krbtgt` เพื่อลบล้าง Golden Ticket ต้องทำอย่างไรจึงจะปลอดภัยสมบูรณ์?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ต้องรีเซ็ตรหัสผ่าน krbtgt จำนวน 2 ครั้ง โดยเว้นระยะห่างระหว่างครั้งให้เวลากระจายข้อมูล (Replication) ข้าม DC ครบถ้วน เพื่อล้างประวัติ Hash เก่า' },
        { key: 'B', text: 'รีเซ็ตเพียงครั้งเดียวก็เพียงพอ' },
        { key: 'C', text: 'ลบบัญชี krbtgt ทิ้งถาวร' },
        { key: 'D', text: 'เปลี่ยนชื่อบัญชีเป็นชื่ออื่น' },
      ],
      correctAnswer: 'A',
      explanation: 'AD เก็บ Password History ของ krbtgt ไว้ 2 รุ่น การเปลี่ยน 2 ครั้งจะทำให้ตั๋ว TGT ปลอมที่สร้างจาก Hash เดิมใช้การไม่ได้อย่างสมบูรณ์',
      order: 14,
    },
    {
      question: 'โปรโตคอล "LAPS" (Local Administrator Password Solution) ของ Microsoft มีประโยชน์หลักอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'สุ่มรหัสผ่าน Local Administrator ของแต่ละเครื่องให้ไม่ซ้ำกัน และหมุนเวียนรหัสผ่านอัตโนมัติพร้อมเก็บไว้อย่างปลอดภัยใน AD' },
        { key: 'B', text: 'ตั้งรหัสผ่านทุกเครื่องให้เป็นค่าเดียวกัน' },
        { key: 'C', text: 'ลบบัญชี Administrator ในเครื่องทิ้ง' },
        { key: 'D', text: 'เพิ่มความเร็วการเปิดเครื่อง Windows' },
      ],
      correctAnswer: 'A',
      explanation: 'LAPS สกัดกั้น Lateral Movement แบบ Pass-the-Hash ข้ามเครื่องลูกข่าย เพราะแต่ละเครื่องจะมีรหัสผ่าน Local Admin ที่สุ่มแตกต่างกันโดยสิ้นเชิง',
      order: 15,
    },
    {
      question: 'การโจมตี "Shadow Credentials" (msDS-KeyCredentialLink Abuse) คืออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การเพิ่ม Public Key ของผู้โจมตีลงในแอตทริบิวต์ `msDS-KeyCredentialLink` ของเหยื่อ เพื่อขอตั๋ว TGT ยืนยันตัวตนผ่าน PKINIT (Windows Hello for Business mechanism)' },
        { key: 'B', text: 'การซ่อนรหัสผ่านไว้ในเงา' },
        { key: 'C', text: 'การปรับความสว่างของหน้าจอ' },
        { key: 'D', text: 'การถอดปลั๊ก Domain Controller' },
      ],
      correctAnswer: 'A',
      explanation: 'หากมีสิทธิ์ WriteProperty บน User/Computer เป้าหมาย ผู้โจมตีสามารถผูก Key Credential เพื่อขอ TGT ในนามเป้าหมายได้โดยไม่ต้องเปลี่ยนรหัสผ่านเดิม',
      order: 16,
    },
    {
      question: 'ฟีเจอร์ "Resource-Based Constrained Delegation" (RBCD) สามารถถูกใช้ในการโจมตีได้อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'หากผู้โจมตีมีสิทธิ์เขียนแอตทริบิวต์ `msDS-AllowedToActOnBehalfOfOtherIdentity` บนเครื่องเป้าหมาย จะสามารถสร้าง Fake Computer Account มา Impersonate สิทธิ์ Admin บนเครื่องนั้นได้' },
        { key: 'B', text: 'ทำให้เครื่องเป้าหมายไม่สามารถเปิดติดได้' },
        { key: 'C', text: 'ทำให้ฮาร์ดดิสก์เกิด Bad Sector' },
        { key: 'D', text: 'ลบระบบ Active Directory ทั้งหมด' },
      ],
      correctAnswer: 'A',
      explanation: 'RBCD อนุญาตให้ Resource กำหนดเองว่าใครสามารถ Delegate สิทธิ์มาหาตนได้ การเขียนค่านี้ช่วยให้ผู้โจมตียึดเครื่องเป้าหมายได้อย่างแนบเนียน',
      order: 17,
    },
    {
      question: 'เครื่องมือ "rubeus" นิยมถูกนำมาใช้ในงานด้านความมั่นคงปลอดภัยเพื่ออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ชุดเครื่องมือ C# สำหรับปฏิสัมพันธ์และโจมตีระบบ Kerberos บน Windows (เช่น Kerberoasting, AS-REP roasting, Ticket extraction, S4U, Harvesting)' },
        { key: 'B', text: 'โปรแกรมแปลภาษา' },
        { key: 'C', text: 'ระบบคิดเงินหน้าร้าน' },
        { key: 'D', text: 'เกมต่อสู้' },
      ],
      correctAnswer: 'A',
      explanation: 'Rubeus เป็นเครื่องมือระดับแนวหน้าสำหรับการทดสอบความปลอดภัยของโปรโตคอล Kerberos ในทุกแง่มุม',
      order: 18,
    },
    {
      question: 'การตรวจสอบ "Domain Trust Relationships" มีความสำคัญอย่างไรในการประเมินความปลอดภัย?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ช่วยให้ผู้โจมตีที่ยึด Child Domain สามารถข้ามไปยัง Parent Domain หรือข้าม Forest ไปยังบริษัทในเครือผ่านการใช้ SID History (SID Filtering bypass)' },
        { key: 'B', text: 'ช่วยลดค่าใช้จ่ายการดูแลระบบ' },
        { key: 'C', text: 'ช่วยเพิ่มความละเอียดหน้าจอ' },
        { key: 'D', text: 'ทำให้ไม่ต้องใช้สายแลน' },
      ],
      correctAnswer: 'A',
      explanation: 'Trust Relationships ช่วยให้เกิดการเคลื่อนที่ข้าม Domain Forest หากขาดการตั้งค่า SID Filtering ที่เข้มงวด',
      order: 19,
    },
    {
      question: 'คำสั่ง PowerShell `Get-ADUser -Filter * -Properties AdminCount | Where-Object {$_.AdminCount -eq 1}` มีจุดประสงค์เพื่ออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ค้นหาบัญชีผู้ใช้ที่เคยเป็นสมาชิกของกลุ่มสิทธิ์สูง (Protected Groups เช่น Domain Admins, Enterprise Admins) ที่ถูกปกป้องโดย SDProp' },
        { key: 'B', text: 'นับจำนวนคอมพิวเตอร์ในออฟฟิศ' },
        { key: 'C', text: 'ลบบัญชีผู้ใช้ที่ไม่มี Admin' },
        { key: 'D', text: 'ตั้งเวลารีบูตเครื่อง' },
      ],
      correctAnswer: 'A',
      explanation: 'AdminCount=1 บ่งชี้ว่าผู้ใช้นั้นมีหรือเคยมีสิทธิ์ระดับสูง ซึ่งเป็นเป้าหมายที่มีมูลค่าสูง (High-value Targets) ของผู้โจมตี',
      order: 20,
    },
  ],

  // 3. Threat Hunting, SIEM (Splunk/Elastic), YARA & Sigma Rules
  'lesson-a2-1': [
    {
      question: 'แนวคิด "Threat Hunting" (การล่าภัยคุกคาม) มีความแตกต่างจากการเฝ้าระวังความปลอดภัยทั่วไป (Security Monitoring) อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Threat Hunting เป็นกระบวนการเชิงรุก (Proactive) โดยตั้งสมมติฐานว่าระบบถูกบุกรุกแล้ว และออกค้นหาภัยคุกคามที่หลบเลี่ยงระบบตรวจจับอัตโนมัติ' },
        { key: 'B', text: 'Threat Hunting คือการนั่งรอให้ระบบแจ้งเตือน Alert ดังขึ้นแล้วค่อยเข้าไปดู' },
        { key: 'C', text: 'Threat Hunting ทำงานเฉพาะเมื่อระบบล่ม' },
        { key: 'D', text: 'Threat Hunting ทำหน้าที่เฉพาะการลบไฟล์เอกสาร' },
      ],
      correctAnswer: 'A',
      explanation: 'Threat Hunting เริ่มต้นด้วยสมมติฐาน (Hypothesis-driven) และใช้วิธีวิเคราะห์ Telemetry เชิงลึกเพื่อตรวจจับ Advanced Persistent Threats (APTs) ที่ไม่ทำให้เกิด Signature Alert',
      order: 1,
    },
    {
      question: 'โมเดล "Pyramid of Pain" โดย David Bianco จัดให้สิ่งบ่งชี้ภัยคุกคาม (IoC) ชนิดใด "สร้างความเจ็บปวดและยากที่สุดแก่ผู้โจมตี" ในการเปลี่ยนแปลงหลบเลี่ยง?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'TTPs (Tactics, Techniques, and Procedures - ยุทธวิธีและรูปแบบพฤติกรรม)' },
        { key: 'B', text: 'Hash Values (เช่น SHA-256)' },
        { key: 'C', text: 'IP Addresses' },
        { key: 'D', text: 'Domain Names' },
      ],
      correctAnswer: 'A',
      explanation: 'Hash, IP, Domain สามารถเปลี่ยนได้ง่ายเพียงเสี้ยววินาที แต่ TTPs คือพฤติกรรมและกระบวนการทำงานหลักของผู้โจมตี หากเราตรวจจับที่ระดับ TTPs ได้ ผู้โจมตีจะต้องคิดค้นเทคนิคใหม่ทั้งหมด',
      order: 2,
    },
    {
      question: 'ระบบ "SIEM" (Security Information and Event Management เช่น Splunk, Elastic Security) มีหน้าที่หลักคืออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'รวบรวม, จัดหมวดหมู่, ทำ Correlation, ค้นหา และวิเคราะห์ Log จากอุปกรณ์และระบบต่างๆ ทั่วทั้งองค์กรแบบรวมศูนย์เพื่อตรวจจับภัยคุกคาม' },
        { key: 'B', text: 'เป็นเครื่องมือตัดต่อรูปภาพ' },
        { key: 'C', text: 'เป็นระบบควบคุมสัญญาณไฟจราจร' },
        { key: 'D', text: 'เป็นโปรแกรมเล่นเกมสามมิติ' },
      ],
      correctAnswer: 'A',
      explanation: 'SIEM รวม Log จาก Servers, Firewalls, Endpoints, Cloud เข้าด้วยกันเพื่อให้ทีม SOC สามารถตรวจจับและตอบสนองต่อเหตุการณ์ผิดปกติได้อย่างทันท่วงที',
      order: 3,
    },
    {
      question: 'กฎ "YARA Rule" ถูกออกแบบมาเพื่อวัตถุประสงค์หลักใดในวงการความมั่นคงปลอดภัย?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ตรวจจับและจำแนกหมวดหมู่ไฟล์มัลแวร์ (Malware Identification) ตามรูปแบบสตริง (Strings), ไบต์ (Byte patterns), และเงื่อนไขตรรกะ (Conditions)' },
        { key: 'B', text: 'กำหนดความเร็วในการดาวน์โหลดไฟล์' },
        { key: 'C', text: 'แปลงไฟล์ PDF เป็น Word' },
        { key: 'D', text: 'คำนวณภาษีประจำปี' },
      ],
      correctAnswer: 'A',
      explanation: 'YARA เปรียบเสมือน Pattern Matching สำหรับไฟล์ไบนารีและมัลแวร์ ช่วยให้นักวิเคราะห์เขียน Rule เพื่อตรวจจับตระกูลมัลแวร์ได้อย่างแม่นยำ',
      order: 4,
    },
    {
      question: 'กฎ "Sigma Rule" มีจุดเด่นสำคัญอย่างไรในระบบ Threat Detection?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เป็นมาตรฐานรูปแบบสากล (Generic Signature Format ในรูปแบบ YAML) ที่สามารถแปลง (Convert) ไปเป็น Query ของ SIEM ใดๆ ก็ได้ (Splunk, Elastic, QRadar, Sentinel)' },
        { key: 'B', text: 'ทำงานได้เฉพาะบนเครื่อง Mac เท่านั้น' },
        { key: 'C', text: 'ใช้สำหรับลบไฟล์ Log อัตโนมัติ' },
        { key: 'D', text: 'เป็นภาษาเขียนเกม' },
      ],
      correctAnswer: 'A',
      explanation: 'Sigma ทำหน้าที่เป็น "YARA for Log Files" ทำให้นักวิจัยสามารถแชร์ Detection Logic ร่วมกันได้โดยไม่ต้องขึ้นกับ SIEM ยี่ห้อใดยี่ห้อหนึ่ง',
      order: 5,
    },
    {
      question: 'ในแบบจำลอง MITRE ATT&CK Framework หมวดหมู่ "Tactic" และ "Technique" มีความสัมพันธ์กันอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Tactic คือ "เป้าหมาย" ของผู้โจมตี (Why - เช่น Initial Access, Persistence) ส่วน Technique คือ "วิธีการ" ที่ใช้เพื่อให้บรรลุเป้าหมายนั้น (How - เช่น Phishing, Scheduled Task)' },
        { key: 'B', text: 'Tactic คือชื่อไวรัส ส่วน Technique คือชื่อโปรแกรม Antivirus' },
        { key: 'C', text: 'ทั้งสองคำมีความหมายเหมือนกัน' },
        { key: 'D', text: 'Tactic ใช้กับซอฟต์แวร์ ส่วน Technique ใช้กับฮาร์ดแวร์' },
      ],
      correctAnswer: 'A',
      explanation: 'MITRE ATT&CK จัดโครงสร้าง Tactics เป็นคอลัมน์เป้าหมาย และ Techniques เป็นแถววิธีการปฏิบัติที่ผู้โจมตีใช้จริงในโลกไซเบอร์',
      order: 6,
    },
    {
      question: 'การตรวจจับภัยคุกคามแบบ "Living off the Land" (LotL / LOLBins) หมายถึงการตรวจจับพฤติกรรมใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การที่ผู้โจมตีใช้เครื่องมือและโปรแกรมมาตรฐานที่ติดมากับระบบปฏิบัติการ (เช่น PowerShell, certutil, wmic, mshta, bitsadmin) ในการทำกิจกรรมอันตรายเพื่อหลบเลี่ยง Antivirus' },
        { key: 'B', text: 'การโจมตีศูนย์ข้อมูลกลางป่า' },
        { key: 'C', text: 'การใช้อุปกรณ์พลังงานแสงอาทิตย์' },
        { key: 'D', text: 'การขโมยสายไฟ' },
      ],
      correctAnswer: 'A',
      explanation: 'LOLBins ไม่ต้องดาวน์โหลดไฟล์แปลกปลอมลงเครื่อง แต่ใช้ Binary ที่ได้รับความไว้วางใจของ Windows/Linux ในการดาวน์โหลดและรัน Payload',
      order: 7,
    },
    {
      question: 'คำสั่ง Splunk SPL (Search Processing Language) ข้อใดใช้ค้นหา IP ที่มียอดล็อกอินล้มเหลวมากที่สุด 10 อันดับแรก?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '`index=security EventCode=4625 | stats count by src_ip | sort - count | head 10`' },
        { key: 'B', text: '`search all logs in computer`' },
        { key: 'C', text: '`delete index=security`' },
        { key: 'D', text: '`show top 10 files`' },
      ],
      correctAnswer: 'A',
      explanation: 'SPL ใช้ Pipeline ประมวลผล: ดึง Event 4625 -> นับจำนวนตาม src_ip -> เรียงลำดับจากมากไปน้อย -> ดึง 10 อันดับแรก',
      order: 8,
    },
    {
      question: 'คำว่า "IoC" (Indicators of Compromise) และ "IoA" (Indicators of Attack) มีความแตกต่างกันอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'IoC เป็นหลักฐานร่องรอยหลังการบุกรุกเกิดขึ้นแล้ว (Forensic Artifacts เช่น File Hash, IP) ส่วน IoA เน้นตรวจจับพฤติกรรมและความตั้งใจในขณะที่การโจมตีกำลังดำเนินอยู่' },
        { key: 'B', text: 'IoC ใช้สำหรับระบบ Mac ส่วน IoA ใช้สำหรับ Windows' },
        { key: 'C', text: 'ไม่มีความแตกต่างกัน' },
        { key: 'D', text: 'IoC เป็นโปรแกรมฟรี ส่วน IoA ต้องเสียเงิน' },
      ],
      correctAnswer: 'A',
      explanation: 'IoC ตอบคำถาม "อะไรถูกโจมตีไปแล้ว" ส่วน IoA ตอบคำถาม "ผู้โจมตีกำลังพยายามทำอะไรอยู่ในตอนนี้" (Behavioral analysis)',
      order: 9,
    },
    {
      question: 'ในการเขียน YARA Rule ส่วนประกอบหลัก 3 ส่วนในโครงสร้าง Rule คืออะไรตามลำดับ?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'meta (ข้อมูลอธิบาย), strings (รูปแบบสตริง/ไบต์ที่ต้องการค้นหา), condition (เงื่อนไขตรรกะในการ Match)' },
        { key: 'B', text: 'header, body, footer' },
        { key: 'C', text: 'start, process, stop' },
        { key: 'D', text: 'input, output, error' },
      ],
      correctAnswer: 'A',
      explanation: 'โครงสร้างมาตรฐานของ YARA: `rule Example { meta: ... strings: $a = "bad" condition: $a }`',
      order: 10,
    },
    {
      question: 'การตรวจจับพฤติกรรม "Beaconing" ของ Command and Control (C2) ในเครือข่าย อาศัยการวิเคราะห์ข้อมูลลักษณะใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การเชื่อมต่อขาออกไปยังโดเมนหรือ IP ภายนอกด้วยช่วงเวลาที่สม่ำเสมอ (Periodic Interval / Heartbeat) หรือมีค่า Jitter สม่ำเสมอ' },
        { key: 'B', text: 'การส่งข้อความผ่าน SMS' },
        { key: 'C', text: 'การพิมพ์งานจำนวนมาก' },
        { key: 'D', text: 'การเปิดไฟล์วิดีโอ' },
      ],
      correctAnswer: 'A',
      explanation: 'มัลแวร์ C2 ต้องส่งสัญญาณกลับไปถามคำสั่งเป็นระยะ การวิเคราะห์ Periodic Network Connections และ Data Transfer Size ช่วยตรวจจับ Beaconing ได้อย่างแม่นยำ',
      order: 11,
    },
    {
      question: 'ระบบ "SOAR" (Security Orchestration, Automation, and Response) ช่วยยกระดับการทำงานของ SOC อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ทำงานร่วมกับ SIEM เพื่อรัน Playbook อัตโนมัติ (เช่น ตัดการเชื่อมต่อเครื่องติดมัลแวร์, บล็อก IP บนไฟร์วอลล์, รีเซ็ตรหัสผ่าน) โดยไม่ต้องรอคนกด' },
        { key: 'B', text: 'ช่วยพิมพ์รายงานเป็นภาษาไทย' },
        { key: 'C', text: 'ปิดไฟห้องเซิร์ฟเวอร์อัตโนมัติ' },
        { key: 'D', text: 'ดาวน์โหลดคลิปวิดีโอ' },
      ],
      correctAnswer: 'A',
      explanation: 'SOAR ช่วยลดเวลา Mean Time to Respond (MTTR) โดยการเชื่อมต่อระบบต่างๆ เข้าด้วยกันและสั่งการตอบสนองตาม Playbook โดยอัตโนมัติ',
      order: 12,
    },
    {
      question: 'พฤติกรรม Process Injection เช่น "Process Hollowing" หรือ "DLL Injection" มีเป้าหมายเพื่ออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'แอบแทรกโค้ดมัลแวร์เข้าไปทำงานภายในหน่วยความจำของ Process ที่ถูกต้องตามกฎหมาย (เช่น svchost.exe หรือ explorer.exe) เพื่อพรางตัวจากการตรวจสอบ' },
        { key: 'B', text: 'เพิ่มความเร็วในการรันโปรแกรม' },
        { key: 'C', text: 'ลดการใช้แบตเตอรี่' },
        { key: 'D', text: 'ปิดโปรแกรมที่ไม่ใช้งาน' },
      ],
      correctAnswer: 'A',
      explanation: 'Process Injection ช่วยให้โค้ดอันตรายรันภายใต้ชื่อโปรแกรมที่น่าเชื่อถือของระบบ หลอกล่อ Task Manager และระบบตรวจจับพฤติกรรมพื้นฐาน',
      order: 13,
    },
    {
      question: 'ใน Elastic Security (ELK Stack) ภาษา Query ใดที่ถูกนำมาใช้สำหรับการตรวจจับพฤติกรรม Threat Detection เชิงลำดับ (Sequencing/Correlation)?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'EQL (Event Query Language)' },
        { key: 'B', text: 'HTML' },
        { key: 'C', text: 'CSS' },
        { key: 'D', text: 'Markdown' },
      ],
      correctAnswer: 'A',
      explanation: 'EQL ออกแบบมาเพื่องานด้าน Security Telemetry โดยเฉพาะ รองรับการ Match เหตุการณ์ที่เกิดขึ้นตามลำดับเวลา (Sequence: Event A followed by Event B)',
      order: 14,
    },
    {
      question: 'เมื่อพบคำสั่ง `powershell.exe -enc <Base64String>` หรือ `-w hidden -nop` ใน Log พฤติกรรมนี้บ่งชี้ถึงอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ความพยายามซ่อนหน้าต่างและรันสคริปต์ที่เข้ารหัสพรางตา (Obfuscated Encoded Command) ซึ่งเป็นพฤติกรรมต้องสงสัยของมัลแวร์หรือแฮกเกอร์' },
        { key: 'B', text: 'การอัปเดตระบบตามปกติของ Microsoft' },
        { key: 'C', text: 'การเล่นเกมออนไลน์' },
        { key: 'D', text: 'การบันทึกเสียง' },
      ],
      correctAnswer: 'A',
      explanation: 'พารามิเตอร์ `-EncodedCommand` (-enc) และ `-WindowStyle hidden` มักถูกใช้ในสเตจแรกของการโจมตีเพื่อรัน Payload โดยไม่ให้ผู้ใช้เห็นหน้าต่างคอนโซล',
      order: 15,
    },
    {
      question: 'การตรวจจับ "Password Spraying" ในระบบ SIEM สามารถเขียน Correlation Rule ได้อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ตรวจจับเหตุการณ์ Logon Failure (Event 4625) ที่เกิดจาก IP ต้นทางเดียวกัน ไปยังบัญชีผู้ใช้ที่แตกต่างกันจำนวนมากในเวลาสั้นๆ โดยใช้รหัสผ่านเพียงไม่กี่ชุด' },
        { key: 'B', text: 'ตรวจจับการเปลี่ยนภาพพื้นหลัง' },
        { key: 'C', text: 'ตรวจจับการเสียบแฟลชไดรฟ์' },
        { key: 'D', text: 'ตรวจจับการเปิดโปรแกรมเครื่องคิดเลข' },
      ],
      correctAnswer: 'A',
      explanation: 'Password Spraying พยายามสุ่มรหัสผ่านยอดนิยม (เช่น Password123) ใส่ผู้ใช้ทุกคนเพื่อเลี่ยงการเกิด Account Lockout กฎ SIEM ต้องกรุ๊ปตาม Distinct Usernames',
      order: 16,
    },
    {
      question: 'เครื่องมือ "Chainsaw" หรือ "Hayabusa" ถูกนำมาใช้ในงาน Threat Hunting ด้านใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'สแกนและคัดกรองไฟล์ Windows Event Logs (.evtx) แบบออฟไลน์ด้วยความเร็วสูงโดยใช้กฎ Sigma Rules' },
        { key: 'B', text: 'ตัดต้นไม้ในป่า' },
        { key: 'C', text: 'สร้างภาพเคลื่อนไหว 3D' },
        { key: 'D', text: 'แชทกับเพื่อน' },
      ],
      correctAnswer: 'A',
      explanation: 'Hayabusa และ Chainsaw เขียนด้วย Rust/Go สามารถสแกนไฟล์ EVTX หลายกิกะไบต์เทียบกับ Sigma rules ได้อย่างรวดเร็วภายในไม่กี่วินาที',
      order: 17,
    },
    {
      question: 'พฤติกรรม "Parent-Child Process Anomaly" ข้อใดที่ควรส่งสัญญาณเตือนภัยระดับสูง (High Alert) ทันที?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '`httpd.exe` หรือ `w3wp.exe` (Web Server) สปอว์นสร้าง Process ลูกเป็น `cmd.exe` หรือ `powershell.exe` (บ่งชี้การโดน Web Shell / RCE)' },
        { key: 'B', text: '`explorer.exe` เรียกเปิด `notepad.exe`' },
        { key: 'C', text: '`chrome.exe` เรียกเปิด `chrome.exe`' },
        { key: 'D', text: '`services.exe` ทำงานตามปกติ' },
      ],
      correctAnswer: 'A',
      explanation: 'เว็บเซิร์ฟเวอร์ไม่ควรสร้าง Command Shell ภายใต้การทำงานปกติ หากเกิดขึ้นแสดงว่ามีการสั่งรันคำสั่งผ่าน Webshell หรือช่องโหว่ RCE',
      order: 18,
    },
    {
      question: 'การวิเคราะห์ "DNS Tunneling" เพื่อตรวจจับการขโมยข้อมูลลับ (Data Exfiltration) ดูจากสิ่งบ่งชี้ใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'จำนวน DNS Queries ที่มี Subdomain ขนาดยาวผิดปกติและมีลักษณะการเข้ารหัส Base64/Hex (เช่น `aXJmMjM0...example.com`) เป็นปริมาณมาก' },
        { key: 'B', text: 'การค้นหาเว็บ Google' },
        { key: 'C', text: 'การเปิดดูรูปภาพในเว็บ' },
        { key: 'D', text: 'การดาวน์โหลดไฟล์เสียง' },
      ],
      correctAnswer: 'A',
      explanation: 'DNS Tunneling ซ่อนข้อมูลลับไว้ใน Subdomain เพื่อส่งผ่าน DNS Resolver หลบเลี่ยงไฟร์วอลล์ที่บล็อกพอร์ต HTTP/HTTPS',
      order: 19,
    },
    {
      question: 'ตัวบ่งชี้ "Misp / TheHive" ในศูนย์ปฏิบัติการ SOC ทำหน้าที่อะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'MISP ใช้สำหรับแชร์ข้อมูล Threat Intelligence (IoCs) ส่วน TheHive เป็นระบบ Security Incident Response Platform สำหรับจัดการเคสการสอบสวน' },
        { key: 'B', text: 'เป็นโปรแกรมเล่นเพลง' },
        { key: 'C', text: 'เป็นระบบควบคุมกล้องวงจรปิด' },
        { key: 'D', text: 'เป็นเครื่องมือออกแบบโลโก้' },
      ],
      correctAnswer: 'A',
      explanation: 'MISP + TheHive เป็นชุดเครื่องมือ Open-Source มาตรฐานที่ SOC ทั่วโลกใช้ผสานข้อมูลข่าวกรองภัยคุกคามและการบริหารจัดการเคส',
      order: 20,
    },
  ],

  // 4. Memory & Disk Forensics (Volatility, Autopsy, Registry, Timeline Analysis)
  'lesson-a3-1': [
    {
      question: 'ขั้นตอนแรกสุดที่สำคัญที่สุดตามหลักการ Forensic Acquisition (การเก็บพยานหลักฐานดิจิทัล) คืออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การรักษาสภาพพยานหลักฐานและคำนวณค่า Cryptographic Hash (MD5/SHA-256) ของภาพสำเนาหลักฐานทันทีเพื่อรับรองความถูกต้องสมบูรณ์ (Integrity)' },
        { key: 'B', text: 'การเปิดเครื่องคอมพิวเตอร์และเล่นเกม' },
        { key: 'C', text: 'การลบไฟล์ที่ไม่จำเป็นทิ้ง' },
        { key: 'D', text: 'การฟอร์แมตฮาร์ดดิสก์' },
      ],
      correctAnswer: 'A',
      explanation: 'หลักการ Chain of Custody และ Forensic Soundness กำหนดว่าต้องสร้าง Bit-by-bit Image และทำ Hashing ทันทีเพื่อพิสูจน์ว่าหลักฐานไม่มีการถูกดัดแปลงในชั้นศาล',
      order: 1,
    },
    {
      question: 'ตามลำดับความผันผวนของข้อมูล (Order of Volatility - RFC 3227) ข้อมูลชนิดใดควรได้รับการเก็บกู้เป็นลำดับแรกสุดก่อนที่จะสูญหาย?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'CPU Registers, Caches, และหน่วยความจำแรม (RAM / Physical Memory)' },
        { key: 'B', text: 'ข้อมูลบนฮาร์ดดิสก์ (Hard Drive)' },
        { key: 'C', text: 'สื่อบันทึกข้อมูลแบบเทปสำรอง (Backup Tapes)' },
        { key: 'D', text: 'เอกสารที่พิมพ์ออกมาทางกระดาษ' },
      ],
      correctAnswer: 'A',
      explanation: 'ข้อมูลใน RAM จะสูญหายทันทีเมื่อปิดเครื่อง (Volatile) จึงต้องทำ Memory Dump เป็นสิ่งแรกเพื่อเก็บรักษา Running processes, Unencrypted keys, และ Network connections',
      order: 2,
    },
    {
      question: 'เครื่องมือ "Volatility Framework" (เช่น Volatility 3) ถูกออกแบบมาเพื่อการวิเคราะห์หลักฐานประเภทใดโดยเฉพาะ?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Memory Forensics (การวิเคราะห์ภาพสำเนาหน่วยความจำ RAM Image / Memory Dump)' },
        { key: 'B', text: 'การกู้คืนฮาร์ดดิสก์ที่ตกน้ำ' },
        { key: 'C', text: 'การออกแบบชิปประมวลผล' },
        { key: 'D', text: 'การวัดความเร็วพัดลมซีพียู' },
      ],
      correctAnswer: 'A',
      explanation: 'Volatility เป็นเครื่องมือระดับแนวหน้าของโลกในการวิเคราะห์ Memory Dumps ของ Windows, Linux, macOS เพื่อหา Injected Code, Hidden Processes, Passwords',
      order: 3,
    },
    {
      question: 'ปลั๊กอิน `windows.malfind` ใน Volatility มีความสามารถในการตรวจหาอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ตรวจหาพื้นที่หน่วยความจำที่มีการตั้งค่าสิทธิ์เป็น PAGE_EXECUTE_READWRITE (RWX) และมีร่องรอยของการทำ Code Injection หรือ DLL Injection' },
        { key: 'B', text: 'ค้นหาไฟล์รูปภาพแมว' },
        { key: 'C', text: 'ลบไวรัสออกจากแรม' },
        { key: 'D', text: 'วัดอุณหภูมิของแรม' },
      ],
      correctAnswer: 'A',
      explanation: 'malfind ไฮไลต์ Memory VAD ที่สามารถทั้งเขียนและรันโค้ดได้ (RWX) ซึ่งเป็นคุณสมบัติเด่นของ Shellcode Injection',
      order: 4,
    },
    {
      question: 'เครื่องมือ "Autopsy / The Sleuth Kit (TSK)" มีบทบาทหน้าที่หลักด้านใดในงานพิสูจน์หลักฐาน?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Disk Forensics (การวิเคราะห์ภาพสำเนาฮาร์ดดิสก์, กู้คืนไฟล์ที่ถูกลบ, วิเคราะห์ Web History, Timeline Analysis และแยกแยะ Artifacts)' },
        { key: 'B', text: 'การผ่าตัดชันสูตรศพมนุษย์' },
        { key: 'C', text: 'การซ่อมแซมแผงวงจรไฟฟ้า' },
        { key: 'D', text: 'การตัดต่อวิดีโอวงจรปิด' },
      ],
      correctAnswer: 'A',
      explanation: 'Autopsy เป็น GUI Digital Forensics Platform แบบ Open Source ยอดนิยมสำหรับวิเคราะห์ Raw disk images (E01/DD)',
      order: 5,
    },
    {
      question: 'ไฟล์ "Prefetch Files" (`.pf` ใน `C:\\Windows\\Prefetch`) บนระบบปฏิบัติการ Windows มีประโยชน์อย่างยิ่งในการสืบสวนคดีอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'พิสูจน์ว่าโปรแกรมหรือไฟล์ .exe นั้นเคยถูกสั่งรันจริงบนเครื่อง พร้อมระบุเวลาที่รันล่าสุด (Last Execution Time) และจำนวนครั้งที่รัน (Run Count)' },
        { key: 'B', text: 'กู้คืนรหัสผ่านของระบบ' },
        { key: 'C', text: 'เพิ่มความเร็วในการเชื่อมต่อ Wi-Fi' },
        { key: 'D', text: 'บันทึกเสียงสนทนา' },
      ],
      correctAnswer: 'A',
      explanation: 'Windows Prefetch สร้างขึ้นเพื่อเร่งความเร็วการเปิดแอป แต่นักนิติวิทยาศาสตร์ใช้เป็นหลักฐานยืนยันว่ามัลแวร์ตัวนั้นเคยถูกเปิดรันบนเครื่องจริงหรือไม่',
      order: 6,
    },
    {
      question: 'ข้อมูล "Amcache.hve" และ "Shimcache (AppCompatCache)" บน Windows Registry มีคุณค่าด้านการสืบสวนอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'บันทึกประวัติเส้นทาง (Path), ขนาดไฟล์, และ SHA-1 Hash ของโปรแกรม Executables ที่เคยรันบนเครื่อง แม้ไฟล์ตัวจริงจะถูกลบไปแล้วก็ตาม' },
        { key: 'B', text: 'เก็บข้อมูลรายชื่อเพื่อนในโซเชียลมีเดีย' },
        { key: 'C', text: 'เก็บรูปถ่ายโปรไฟล์' },
        { key: 'D', text: 'บันทึกประวัติการเปลี่ยนภาษา' },
      ],
      correctAnswer: 'A',
      explanation: 'Shimcache และ Amcache ช่วยให้นักสืบสวนพบร่องรอยและแฮชของมัลแวร์ที่ผู้โจมตีรันแล้วสั่งลบไฟล์ตัวเองทิ้งไปแล้วได้',
      order: 7,
    },
    {
      question: 'โครงสร้าง "MFT" (Master File Table) บนระบบไฟล์แบบ NTFS เก็บข้อมูลอะไรเกี่ยวกับไฟล์?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ข้อมูล Metadata ของไฟล์ทุกไฟล์ เช่น ชื่อไฟล์, ขนาด, ตำแหน่งคลัสเตอร์, และข้อมูลเวลา $STANDARD_INFORMATION และ $FILE_NAME (MACB Timestamps)' },
        { key: 'B', text: 'เก็บเฉพาะไฟล์เพลง MP3' },
        { key: 'C', text: 'เก็บรหัสผ่าน Wi-Fi' },
        { key: 'D', text: 'เก็บประวัติการสนทนาทางโทรศัพท์' },
      ],
      correctAnswer: 'A',
      explanation: '$MFT คือหัวใจของ NTFS ที่บันทึก Attributes ทั้งหมดของไฟล์ การวิเคราะห์ $MFT ($MFT Parser) ช่วยสร้าง Timeline เหตุการณ์ได้อย่างแม่นยำ',
      order: 8,
    },
    {
      question: 'เทคนิค "Timestomping" คืออะไร และมักทำไปเพื่อจุดประสงค์ใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การที่ผู้โจมตีจงใจแก้ไขค่าเวลา $STANDARD_INFORMATION (Created, Modified) ของมัลแวร์ให้ตรงกับไฟล์ระบบของ Windows เพื่อหลอกการทำ Timeline Analysis' },
        { key: 'B', text: 'การเปลี่ยนเวลาของนาฬิกาข้อมือ' },
        { key: 'C', text: 'การทำลายหน้าจอคอมพิวเตอร์' },
        { key: 'D', text: 'การเร่งความเร็วของระบบ' },
      ],
      correctAnswer: 'A',
      explanation: 'ผู้โจมตีแก้ Timestamps ให้เหมือนไฟล์ระบบปกติ แต่นักสืบสวนสามารถตรวจจับได้โดยการเปรียบเทียบกับแอตทริบิวต์ `$FILE_NAME` ใน $MFT ซึ่งแก้ได้ยากกว่า',
      order: 9,
    },
    {
      question: 'ข้อมูล "Shellbags" ใน Windows Registry บันทึกร่องรอยกิจกรรมใดของผู้ใช้งาน?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'บันทึกประวัติโฟลเดอร์ที่ผู้ใช้เคยเปิดดูผ่าน Windows Explorer รวมถึงโฟลเดอร์บน Network Share หรือ External USB Drive ที่ถูกถอดออกไปแล้ว' },
        { key: 'B', text: 'บันทึกประวัติการช้อปปิ้งออนไลน์' },
        { key: 'C', text: 'บันทึกระดับเสียงลำโพง' },
        { key: 'D', text: 'บันทึกการพิมพ์ข้อความ' },
      ],
      correctAnswer: 'A',
      explanation: 'Shellbags พิสูจน์ว่าผู้ต้องสงสัยเคยเปิดเข้าไปดูโฟลเดอร์ลับใดบ้าง แม้โฟลเดอร์นั้นจะถูกลบหรืออยู่ใน USB Drive ที่ถอดออกไปแล้ว',
      order: 10,
    },
    {
      question: 'ฟังก์ชัน "File Carving" (เช่น เครื่องมือ Scalpel หรือ Foremost) ทำงานอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'กู้คืนไฟล์จากพื้นที่ Unallocated Space โดยค้นหา Header (Magic Bytes) และ Footer ของไฟล์โดยตรงโดยไม่ต้องพึ่งพาข้อมูล File System Metadata' },
        { key: 'B', text: 'การแกะสลักเคสคอมพิวเตอร์' },
        { key: 'C', text: 'การลบไฟล์แบบถาวร' },
        { key: 'D', text: 'การบีบอัดไฟล์เป็น zip' },
      ],
      correctAnswer: 'A',
      explanation: 'File Carving อ่าน Raw Bytes บนดิสก์เพื่อหากลุ่ม Magic Bytes (เช่น `\xFF\xD8\xFF` สำหรับ JPEG) เพื่อประกอบไฟล์ที่ถูกลบและ Metadata เสียหายกลับคืนมา',
      order: 11,
    },
    {
      question: 'ไฟล์ `$LogFile` และ `$UsnJrnl` ($J) บน NTFS มีความสำคัญต่องานสืบสวนอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'บันทึกประวัติการเปลี่ยนแปลงของไฟล์ในระดับ Transaction (สร้าง, ลบ, แก้ไข, เปลี่ยนชื่อ) ช่วยให้ทราบว่าไฟล์ใดถูกลบหรือถูกแก้ไขในช่วงเวลาเกิดเหตุ' },
        { key: 'B', text: 'เก็บข้อมูลรายชื่อพนักงาน' },
        { key: 'C', text: 'เก็บไฟล์ภาพถ่าย' },
        { key: 'D', text: 'เก็บข้อมูลการชำระเงิน' },
      ],
      correctAnswer: 'A',
      explanation: 'USN Change Journal บันทึกทุกธุรกรรมของระบบไฟล์ ทำให้สามารถสืบหาไฟล์ที่มัลแวร์สร้างขึ้นแล้วลบทิ้งได้อย่างละเอียดเป็นวินาที',
      order: 12,
    },
    {
      question: 'เครื่องมือ "Write Blocker" (แบบฮาร์ดแวร์หรือซอฟต์แวร์) มีหน้าที่สำคัญอย่างไรในขั้นตอนการทำ Disk Acquisition?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ป้องกันไม่ให้ระบบปฏิบัติการของเครื่องนักสืบสวนเขียนหรือแก้ไขข้อมูลใดๆ ลงบนฮาร์ดดิสก์พยานหลักฐานต้นฉบับในระหว่างการเชื่อมต่อและทำสำเนา' },
        { key: 'B', text: 'ป้องกันไม่ให้ไฟดับ' },
        { key: 'C', text: 'เพิ่มความเร็วในการอ่านข้อมูล' },
        { key: 'D', text: 'ลบไวรัสบนฮาร์ดดิสก์' },
      ],
      correctAnswer: 'A',
      explanation: 'Write Blocker บล็อกคำสั่ง Write ขาเข้า ป้องกันไม่ให้ OS แอบเขียน Metadata หรือ Timestamp ทับหลักฐานต้นฉบับ',
      order: 13,
    },
    {
      question: 'ชิ้นส่วน "LNK Files" (Windows Shortcuts) ในโฟลเดอร์ Recent Items บ่งชี้ข้อมูลใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'หลักฐานการเปิดไฟล์เอกสารหรือโปรแกรม ระบุ Target Path, Drive Type, หมายเลข Volume Serial Number, และ MAC Address ของเครื่องต้นทาง' },
        { key: 'B', text: 'ข้อมูลรหัสผ่าน Wi-Fi' },
        { key: 'C', text: 'รูปภาพพื้นหลัง' },
        { key: 'D', text: 'คะแนนการเล่นเกม' },
      ],
      correctAnswer: 'A',
      explanation: 'LNK Files เก็บข้อมูลเชิงลึกเกี่ยวกับไฟล์ปลายทางที่เคยถูกเปิด แม้ไฟล์ต้นทางจะอยู่บน Flash Drive หรือถูกลบไปแล้ว',
      order: 14,
    },
    {
      question: 'การตรวจสอบ "USB Device Artifacts" บน Windows Registry (เช่น `USBSTOR`) ช่วยให้นักสืบสวนทราบอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'รายชื่อยี่ห้อ, รุ่น, หมายเลข Serial Number ของ Flash Drive ทุกตัวที่เคยเสียบเข้ากับเครื่อง พร้อมวันเวลาที่เสียบครั้งแรกและครั้งล่าสุด' },
        { key: 'B', text: 'ปริมาณไฟฟ้าที่จ่ายให้พอร์ต USB' },
        { key: 'C', text: 'ความยาวของสาย USB' },
        { key: 'D', text: 'สีของตัว Flash Drive' },
      ],
      correctAnswer: 'A',
      explanation: 'USBSTOR และ setupapi.dev.log บันทึกประวัติ USB ทุกชิ้น ช่วยพิสูจน์คดีขโมยข้อมูลลับองค์กร (Data Exfiltration via USB) ได้อย่างชัดเจน',
      order: 15,
    },
    {
      question: 'รูปแบบไฟล์พยานหลักฐาน "E01" (Expert Witness Format) มีคุณสมบัติเด่นเหนือกว่า Raw DD Image อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'มีการบีบอัดข้อมูล, เก็บข้อมูล Case Metadata, และฝังค่า Checksum/Hash ประจำแต่ละบล็อกเพื่อตรวจสอบความถูกต้องสมบูรณ์ในตัว' },
        { key: 'B', text: 'สามารถเปิดดูเป็นภาพเคลื่อนไหวได้' },
        { key: 'C', text: 'สามารถแก้ไขข้อความภายในไฟล์ได้อิสระ' },
        { key: 'D', text: 'ไม่มีความแตกต่างกัน' },
      ],
      correctAnswer: 'A',
      explanation: 'E01 (EnCase Image Format) เป็นมาตรฐานสากลที่ศาลยอมรับเนื่องจากมีระบบ Integrity Hash ตรวจสอบความถูกต้องของแต่ละส่วนในไฟล์',
      order: 16,
    },
    {
      question: 'ปลั๊กอิน `windows.pstree` ใน Volatility มีประโยชน์อย่างไรในการสืบสวน?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'แสดงความสัมพันธ์ของ Process ในรูปแบบแผนภูมิต้นไม้ (Parent-Child Process Tree) ช่วยตรวจหา Process แปลกปลอมที่ถูกสร้างจากโปรแกรมที่ไม่เหมาะสม' },
        { key: 'B', text: 'ปลูกต้นไม้ในเกมจำลอง' },
        { key: 'C', text: 'ตรวจสอบประวัติการพิมพ์งาน' },
        { key: 'D', text: 'แสดงภาพพื้นหลังหน้าจอ' },
      ],
      correctAnswer: 'A',
      explanation: 'pstree ช่วยให้เห็นชัดเจนทันที เช่น พบว่า cmd.exe ถูกสร้างขึ้นมาจาก WINWORD.EXE หรือ w3wp.exe ซึ่งเป็นพฤติกรรมผิดปกติร้ายแรง',
      order: 17,
    },
    {
      question: 'คำว่า "MACB Timestamps" ในการวิเคราะห์ลำดับเหตุการณ์ (Timeline Analysis) ย่อมาจากอะไรตามลำดับ?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Modified (แก้ไขเนื้อหา), Accessed (เข้าถึง/เปิดอ่าน), Created / Changed ($MFT Modified), Birth (วันที่สร้างไฟล์ครั้งแรก)' },
        { key: 'B', text: 'MAC Address, Control, Boot, Base' },
        { key: 'C', text: 'Master, Administrator, Client, Backup' },
        { key: 'D', text: 'Memory, Address, Cache, Buffer' },
      ],
      correctAnswer: 'A',
      explanation: 'MACB (M: Modified, A: Accessed, C: MFT Record Changed, B: Birth/Creation) เป็น 4 ค่าเวลามาตรฐานในการพล็อต Super Timeline',
      order: 18,
    },
    {
      question: 'ไฟล์ `hiberfil.sys` และ `pagefile.sys` บนระบบปฏิบัติการ Windows มีคุณค่าต่องาน Memory Forensics อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เป็นไฟล์สำเนาหน่วยความจำ RAM ที่ระบบเขียนลงดิสก์เมื่อเข้าสู่โหมด Hibernate หรือทำ Paging ซึ่งอาจมีข้อมูลรหัสผ่านและคีย์ลับหลงเหลืออยู่' },
        { key: 'B', text: 'เป็นไฟล์ระบบที่ไม่มีข้อมูลใดๆ' },
        { key: 'C', text: 'เป็นไฟล์เก็บรูปถ่ายครอบครัว' },
        { key: 'D', text: 'เป็นไฟล์ติดตั้งโปรแกรม Office' },
      ],
      correctAnswer: 'A',
      explanation: 'hiberfil.sys เก็บสแน็ปช็อตของ RAM ทั้งหมดก่อนเครื่องดับ สามารถนำมาแตกไฟล์และวิเคราะห์ใน Volatility ได้เหมือน RAM ดัมป์สด',
      order: 19,
    },
    {
      question: 'แนวคิด "Chain of Custody" ในกระบวนการนิติวิทยาศาสตร์ดิจิทัลมีความสำคัญสูงสุดในเรื่องใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'บันทึกเอกสารแสดงลำดับขั้นตอนการครอบครอง, การส่งมอบ, วันเวลา, และผู้รับผิดชอบพยานหลักฐานอย่างต่อเนื่อง เพื่อให้หลักฐานมีน้ำหนักรับฟังได้ในชั้นศาล' },
        { key: 'B', text: 'การล็อคกุญแจห้องเซิร์ฟเวอร์' },
        { key: 'C', text: 'การผูกสายแลนเข้าด้วยกัน' },
        { key: 'D', text: 'การเชื่อมต่อบลูทูธ' },
      ],
      correctAnswer: 'A',
      explanation: 'หากขาด Chain of Custody หรือมีช่วงเวลาที่ไม่สามารถระบุได้ว่าใครเป็นผู้ดูแลหลักฐาน ทนายฝ่ายตรงข้ามสามารถคัดค้านไม่ให้ศาลรับฟังหลักฐานชิ้นนั้นได้',
      order: 20,
    },
  ],

  // 5. Incident Response, Ransomware Containment & NIST/SANS Frameworks
  'lesson-a3-2': [
    {
      question: 'ขั้นตอนทั้ง 6 ของวงจรการตอบสนองต่อภัยคุกคามตามกรอบมาตรฐาน SANS Incident Response เรียงตามลำดับอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: '1. Preparation -> 2. Identification -> 3. Containment -> 4. Eradication -> 5. Recovery -> 6. Lessons Learned' },
        { key: 'B', text: '1. Recovery -> 2. Eradication -> 3. Preparation -> 4. Identification -> 5. Lessons Learned -> 6. Containment' },
        { key: 'C', text: '1. Identification -> 2. Preparation -> 3. Recovery -> 4. Eradication -> 5. Containment -> 6. Lessons Learned' },
        { key: 'D', text: '1. Lessons Learned -> 2. Preparation -> 3. Identification -> 4. Containment -> 5. Eradication -> 6. Recovery' },
      ],
      correctAnswer: 'A',
      explanation: 'วงจรมาตรฐาน SANS PICERL: เตรียมพร้อม (Preparation) -> ตรวจสอบระบุเหตุ (Identification) -> ควบคุมจำกัดวง (Containment) -> กำจัดต้นตอ (Eradication) -> ฟื้นฟูระบบ (Recovery) -> ถอดบทเรียน (Lessons Learned)',
      order: 1,
    },
    {
      question: 'เมื่อตรวจพบว่าเครื่องคอมพิวเตอร์ในองค์กรกำลังถูก Ransomware ทำการเข้ารหัสไฟล์ มาตรการ Containment ขั้นแรกที่ต้องทำทันทีคืออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ตัดการเชื่อมต่อเครือข่ายของเครื่องนั้นทันที (ถอดสายแลน / ปิด Wi-Fi / สั่ง Network Isolation ผ่าน EDR) โดย "ห้ามปิดเครื่อง (Do NOT Power Off)" ทันทีหากต้องการเก็บ Memory หลักฐาน' },
        { key: 'B', text: 'จ่ายเงินค่าไถ่เป็น Bitcoin ทันที' },
        { key: 'C', text: 'ส่งอีเมลแจ้งเตือนพนักงานทุกคน' },
        { key: 'D', text: 'ฟอร์แมตเครื่องทันทีโดยไม่สำรองข้อมูล' },
      ],
      correctAnswer: 'A',
      explanation: 'การตัดการเชื่อมต่อเครือข่ายป้องกันไม่ให้ Ransomware แพร่กระจายไปยัง Shared Drive หรือเครื่องอื่น และการไม่ปิดเครื่องช่วยให้สามารถดัมป์ RAM เพื่อเก็บรหัสหรือกุญแจถอดรหัสได้',
      order: 2,
    },
    {
      question: 'กรอบการทำงาน "NIST Cybersecurity Framework" (NIST CSF 2.0) ประกอบด้วย Core Functions หลัก 6 ด้านใดบ้าง?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'Govern, Identify, Protect, Detect, Respond, Recover' },
        { key: 'B', text: 'Plan, Do, Check, Act, Buy, Sell' },
        { key: 'C', text: 'Input, Output, Process, Storage, Control, Feedback' },
        { key: 'D', text: 'Hardware, Software, Network, Database, People, Policy' },
      ],
      correctAnswer: 'A',
      explanation: 'NIST CSF 2.0 เพิ่มเติมฟังก์ชัน "Govern" เข้ามาร่วมกับ 5 ฟังก์ชันเดิม (Identify, Protect, Detect, Respond, Recover) เพื่อครอบคลุมการกำกับดูแลระดับองค์กร',
      order: 3,
    },
    {
      question: 'ในขั้นตอน "Eradication" ของกระบวนการตอบสนองต่อเหตุการณ์ ทีมความปลอดภัยต้องดำเนินการสิ่งใด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'กำจัดมัลแวร์, ปิดบัญชีที่ถูก Compromised, ลบ Backdoors และ Persistence Mechanisms ทั้งหมด, พร้อมทั้งปิดช่องโหว่ที่เป็นจุดเริ่มต้นของการบุกรุก' },
        { key: 'B', text: 'การจัดงานเลี้ยงฉลอง' },
        { key: 'C', text: 'การซื้อคอมพิวเตอร์ใหม่ให้พนักงานทุกคน' },
        { key: 'D', text: 'การหยุดให้บริการอย่างถาวร' },
      ],
      correctAnswer: 'A',
      explanation: 'Eradication มุ่งเน้นการขุดรากถอนโคนภัยคุกคามออกจากระบบอย่างสมบูรณ์ เพื่อให้มั่นใจว่าจะไม่มีการแอบกลับเข้ามาได้อีก',
      order: 4,
    },
    {
      question: 'การสำรองข้อมูลตามกลยุทธ์ "กฎสำรองข้อมูล 3-2-1-1-0" มีหลักการสำคัญอย่างไรในการรับมือ Ransomware?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เก็บข้อมูล 3 ชุด, บนสื่อ 2 ชนิด, 1 ชุดอยู่นอกสถานที่ (Off-site), 1 ชุดเป็น Immutable/Air-gapped (แก้ไม่ได้/ตัดขาดเน็ต), และ 0 ข้อผิดพลาดหลังทดสอบ Restore' },
        { key: 'B', text: 'สำรองข้อมูลวันละ 3 ครั้ง บนฮาร์ดดิสก์ 2 ตัว ใช้เวลา 1 ชั่วโมง' },
        { key: 'C', text: 'เก็บข้อมูลไว้ใน Flash Drive 3 อัน' },
        { key: 'D', text: 'ส่งไฟล์ทางอีเมลหากัน 3 คน' },
      ],
      correctAnswer: 'A',
      explanation: 'Immutable Backups (WORM: Write Once, Read Many) และ Air-gapped Backups เป็นเกราะป้องกันชั้นสุดท้ายที่ Ransomware ไม่สามารถเข้าทำลายหรือเข้ารหัสทับได้',
      order: 5,
    },
    {
      question: 'การโจมตีแบบ "Double Extortion Ransomware" หมายถึงอะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ผู้โจมตีทำการ "ขโมยข้อมูลลับออกไปภายนอก (Data Exfiltration)" ก่อน แล้วจึงทำการ "เข้ารหัสไฟล์" เพื่อขู่กรรโชกเงิน 2 ทาง (ค่าถอดรหัส และค่าไม่ให้ปล่อยข้อมูลสู่สาธารณะ)' },
        { key: 'B', text: 'การเรียกค่าไถ่เป็นจำนวนเงิน 2 เท่า' },
        { key: 'C', text: 'การโดน Ransomware สองตัวพร้อมกัน' },
        { key: 'D', text: 'การส่งจดหมายเรียกค่าไถ่สองฉบับ' },
      ],
      correctAnswer: 'A',
      explanation: 'Double Extortion ทำให้องค์กรแม้จะมี Backup กู้คืนได้ ก็ยังถูกกดดันด้วยการขู่เปิดเผยข้อมูลความลับและข้อมูลลูกค้าสู่ Dark Web หากไม่ยอมจ่ายค่าไถ่',
      order: 6,
    },
    {
      question: 'เป้าหมายสำคัญที่สุดของการจัดประชุม "Lessons Learned / Post-Incident Review" คืออะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'วิเคราะห์สิ่งที่เกิดขึ้นอย่างตรงไปตรงมา, ประเมินจุดบกพร่อง, ปรับปรุง Playbook, และอุดช่องว่างเพื่อป้องกันไม่ให้เกิดเหตุการณ์ซ้ำเดิมในอนาคต (No-blame Culture)' },
        { key: 'B', text: 'หาตัวคนผิดมาลงโทษและไล่ออก' },
        { key: 'C', text: 'การจัดทำเอกสารเพื่อเพิ่มยอดขาย' },
        { key: 'D', text: 'การปิดเรื่องให้เงียบที่สุด' },
      ],
      correctAnswer: 'A',
      explanation: 'Lessons Learned เป็นการถอดบทเรียนเพื่อปรับปรุงกระบวนการและระบบให้แข็งแกร่งขึ้น (Continuous Improvement) โดยไม่เน้นการกล่าวโทษบุคคล',
      order: 7,
    },
    {
      question: 'การฝึกซ้อมสถานการณ์จำลองแบบ "Tabletop Exercise" (TTX) มีประโยชน์ต่อองค์กรอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เป็นการซ้อมแผนบนโต๊ะจำลองสถานการณ์วิกฤตไซเบอร์เสมือนจริง เพื่อทดสอบความพร้อมในการตัดสินใจ, การสื่อสาร, และบทบาทหน้าที่ของทีมผู้บริหารและฝ่ายเทคนิค' },
        { key: 'B', text: 'การจัดโต๊ะทำงานให้เป็นระเบียบ' },
        { key: 'C', text: 'การเล่นเกมกระดานในเวลาว่าง' },
        { key: 'D', text: 'การทำความสะอาดอุปกรณ์ไอที' },
      ],
      correctAnswer: 'A',
      explanation: 'Tabletop Exercise ช่วยระบุจุดบกพร่องในแผนตอบสนองฉุกเฉิน (IR Plan) และฝึกทักษะการตัดสินใจในภาวะวิกฤตโดยไม่กระทบต่อระบบ Production จริง',
      order: 8,
    },
    {
      question: 'ดัชนีชี้วัด "MTTD" (Mean Time to Detect) และ "MTTR" (Mean Time to Respond) มีความสำคัญอย่างไรในศูนย์ SOC?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'MTTD วัดระยะเวลาเฉลี่ยตั้งแต่เริ่มถูกบุกรุกจนกระทั่งตรวจพบ ส่วน MTTR วัดระยะเวลาเฉลี่ยตั้งแต่ตรวจพบจนกระทั่งควบคุมและกำจัดภัยคุกคามสำเร็จ' },
        { key: 'B', text: 'MTTD วัดความเร็วอินเทอร์เน็ต ส่วน MTTR วัดความเร็วซีพียู' },
        { key: 'C', text: 'MTTD วัดระยะทางสายแลน ส่วน MTTR วัดขนาดฮาร์ดดิสก์' },
        { key: 'D', text: 'ไม่มีความสำคัญใดๆ' },
      ],
      correctAnswer: 'A',
      explanation: 'ยิ่ง MTTD และ MTTR สั้นลงเท่าใด โอกาสที่ผู้โจมตีจะสร้างความเสียหายหรือขโมยข้อมูลสำคัญสำเร็จก็จะยิ่งลดน้อยลงเท่านั้น',
      order: 9,
    },
    {
      question: 'ข้อใดคือหลักเกณฑ์สำคัญในการรายงานเหตุการณ์ละเมิดข้อมูลส่วนบุคคลตามกฎหมาย PDPA (ประเทศไทย) หรือ GDPR?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ต้องแจ้งเหตุการณ์ละเมิดแก่สำนักงานคณะกรรมการคุ้มครองข้อมูลส่วนบุคคล (สคส.) ภายใน 72 ชั่วโมงนับแต่ทราบเหตุ หากมีความเสี่ยงสูงต่อสิทธิเสรีภาพของบุคคล' },
        { key: 'B', text: 'สามารถรอรายงานได้ภายใน 1 ปี' },
        { key: 'C', text: 'ไม่จำเป็นต้องรายงานหากไม่มีใครถาม' },
        { key: 'D', text: 'รายงานเฉพาะเมื่อบริษัทปิดกิจการ' },
      ],
      correctAnswer: 'A',
      explanation: 'กฎหมายคุ้มครองข้อมูลส่วนบุคคลสากล (รวมถึง PDPA ของไทย) กำหนดกรอบเวลาแจ้งเตือนที่เข้มงวดภายใน 72 ชั่วโมงเมื่อเกิด Data Breach',
      order: 10,
    },
    {
      question: 'เครื่องมือ "EDR" (Endpoint Detection and Response) แตกต่างจากโปรแกรม Antivirus แบบดั้งเดิมอย่างไรในงาน Incident Response?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'EDR บันทึก Telemetry และพฤติกรรมในเครื่องตลอดเวลา, แสดง Process Tree ย้อนหลัง, รองรับการสั่งกักกันเครื่อง (Network Isolation) และ Live Response ทางไกล' },
        { key: 'B', text: 'EDR ทำงานเฉพาะเมื่อไม่มีอินเทอร์เน็ต' },
        { key: 'C', text: 'Antivirus ป้องกันได้ดีกว่า EDR 100 เท่า' },
        { key: 'D', text: 'ไม่มีความแตกต่างกัน' },
      ],
      correctAnswer: 'A',
      explanation: 'EDR ช่วยให้ทีม IR สามารถสืบสวนหาสาเหตุต้นตอ (Root Cause Analysis), สั่งกักกันเครื่องจากระยะไกล, และกวาดล้างร่องรอยทั่วทั้งองค์กรได้อย่างรวดเร็ว',
      order: 11,
    },
    {
      question: 'ในระหว่างเกิดเหตุการณ์วิกฤตไซเบอร์ "Out-of-Band Communication" มีความจำเป็นอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ใช้ช่องทางสื่อสารสำรองภายนอก (เช่น แอพแชท Signal หรือโทรศัพท์สายตรง) ที่แยกจากระบบเครือข่าย/อีเมลองค์กร เพื่อป้องกันผู้โจมตีที่แฝงตัวอยู่แอบดักฟังแผนรับมือ' },
        { key: 'B', text: 'เพื่อประหยัดค่าโทรศัพท์' },
        { key: 'C', text: 'เพื่อส่งไฟล์เพลงขนาดใหญ่' },
        { key: 'D', text: 'เพื่อเพิ่มความเร็วอินเทอร์เน็ต' },
      ],
      correctAnswer: 'A',
      explanation: 'หากอีเมลหรือระบบแชทภายในขององค์กรถูกแฮกเกอร์แอบเข้าถึงได้ การวางแผนรับมือบนช่องทางเดิมจะทำให้ผู้โจมตีรู้ตัวล่วงหน้าและชิงทำลายหลักฐาน',
      order: 12,
    },
    {
      question: 'แนวทางการกู้คืนระบบ (Recovery Phase) หลังการถูก Ransomware โจมตีข้อใดมีความปลอดภัยสูงสุด?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'สร้างระบบใหม่จาก Golden Image / Clean Baseline ที่ปลอดภัย แล้ว Restore เฉพาะข้อมูลไฟล์ดิบที่ผ่านการสแกนและตรวจสอบมัลแวร์แล้วอย่างละเอียด' },
        { key: 'B', text: 'Restore ทับเครื่องเดิมทันทีโดยไม่อัปเดตแพตช์' },
        { key: 'C', text: 'เปิดเครื่องให้ทำงานต่อไปตามปกติ' },
        { key: 'D', text: 'ปิดไฟร์วอลล์เพื่อให้ข้อมูลไหลลื่นขึ้น' },
      ],
      correctAnswer: 'A',
      explanation: 'การ Rebuild ระบบใหม่จาก Clean Image ป้องกันไม่ให้มี Backdoor หรือ Persistence Script ของผู้โจมตีหลงเหลืออยู่ในระดับ OS หรือ Registry',
      order: 13,
    },
    {
      question: 'การตั้งค่า "Canary Files / Honeyfiles" ใน File Shares ขององค์กรมีประโยชน์ด้าน Incident Detection อย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เป็นไฟล์ล่อที่มีการตั้ง Alert ไว้ หากมีโปรแกรมใด (เช่น Ransomware) เข้ามาเปิด แก้ไข หรือเข้ารหัสไฟล์นี้ ระบบจะแจ้งเตือนและตัดการเชื่อมต่อเครื่องนั้นทันที' },
        { key: 'B', text: 'เก็บข้อมูลรหัสผ่านทั้งหมด' },
        { key: 'C', text: 'เพิ่มความจุของ File Server' },
        { key: 'D', text: 'ช่วยจัดระเบียบไฟล์เอกสาร' },
      ],
      correctAnswer: 'A',
      explanation: 'Honeyfiles ทำหน้าที่เป็นสัญญาณเตือนภัยล่วงหน้า (Tripwire) ตรวจจับ Ransomware ตั้งแต่เริ่มเข้ารหัสไฟล์แรกๆ บน Share Drive',
      order: 14,
    },
    {
      question: 'เอกสาร "IR Playbook" (Incident Response Playbook) มีบทบาทสำคัญอย่างไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เป็นคู่มือขั้นตอนปฏิบัติทีละสเต็ป (Step-by-step SOP) สำหรับรับมือกับภัยคุกคามแต่ละประเภทโดยเฉพาะ (เช่น Ransomware, Phishing, DDoS, Data Leak)' },
        { key: 'B', text: 'เป็นหนังสือนิยายให้อ่านในเวลาว่าง' },
        { key: 'C', text: 'เป็นเอกสารสัญญาจ้างงาน' },
        { key: 'D', text: 'เป็นคู่มือการประกอบโต๊ะ' },
      ],
      correctAnswer: 'A',
      explanation: 'IR Playbook ช่วยให้ทีม Incident Responders ปฏิบัติตามขั้นตอนที่ถูกต้อง รวดเร็ว และไม่สับสนภายใต้สถานการณ์กดดัน',
      order: 15,
    },
    {
      question: 'เมื่อยืนยันว่าเกิดเหตุการณ์รั่วไหลของข้อมูลบัญชีผู้ใช้ (Credential Leak) มาตรการ Eradication ข้อใดต้องดำเนินการทันที?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'สั่งยกเลิก Active Sessions และ Revoke Refresh Tokens ทั้งหมด, บังคับรีเซ็ตรหัสผ่าน, และเปิดใช้งาน MFA ทันที' },
        { key: 'B', text: 'รอจนกว่าผู้ใช้จะติดต่อเข้ามาแจ้ง' },
        { key: 'C', text: 'ลบบัญชีผู้ใช้นั้นทิ้งถาวร' },
        { key: 'D', text: 'ส่งอีเมลแจ้งเตือนโดยไม่รีเซ็ตรหัสผ่าน' },
      ],
      correctAnswer: 'A',
      explanation: 'การ Revoke Tokens และตัด Session สำคัญพอๆ กับการเปลี่ยน Password เพื่อเตะผู้โจมตีที่ยังถือ Session ค้างอยู่ออกจากระบบทันที',
      order: 16,
    },
    {
      question: 'ในทีม Incident Response บทบาทของ "Incident Commander" มีหน้าที่อะไร?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'เป็นผู้นำสั่งการภาพรวมในการจัดการเหตุการณ์, ตัดสินใจเชิงยุทธศาสตร์, จัดสรรทรัพยากร, และประสานงานกับผู้บริหารและฝ่ายกฎหมาย' },
        { key: 'B', text: 'เขียนโค้ดแก้บั๊กโปรแกรม' },
        { key: 'C', text: 'ทำหน้าที่เดินสายเคเบิล' },
        { key: 'D', text: 'จัดเตรียมอาหารว่าง' },
      ],
      correctAnswer: 'A',
      explanation: 'Incident Commander ควบคุมสถานการณ์และบริหารทีมเพื่อให้กระบวนการรับมือเป็นไปอย่างมีระบบและมีประสิทธิภาพสูงสุด',
      order: 17,
    },
    {
      question: 'ข้อใดคือตัวอย่างของ "Compensating Controls" ในระหว่างที่ยังไม่สามารถลงแพตช์แก้ไขช่องโหว่ Zero-Day บนระบบ Production ได้ทันที?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'การเขียน Virtual Patching Rule บน WAF หรือ IPS เพื่อบล็อกรูปแบบ Payload ของช่องโหว่นั้นชั่วคราว' },
        { key: 'B', text: 'การปิดระบบรักษาความปลอดภัยทั้งหมด' },
        { key: 'C', text: 'การเพิ่มความสว่างหน้าจอ' },
        { key: 'D', text: 'การลดจำนวนเจ้าหน้าที่ SOC' },
      ],
      correctAnswer: 'A',
      explanation: 'Virtual Patching บน WAF/IPS ช่วยป้องกันการโจมตีได้ทันทีในระหว่างที่ทีมพัฒนายังต้องใช้เวลาทดสอบ Patch ในระบบ Staging',
      order: 18,
    },
    {
      question: 'การจัดทำ "Evidence Bag" และการปิดผนึก "Tamper-Evident Tape" มีความสำคัญอย่างไรในการเก็บพยานหลักฐานทางกายภาพ?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'พิสูจน์ว่าไม่มีผู้ใดแอบเปิดหรือดัดแปลงแก้ไขพยานหลักฐาน (ฮาร์ดดิสก์, โทรศัพท์, แฟลชไดรฟ์) นับตั้งแต่ช่วงเวลาที่ถูกตรวจยึด' },
        { key: 'B', text: 'ป้องกันฝุ่นละออง' },
        { key: 'C', text: 'ทำให้หลักฐานดูสวยงาม' },
        { key: 'D', text: 'เพิ่มราคาของอุปกรณ์' },
      ],
      correctAnswer: 'A',
      explanation: 'สติกเกอร์และถุงกันการแกะทำลาย (Tamper-evident) ช่วยยืนยันความสมบูรณ์ของพยานหลักฐานทางกายภาพในชั้นศาล',
      order: 19,
    },
    {
      question: 'สิ่งใดคือผลลัพธ์ที่เป็นรูปธรรมที่สุดของกระบวนการตอบสนองต่อเหตุการณ์ (Incident Response) ที่ประสบความสำเร็จ?',
      questionType: 'MULTIPLE_CHOICE',
      options: [
        { key: 'A', text: 'ระบบสามารถกลับมาให้บริการได้อย่างปลอดภัยสมบูรณ์, ข้อมูลสูญหายน้อยที่สุด, และองค์กรมีมาตรการป้องกันที่แข็งแกร่งขึ้นเพื่อไม่ให้เกิดเหตุซ้ำ' },
        { key: 'B', text: 'การที่ไม่มีใครทราบว่าเกิดเหตุการณ์ขึ้น' },
        { key: 'C', text: 'การประหยัดงบประมาณด้านไอทีได้ 100%' },
        { key: 'D', text: 'การปิดเซิร์ฟเวอร์ทั้งหมดอย่างถาวร' },
      ],
      correctAnswer: 'A',
      explanation: 'ความสำเร็จของ IR วัดจาก Business Resilience ความรวดเร็วในการฟื้นฟูอย่างปลอดภัย และการยกระดับความมั่นคงปลอดภัยขององค์กรอย่างยั่งยืน',
      order: 20,
    },
  ],
};
